Category.create([
                    {name:'Compact'},
                    {name:'MiniVan'},
                    {name:'PickUp'},
                    {name:'Sport'},
                    {name:'Economy'},
                    {name:'Premium'},
                    {name:'Standard'}
                ])