after :countries do
  countries = Country.all
  austria = countries.where(name: 'Austria').first
  belgium = countries.where(name: 'Belgium').first
  bulgaria = countries.where(name: 'Bulgaria').first
  croatia = countries.where(name: 'Croatia').first
  cyprus = countries.where(name: 'Cyprus').first
  czech = countries.where(name:'Czech Republic').first
  egypt = countries.where(name:'Egypt').first
  estonia = countries.where(name:'Estonia').first
  finland = countries.where(name:'Finland').first
  france  = countries.where(name:'France').first
  germany  = countries.where(name:'Germany').first
  greece = countries.where(name:'Greece').first
  hungary = countries.where(name:'Hungary').first
  italy = countries.where(name:'Italy').first
  latvia = countries.where(name:'Latvia').first
  lithuania = countries.where(name:'Lithuania').first
  luxembourg = countries.where(name:'Luxembourg').first
  malta = countries.where(name:'Malta').first
  netherlands = countries.where(name:'Netherlands').first
  norway = countries.where(name:'Norway').first
  poland = countries.where(name:'Poland').first
  portugal = countries.where(name:'Portugal').first
  romania  = countries.where(name:'Romania').first
  russia = countries.where(name:'Russia').first
  serbia = countries.where(name:'Serbia').first
  slovakia = countries.where(name:'Slovakia').first
  slovenia = countries.where(name:'Slovenia').first
  spain =  countries.where(name:'Spain').first
  switzerland = countries.where(name:'Switzerland').first
  turkey =  countries.where(name:'Turkey').first
  uk =  countries.where(name:'United Kingdom').first

  City.create([
                {name: 'Innsbruck', is_taxi:true, country: austria },
                {name: 'Klagenfurt', is_taxi:true, country: austria},
                {name: 'Salzburg', is_taxi:true, country: austria},
                {name: 'Vienna', is_taxi:true, country: austria},
                {name: 'Antwerp', is_taxi:true, country: belgium },
                {name: 'Bruges', is_taxi:true, country: belgium },
                {name: 'Brussels', is_taxi:true, country: belgium },
                {name: 'Burgas', is_taxi:true, country: bulgaria },
                {name: 'Plovdiv', is_taxi:true, country: bulgaria},
                {name: 'Sofia', is_taxi:true, country: bulgaria},
                {name: 'Varna', is_taxi:true, country: bulgaria},
                {name: 'Dubrovnik', is_taxi:true, country: croatia},
                {name: 'Osijek', is_taxi:true, country: croatia},
                {name: 'Pula', is_taxi:true, country: croatia},
                {name: 'Rijeka', is_taxi:true, country: croatia},
                {name: 'Split', is_taxi:true, country: croatia},
                {name: 'Zadar', is_taxi:true, country: croatia},
                {name: 'Zagreb', is_taxi:true, country: croatia},
                {name: 'Larnaca', is_taxi:true, country: cyprus},
                {name: 'Limassol', is_taxi:true, country: cyprus},
                {name: 'Paphos', is_taxi:true, country: cyprus},
                {name: 'Prague', is_taxi:true, country: czech},
                {name: 'Alexandria', is_taxi:true, country: egypt},
                {name: 'Aswan', is_taxi:true, country: egypt},
                {name: 'Cairo', is_taxi:true, country: egypt},
                {name: 'Dabaa', is_taxi:true, country: egypt},
                {name: 'Hurghada', is_taxi:true, country: egypt},
                {name: 'Luxor', is_taxi:true, country: egypt},
                {name: 'Marsa Alam', is_taxi:true, country: egypt},
                {name: 'Sharm El Sheikh', is_taxi:true, country: egypt},
                {name: 'Taba', is_taxi:true, country: egypt},
                {name: 'Tallinn', is_taxi:true, country: estonia},
                {name: 'Tartu', is_taxi:true, country: estonia},
                {name: 'Helsinki', is_taxi:true, country: finland},
                {name: 'Annecy', is_taxi:true, country: france},
                {name: 'Biarritz', is_taxi:true, country: france},
                {name: 'Bordeaux', is_taxi:true, country: france},
                {name: 'Cannes', is_taxi:true, country: france},
                {name: 'Chambery', is_taxi:true, country: france},
                {name: 'Grenoble', is_taxi:true, country: france},
                {name: 'Lyon', is_taxi:true, country: france},
                {name: 'Marseille', is_taxi:true, country: france},
                {name: 'Metz', is_taxi:true, country: france},
                {name: 'Montpellier', is_taxi:true, country: france},
                {name: 'Nancy', is_taxi:true, country: france},
                {name: 'Nice', is_taxi:true, country: france},
                {name: 'Paris', is_taxi:true, country: france},
                {name: 'Pau', is_taxi:true, country: france},
                {name: 'Perpignan', is_taxi:true, country: france},
                {name: 'Strasbourg', is_taxi:true, country: france},
                {name: 'Tarbes', is_taxi:true, country: france},
                {name: 'Toulon', is_taxi:true, country: france},
                {name: 'Toulouse', is_taxi:true, country: france},
                {name: 'Berlin', is_taxi:true, country: germany},
                {name: 'Bremen', is_taxi:true, country: germany},
                {name: 'Cologne', is_taxi:true, country: germany},
                {name: 'Dusseldorf', is_taxi:true, country: germany},
                {name: 'Frankfurt', is_taxi:true, country: germany},
                {name: 'Friedrichshafen', is_taxi:true, country: germany},
                {name: 'Hamburg', is_taxi:true, country: germany},
                {name: 'Hannover', is_taxi:true, country: germany},
                {name: 'Leipzig', is_taxi:true, country: germany},
                {name: 'Munich', is_taxi:true, country: germany},
                {name: 'Nuremberg', is_taxi:true, country: germany},
                {name: 'Stuttgart', is_taxi:true, country: germany},
                {name: 'Athens', is_taxi:true, country: greece},
                {name: 'Crete', is_taxi:true, country: greece},
                {name: 'Kos', is_taxi:true, country: greece},
                {name: 'Mykonos', is_taxi:true, country: greece},
                {name: 'Naxos', is_taxi:true, country: greece},
                {name: 'Paros', is_taxi:true, country: greece},
                {name: 'Rhodes', is_taxi:true, country: greece},
                {name: 'Santorini', is_taxi:true, country: greece},
                {name: 'Thessaloniki', is_taxi:true, country: greece},
                {name: 'Zakynthos', is_taxi:true, country: greece},
                {name: 'Budapest', is_taxi:true, country: hungary},
                {name: 'Alghero', is_taxi:true, country: italy},
                {name: 'Ancona', is_taxi:true, country: italy},
                {name: 'Bergamo', is_taxi:true, country: italy},
                {name: 'Bologna', is_taxi:true, country: italy},
                {name: 'Bolzano', is_taxi:true, country: italy},
                {name: 'Brescia', is_taxi:true, country: italy},
                {name: 'Cagliari', is_taxi:true, country: italy},
                {name: 'Catania', is_taxi:true, country: italy},
                {name: 'Florence', is_taxi:true, country: italy},
                {name: 'Forli', is_taxi:true, country: italy},
                {name: 'Genoa', is_taxi:true, country: italy},
                {name: 'Lamezia Terme', is_taxi:true, country: italy},
                {name: 'Milan', is_taxi:true, country: italy},
                {name: 'Naples', is_taxi:true, country: italy},
                {name: 'Olbia', is_taxi:true, country: italy},
                {name: 'Palermo', is_taxi:true, country: italy},
                {name: 'Pescara', is_taxi:true, country: italy},
                {name: 'Pisa', is_taxi:true, country: italy},
                {name: 'Rimini', is_taxi:true, country: italy},
                {name: 'Rome', is_taxi:true, country: italy},
                {name: 'Trapani', is_taxi:true, country: italy},
                {name: 'Treviso', is_taxi:true, country: italy},
                {name: 'Trieste', is_taxi:true, country: italy},
                {name: 'Turin', is_taxi:true, country: italy},
                {name: 'Venice', is_taxi:true, country: italy},
                {name: 'Verona', is_taxi:true, country: italy},
                {name: 'Liepaja', is_taxi:true, country: latvia},
                {name: 'Riga', is_taxi:true, country: latvia},
                {name: 'Kaunas', is_taxi:true, country: lithuania},
                {name: 'Palanga', is_taxi:true, country: lithuania},
                {name: 'Vilnius', is_taxi:true, country: lithuania},
                {name: 'Luxembourg', is_taxi:true, country: luxembourg},
                {name: 'Valletta', is_taxi:true, country: malta},
                {name: 'Amsterdam', is_taxi:true, country: netherlands},
                {name: 'Eindhoven', is_taxi:true, country: netherlands},
                {name: 'Rotterdam', is_taxi:true, country: netherlands},
                {name: 'Oslo', is_taxi:true, country: norway},
                {name: 'Bydgoszcz', is_taxi:true, country: poland},
                {name: 'Gdansk', is_taxi:true, country: poland},
                {name: 'Katowice', is_taxi:true, country: poland},
                {name: 'Krakow', is_taxi:true, country: poland},
                {name: 'Poznan', is_taxi:true, country: poland},
                {name: 'Warsaw', is_taxi:true, country: poland},
                {name: 'Wroclaw', is_taxi:true, country: poland},
                {name: 'Beja', is_taxi:true, country: portugal},
                {name: 'Faro', is_taxi:true, country: portugal},
                {name: 'Funchal', is_taxi:true, country: portugal},
                {name: 'Lisbon', is_taxi:true, country: portugal},
                {name: 'Porto', is_taxi:true, country: portugal},
                {name: 'Bucharest', is_taxi:true, country: romania},
                {name: 'Cluj Napoca', is_taxi:true, country: romania},
                {name: 'Sibiu', is_taxi:true, country: romania},
                {name: 'Timisoara', is_taxi:true, country: romania},
                {name: 'Moscow', is_taxi:true, country: russia},
                {name: 'Saint Petersburg', is_taxi:true, country: russia},
                {name: 'Belgrade', is_taxi:true, country: serbia},
                {name: 'Bratislava', is_taxi:true, country: slovakia},
                {name: 'Bled', is_taxi:true, country: slovenia},
                {name: 'Ljubljana', is_taxi:true, country: slovenia},
                {name: 'Portoroz', is_taxi:true, country: slovenia},
                {name: 'Alicante', is_taxi:true, country: spain},
                {name: 'Almeria', is_taxi:true, country: spain},
                {name: 'Barcelona', is_taxi:true, country: spain},
                {name: 'Bilbao', is_taxi:true, country: spain},
                {name: 'Girona', is_taxi:true, country: spain},
                {name: 'Gran Canaria', is_taxi:true, country: spain},
                {name: 'Madrid', is_taxi:true, country: spain},
                {name: 'Malaga', is_taxi:true, country: spain},
                {name: 'Menorca', is_taxi:true, country: spain},
                {name: 'Murcia', is_taxi:true, country: spain},
                {name: 'San Sebastian', is_taxi:true, country: spain},
                {name: 'Santander', is_taxi:true, country: spain},
                {name: 'Tenerife', is_taxi:true, country: spain},
                {name: 'Valencia', is_taxi:true, country: spain},
                {name: 'Basel', is_taxi:true, country: switzerland},
                {name: 'Bern', is_taxi:true, country: switzerland},
                {name: 'Geneva', is_taxi:true, country: switzerland},
                {name: 'Lugano', is_taxi:true, country: switzerland},
                {name: 'Sion', is_taxi:true, country: switzerland},
                {name: 'Zurich', is_taxi:true, country: switzerland},
                {name: 'Ankara', is_taxi:true, country: turkey},
                {name: 'Antalya', is_taxi:true, country:  turkey},
                {name: 'Bodrum', is_taxi:true, country: turkey},
                {name: 'Dalaman', is_taxi:true, country: turkey},
                {name: 'Istanbul', is_taxi:true, country: turkey},
                {name: 'Izmir', is_taxi:true, country: turkey},
                {name: 'Birmingham', is_taxi:true, country: uk},
                {name: 'Bristol', is_taxi:true, country: uk},
                {name: 'Edinburgh', is_taxi:true, country: uk},
                {name: 'Glasgow', is_taxi:true, country: uk},
                {name: 'London', is_taxi:true, country: uk},
                {name: 'Manchester', is_taxi:true, country: uk}
              ])

end