puts '--------- Begin of Country Seeds File ---------'
Country.create([
                   { name: 'Albania' },
                   { name: 'Andorra' },
                   { name: 'Angola' },
                   { name: 'Anguilla' },
                   { name: 'Antigua' },
                   { name: 'Argentina' },
                   { name: 'Armenia' },
                   { name: 'Aruba' },
                   { name: 'Australia' },
                   { name: 'Austria' },
                   { name: 'Bahamas' },
                   { name: 'Bahrain' },
                   { name: 'Barbados' },
                   { name: 'Belarus' },
                   { name: 'Belgium' },
                   { name: 'Belize' },
                   { name: 'Bolivia' },
                   { name: 'Bonaire' },
                   { name: 'Bosnia' },
                   { name: 'Botswana' },
                   { name: 'Brazil' },
                   { name: 'Brunei' },
                   { name: 'Bulgaria' },
                   { name: 'Cameroon' },
                   { name: 'Canada' },
                   { name: 'Cayman Islands' },
                   { name: 'Chile' },
                   { name: 'Colombia' },
                   { name: 'Costa Rica' },
                   { name: 'Croatia' },
                   { name: 'Curacao' },
                   { name: 'Cyprus' },
                   { name: 'Czech Republic' },
                   { name: 'Denmark' },
                   { name: 'Dominican Republic' },
                   { name: 'Ecuador' },
                   { name: 'Egypt' },
                   { name: 'El Salvador' },
                   { name: 'Estonia' },
                   { name: 'Fiji' },
                   { name: 'Finland' },
                   { name: 'France - Corsica' },
                   { name: 'France' },
                   { name: 'French Guiana' },
                   { name: 'French Polynesia' },
                   { name: 'Georgia' },
                   { name: 'Germany' },
                   { name: 'Ghana' },
                   { name: 'Gibraltar' },
                   { name: 'Greece' },
                   { name: 'Grenada' },
                   { name: 'Guadeloupe' },
                   { name: 'Guam' },
                   { name: 'Guatemala' },
                   { name: 'Guernsey' },
                   { name: 'Haiti' },
                   { name: 'Holland' },
                   { name: 'Honduras Roatan Island' },
                   { name: 'Hong Kong' },
                   { name: 'Hungary' },
                   { name: 'Iceland' },
                   { name: 'India' },
                   { name: 'Indonesia' },
                   { name: 'Iraq' },
                   { name: 'Ireland' },
                   { name: 'Isle Of Man' },
                   { name: 'Israel' },
                   { name: 'Italy' },
                   { name: 'Italy - Sardinia' },
                   { name: 'Italy - Sicily' },
                   { name: 'Jamaica' },
                   { name: 'Japan' },
                   { name: 'Jersey' },
                   { name: 'Jordan' },
                   { name: 'Kazakhstan' },
                   { name: 'Kenya' },
                   { name: 'Korea' },
                   { name: 'Kosovo' },
                   { name: 'Kuwait' },
                   { name: 'Laos' },
                   { name: 'Latvia' },
                   { name: 'Lebanon' },
                   { name: 'Lesotho' },
                   { name: 'Lithuania' },
                   { name: 'Luxembourg' },
                   { name: 'Macedonia' },
                   { name: 'Madagascar' },
                   { name: 'Malaysia' },
                   { name: 'Malta' },
                   { name: 'Martinique' },
                   { name: 'Mauritius' },
                   { name: 'Mayotte' },
                   { name: 'Mexico' },
                   { name: 'Moldova' },
                   { name: 'Montenegro' },
                   { name: 'Morocco' },
                   { name: 'Mozambique' },
                   { name: 'Namibia' },
                   { name: 'New Caledonia' },
                   { name: 'New Zealand' },
                   { name: 'Nicaragua' },
                   { name: 'Northern Cyprus' },
                   { name: 'Northern Ireland' },
                   { name: 'Northern Mariana Islands' },
                   { name: 'Norway' },
                   { name: 'Oman' },
                   { name: 'Pakistan' },
                   { name: 'Panama' },
                   { name: 'Paraguay' },
                   { name: 'Peru' },
                   { name: 'Philippines' },
                   { name: 'Poland' },
                   { name: 'Portugal' },
                   { name: 'Portugal - Azores' },
                   { name: 'Portugal - Madeira' },
                   { name: 'Puerto Rico' },
                   { name: 'Qatar' },
                   { name: 'Reunion Island' },
                   { name: 'Romania' },
                   { name: 'Russia' },
                   { name: 'Saipan' },
                   { name: 'Saudi Arabia' },
                   { name: 'Serbia' },
                   { name: 'Shetland Islands' },
                   { name: 'Singapore' },
                   { name: 'Slovakia' },
                   { name: 'Slovenia' },
                   { name: 'South Africa' },
                   { name: 'South Korea' },
                   { name: 'Spain - Balearic Islands' },
                   { name: 'Spain - Canary Islands' },
                   { name: 'Spain' },
                   { name: 'Sri Lanka' },
                   { name: 'St. Barthelemy' },
                   { name: 'St. Croix' },
                   { name: 'St. Kitts' },
                   { name: 'St. Lucia' },
                   { name: 'St. Maarten' },
                   { name: 'St. Thomas' },
                   { name: 'Suriname' },
                   { name: 'Swaziland' },
                   { name: 'Sweden' },
                   { name: 'Switzerland' },
                   { name: 'Tahiti' },
                   { name: 'Taiwan' },
                   { name: 'Tanzania' },
                   { name: 'Thailand' },
                   { name: 'Tortola' },
                   { name: 'Trinidad' },
                   { name: 'Tunisia' },
                   { name: 'Turkey' },
                   { name: 'Turks and Caicos Islands' },
                   { name: 'U.A.E.' },
                   { name: 'United Kingdom' },
                   { name: 'Ukraine' },
                   { name: 'Uruguay' },
                   { name: 'USA - California' },
                   { name: 'USA - Florida' },
                   { name: 'USA - Las Vegas' },
                   { name: 'USA - New York' },
                   { name: 'USA - Other' },
                   { name: 'Vanuatu' },
                   { name: 'Venezuela' },
                   { name: 'Yemen' },
                   { name: 'Zambia' },
                   { name: 'Zimbabwe' },
                   { name: 'Netherlands'}
               ])
puts '--------- End of Country Seeds File -----------'