puts '--------- Begin of Country Seeds File ---------'
countries = []

countries_new = ['Albania','Andorra','Angola','Anguilla','Antigua','Argentina','Armenia','Aruba','Australia','Austria','Bahamas','Bahrain','Barbados','Belarus','Belgium','Belize','Bolivia','Bonaire','Bosnia','Botswana','Brazil','Brunei','Bulgaria','Cameroon','Canada','Cayman Islands','Chile','China','Colombia','Costa Rica','Croatia','Curacao','Cyprus','Czech Republic','Denmark','Dominican Republic','Ecuador','Egypt','El Salvador','Estonia','Fiji','Finland','France - Corsica','France','French Guiana','French Polynesia','Georgia','Germany','Ghana','Gibraltar','Greece','Grenada','Guadeloupe','Guam','Guatemala','Guernsey','Haiti','Holland','Honduras','Hong Kong','Hungary','Iceland','India','Indonesia','Iraq','Ireland','Isle Of Man','Israel','Italy','Italy - Sardinia','Italy - Sicily','Jamaica','Japan','Jersey','Jordan','Kazakhstan','Kenya','Korea','Kosovo','Kuwait','Laos','Latvia','Lebanon','Lesotho','Lithuania','Luxembourg','Macedonia','Madagascar','Malaysia','Malta','Martinique','Mauritius','Mayotte','Mexico','Moldova','Montenegro','Morocco','Mozambique','Namibia','New Caledonia','New Zealand','Nicaragua','Northern Cyprus','Northern Ireland','Northern Mariana Islands','Norway','Oman','Pakistan','Panama','Paraguay','Peru','Philippines','Poland','Portugal','Portugal - Azores','Portugal - Madeira','Puerto Rico','Qatar','Reunion Island','Romania','Russia','Saipan','Saudi Arabia','Serbia','Shetland Islands','Singapore','Slovakia','Slovenia','South Africa','South Korea','Spain - Balearic Islands','Spain - Canary Islands','Spain','Sri Lanka','St. Barthelemy','St. Croix','St. Kitts','St. Lucia','St. Maarten','St. Thomas','Suriname','Swaziland','Sweden','Switzerland','Tahiti','Taiwan','Tanzania','Thailand','Tortola','Trinidad','Tunisia','Turkey','Turks and Caicos Islands','U.A.E.','United Kingdom','Ukraine','Uruguay','USA - California','USA - Florida','USA - Las Vegas','USA - New York','USA - Other','Vanuatu','Venezuela','Yemen','Zambia','Zimbabwe']

countries_new.each do |country|
  countries << Country.new(name: country)
end

Country.import countries
puts '--------- End of Country Seeds File -----------'