after :cities do

  puts 'Cities of Austria'
  innsbruck = City.find_by(name: 'Innsbruck')
  klagenfurt = City.find_by(name: 'Klagenfurt')
  salzburg = City.find_by(name: 'Salzburg')
  vienna = City.find_by(name: 'Vienna')
  PickUpLocation.create([
        {name:'Innsbruck Airport',city:innsbruck},
        {name:'Innsbruck Train Station',city:innsbruck},
        {name:'Kitzbuhel',city:innsbruck},
        {name:'Mayrhofen',city:innsbruck},
        {name:'Ischgl',city:innsbruck},
        {name:'Fugen',city:innsbruck},
        {name:'Lech',city:innsbruck},
        {name:'Absam',city:innsbruck},
        {name:'Achenkirch',city:innsbruck},
        {name:'Affenhausen',city:innsbruck},
        {name:'Alberschwende',city:innsbruck},
        {name:'Alpbach',city:innsbruck},
        {name:'Andelsbuch',city:innsbruck},
        {name:'Arzl im Pitztal',city:innsbruck},
        {name:'Aschau im Zillertal',city:innsbruck},
        {name:'Au',city:innsbruck},
        {name:'Auffach',city:innsbruck},
        {name:'Aurach bei Kitzbuhel',city:innsbruck},
        {name:'Axamer Lizum',city:innsbruck},
        {name:'Axams',city:innsbruck},
        {name:'Bad Haring',city:innsbruck},
        {name:'Berwang',city:innsbruck},
        {name:'Biberwier',city:innsbruck},
        {name:'Bichlbach',city:innsbruck},
        {name:'Birgitz',city:innsbruck},
        {name:'Bizau',city:innsbruck},
        {name:'Bludenz',city:innsbruck},
        {name:'Brand',city:innsbruck},
        {name:'Brandenberg',city:innsbruck},
        {name:'Bregenz',city:innsbruck},
        {name:'Brennerpass',city:innsbruck},
        {name:'Brixen im Thale',city:innsbruck},
        {name:'Brixlegg',city:innsbruck},
        {name:'Bruck am Ziller',city:innsbruck},
        {name:'Burserberg',city:innsbruck},
        {name:'Dalaas',city:innsbruck},
        {name:'Damuels',city:innsbruck},
        {name:'Dirschenbach',city:innsbruck},
        {name:'Dornbirn',city:innsbruck},
        {name:'Ebbs',city:innsbruck},
        {name:'Eben am Achensee',city:innsbruck},
        {name:'Ehrwald',city:innsbruck},
        {name:'Eigenhofen',city:innsbruck},
        {name:'Elblingenalp',city:innsbruck},
        {name:'Ellmau',city:innsbruck},
        {name:'Elmen',city:innsbruck},
        {name:'Erl',city:innsbruck},
        {name:'Erpfendorf',city:innsbruck},
        {name:'Faschina',city:innsbruck},
        {name:'Feldkirch',city:innsbruck},
        {name:'Fernpass',city:innsbruck},
        {name:'Fieberbrunn',city:innsbruck},
        {name:'Fiecht',city:innsbruck},
        {name:'Finkenberg',city:innsbruck},
        {name:'Fiss',city:innsbruck},
        {name:'Flaurling',city:innsbruck},
        {name:'Fliess',city:innsbruck},
        {name:'Flirsch',city:innsbruck},
        {name:'Fontanella',city:innsbruck},
        {name:'Frohnhausen',city:innsbruck},
        {name:'Fugen',city:innsbruck},
        {name:'Fulpmes',city:innsbruck},
        {name:'Galtuer',city:innsbruck},
        {name:'Galtur',city:innsbruck},
        {name:'Gargellen',city:innsbruck},
        {name:'Gerlos',city:innsbruck},
        {name:'Gnadenwald',city:innsbruck},
        {name:'Going am Wilden Kaiser',city:innsbruck},
        {name:'Gotzens',city:innsbruck},
        {name:'Gotzis',city:innsbruck},
        {name:'Gries Sellrain',city:innsbruck},
        {name:'Gries am Brenner',city:innsbruck},
        {name:'Grinzens',city:innsbruck},
        {name:'Gschnitz',city:innsbruck},
        {name:'Haiming',city:innsbruck},
        {name:'Hall in Tirol',city:innsbruck},
        {name:'Hatting',city:innsbruck},
        {name:'Heiligenblut',city:innsbruck},
        {name:'Heiterwang',city:innsbruck},
        {name:'Hintertux',city:innsbruck},
        {name:'Hippach',city:innsbruck},
        {name:'Hochfilzen',city:innsbruck},
        {name:'Hochfugen',city:innsbruck},
        {name:'Hochgurgl',city:innsbruck},
        {name:'Hochpillberg',city:innsbruck},
        {name:'Hochzirl',city:innsbruck},
        {name:'Hofen',city:innsbruck},
        {name:'Hohenems',city:innsbruck},
        {name:'Hopfgarten im Brixental',city:innsbruck},
        {name:'Huben',city:innsbruck},
        {name:'Igls',city:innsbruck},
        {name:'Imst',city:innsbruck},
        {name:'Innsbruck City Centre',city:innsbruck},
        {name:'Inzing',city:innsbruck},
        {name:'Ischgl',city:innsbruck},
        {name:'Itter',city:innsbruck},
        {name:'Jenbach',city:innsbruck},
        {name:'Judenstein',city:innsbruck},
        {name:'Jungholz',city:innsbruck},
        {name:'Kaltenbach',city:innsbruck},
        {name:'Kampl',city:innsbruck},
        {name:'Kappl',city:innsbruck},
        {name:'Karres',city:innsbruck},
        {name:'Kaunertal',city:innsbruck},
        {name:'Kauns',city:innsbruck},
        {name:'Kelchsau',city:innsbruck},
        {name:'Kematen',city:innsbruck},
        {name:'Kirchberg in Tirol',city:innsbruck},
        {name:'Kirchbichl',city:innsbruck},
        {name:'Kitzbuhel',city:innsbruck},
        {name:'Kleinwalsertal',city:innsbruck},
        {name:'Klosterle',city:innsbruck},
        {name:'Koessen',city:innsbruck},
        {name:'Kolsass',city:innsbruck},
        {name:'Konigsleiten',city:innsbruck},
        {name:'Kossen',city:innsbruck},
        {name:'Kramsach',city:innsbruck},
        {name:'Krimml',city:innsbruck},
        {name:'Krossbach',city:innsbruck},
        {name:'Kufstein',city:innsbruck},
        {name:'Kuhtai',city:innsbruck},
        {name:'Kundl',city:innsbruck},
        {name:'Ladis',city:innsbruck},
        {name:'Landeck',city:innsbruck},
        {name:'Lanersbach',city:innsbruck},
        {name:'Langen am Arlberg',city:innsbruck},
        {name:'Langenfeld',city:innsbruck},
        {name:'Lans',city:innsbruck},
        {name:'Laterns',city:innsbruck},
        {name:'Lech',city:innsbruck},
        {name:'Lech am Arlberg',city:innsbruck},
        {name:'Leiblfing',city:innsbruck},
        {name:'Leithen',city:innsbruck},
        {name:'Lermoos',city:innsbruck},
        {name:'Leutasch',city:innsbruck},
        {name:'Lienz',city:innsbruck},
        {name:'Lofer',city:innsbruck},
        {name:'Lusens',city:innsbruck},
        {name:'Lustenau',city:innsbruck},
        {name:'Mathon',city:innsbruck},
        {name:'Matrei am Brenner',city:innsbruck},
        {name:'Matrei in Osttirol',city:innsbruck},
        {name:'Maurach',city:innsbruck},
        {name:'Mayrhofen',city:innsbruck},
        {name:'Mellau',city:innsbruck},
        {name:'Mieders',city:innsbruck},
        {name:'Milders',city:innsbruck},
        {name:'Mils bei Imst',city:innsbruck},
        {name:'Mittelberg',city:innsbruck},
        {name:'Mittersill',city:innsbruck},
        {name:'Motz',city:innsbruck},
        {name:'Munster Tirol',city:innsbruck},
        {name:'Mutters',city:innsbruck},
        {name:'Nassereth',city:innsbruck},
        {name:'Natters',city:innsbruck},
        {name:'Nauders',city:innsbruck},
        {name:'Navis',city:innsbruck},
        {name:'Neder',city:innsbruck},
        {name:'Neu Gotzens',city:innsbruck},
        {name:'Neukirchen am Grossvenediger',city:innsbruck},
        {name:'Neustift im Stubaital',city:innsbruck},
        {name:'Niederau',city:innsbruck},
        {name:'Oberau Wildschonau',city:innsbruck},
        {name:'Obergurgl',city:innsbruck},
        {name:'Oberhofen',city:innsbruck},
        {name:'Oberlech',city:innsbruck},
        {name:'Obermieming',city:innsbruck},
        {name:'Obernberg am Brenner',city:innsbruck},
        {name:'Oberperfuss',city:innsbruck},
        {name:'Obladis',city:innsbruck},
        {name:'Obsteig',city:innsbruck},
        {name:'Oetz',city:innsbruck},
        {name:'Omes',city:innsbruck},
        {name:'Partenen',city:innsbruck},
        {name:'Patsch',city:innsbruck},
        {name:'Pertisau',city:innsbruck},
        {name:'Pettnau',city:innsbruck},
        {name:'Pettnau am Arlberg',city:innsbruck},
        {name:'Pfaffenhofen',city:innsbruck},
        {name:'Pfons',city:innsbruck},
        {name:'Pfunds',city:innsbruck},
        {name:'Pians',city:innsbruck},
        {name:'Pill',city:innsbruck},
        {name:'Pitztal',city:innsbruck},
        {name:'Plagne Montalbert',city:innsbruck},
        {name:'Polling',city:innsbruck},
        {name:'Prutz',city:innsbruck},
        {name:'Radfeld',city:innsbruck},
        {name:'Raggal',city:innsbruck},
        {name:'Ramsau im Zillertal',city:innsbruck},
        {name:'Ranggen',city:innsbruck},
        {name:'Rankweil',city:innsbruck},
        {name:'Rans',city:innsbruck},
        {name:'Rattenberg',city:innsbruck},
        {name:'Reith bei Seefeld',city:innsbruck},
        {name:'Reith im Alpbachtal',city:innsbruck},
        {name:'Reutte',city:innsbruck},
        {name:'Ried im Zillertal',city:innsbruck},
        {name:'Rietz',city:innsbruck},
        {name:'Rinn',city:innsbruck},
        {name:'Rotholz',city:innsbruck},
        {name:'Rum',city:innsbruck},
        {name:'Sankt Leonhard im Pitztal',city:innsbruck},
        {name:'Sauttens',city:innsbruck},
        {name:'Scharnitz',city:innsbruck},
        {name:'Schattwald',city:innsbruck},
        {name:'Schlitters',city:innsbruck},
        {name:'Schmirn',city:innsbruck},
        {name:'Schoenberg',city:innsbruck},
        {name:'Schonwies',city:innsbruck},
        {name:'Schrocken',city:innsbruck},
        {name:'Schruns',city:innsbruck},
        {name:'Schwarzenberg',city:innsbruck},
        {name:'Schwaz',city:innsbruck},
        {name:'See im Paznauntal',city:innsbruck},
        {name:'Seefeld in Tirol',city:innsbruck},
        {name:'Sellrain',city:innsbruck},
        {name:'Serfaus',city:innsbruck},
        {name:'Silbertal',city:innsbruck},
        {name:'Sillian',city:innsbruck},
        {name:'Silz',city:innsbruck},
        {name:'Sistrans',city:innsbruck},
        {name:'Solden',city:innsbruck},
        {name:'Soll',city:innsbruck},
        {name:'St Agatha',city:innsbruck},
        {name:'St Anton am Arlberg',city:innsbruck},
        {name:'St Christoph am Arlberg',city:innsbruck},
        {name:'St Gallenkirch',city:innsbruck},
        {name:'St Jakob am Arlberg',city:innsbruck},
        {name:'St Johann in Tirol',city:innsbruck},
        {name:'St Peter in Tirol',city:innsbruck},
        {name:'St Sigmund im Sellrain',city:innsbruck},
        {name:'Stams',city:innsbruck},
        {name:'Stans',city:innsbruck},
        {name:'Stanzach',city:innsbruck},
        {name:'Steeg',city:innsbruck},
        {name:'Steinach am Brenner',city:innsbruck},
        {name:'Strass im Zillertal',city:innsbruck},
        {name:'Strengen am Arlberg',city:innsbruck},
        {name:'Stubaier Gletscher',city:innsbruck},
        {name:'Stuben am Arlberg',city:innsbruck},
        {name:'Stumm',city:innsbruck},
        {name:'Tannheim',city:innsbruck},
        {name:'Tarrenz',city:innsbruck},
        {name:'Telfes',city:innsbruck},
        {name:'Telfs',city:innsbruck},
        {name:'Terfens',city:innsbruck},
        {name:'Thaur',city:innsbruck},
        {name:'Thiersee',city:innsbruck},
        {name:'Trin',city:innsbruck},
        {name:'Tschagguns',city:innsbruck},
        {name:'Tulfes',city:innsbruck},
        {name:'Tumpen',city:innsbruck},
        {name:'Tux',city:innsbruck},
        {name:'Uderns',city:innsbruck},
        {name:'Umhausen',city:innsbruck},
        {name:'Untermieming',city:innsbruck},
        {name:'Vandans',city:innsbruck},
        {name:'Vomperberg',city:innsbruck},
        {name:'Waidring',city:innsbruck},
        {name:'Walchsee',city:innsbruck},
        {name:'Wald im Pinzgau',city:innsbruck},
        {name:'Warth',city:innsbruck},
        {name:'Wattens',city:innsbruck},
        {name:'Weer',city:innsbruck},
        {name:'Weissenmbach Lech',city:innsbruck},
        {name:'Wenns',city:innsbruck},
        {name:'Westendorf',city:innsbruck},
        {name:'Wiesing',city:innsbruck},
        {name:'Wildschonau Oberau',city:innsbruck},
        {name:'Worgl',city:innsbruck},
        {name:'Zams',city:innsbruck},
        {name:'Zell am Ziller',city:innsbruck},
        {name:'Zillertal',city:innsbruck},
        {name:'Zirl',city:innsbruck},
        {name:'Zurs',city:innsbruck},
        {name:'Zwieselstein',city:innsbruck},
        {name:'Klagenfurt Airport', city: klagenfurt},
        {name:'Altenmarkt im Pongau', city: klagenfurt},
        {name:'Katschberg', city: klagenfurt},
        {name:'Bad Kleinkirchheim', city: klagenfurt},
        {name:'Kotschach Mauthen', city: klagenfurt},
        {name:'Maria Worth', city: klagenfurt},
        {name:'Zauchensee', city: klagenfurt},
        {name:'Altenmarkt im Pongau', city: klagenfurt},
        {name:'Annenheim', city: klagenfurt},
        {name:'Arnoldstein', city: klagenfurt},
        {name:'Bad Bleiberg', city: klagenfurt},
        {name:'Bad Kleinkirchheim', city: klagenfurt},
        {name:'Bad St Leonhard im Lavanttal', city: klagenfurt},
        {name:'Bleiburg', city: klagenfurt},
        {name:'Bodensdorf', city: klagenfurt},
        {name:'Dobriach', city: klagenfurt},
        {name:'Drobollach', city: klagenfurt},
        {name:'Ebene Reichenau', city: klagenfurt},
        {name:'Egg am Faaker See', city: klagenfurt},
        {name:'Eisentratten', city: klagenfurt},
        {name:'Faak am See', city: klagenfurt},
        {name:'Falkert', city: klagenfurt},
        {name:'Feistritz ob Bleiburg', city: klagenfurt},
        {name:'Feld am See', city: klagenfurt},
        {name:'Feldkirchen in Karnten', city: klagenfurt},
        {name:'Ferndorf', city: klagenfurt},
        {name:'Finkenstein am Faaker See', city: klagenfurt},
        {name:'Flattach', city: klagenfurt},
        {name:'Frantschach', city: klagenfurt},
        {name:'Fresach', city: klagenfurt},
        {name:'Gerlitzen', city: klagenfurt},
        {name:'Godersdorf', city: klagenfurt},
        {name:'Goldeck', city: klagenfurt},
        {name:'Heiligengeist', city: klagenfurt},
        {name:'Hermagor', city: klagenfurt},
        {name:'Innerkrems', city: klagenfurt},
        {name:'Jenig', city: klagenfurt},
        {name:'Katschberg', city: klagenfurt},
        {name:'Kirchbach', city: klagenfurt},
        {name:'Klagenfurt City Centre', city: klagenfurt},
        {name:'Klippitztorl', city: klagenfurt},
        {name:'Kotschach Mauthen', city: klagenfurt},
        {name:'Krumpendorf', city: klagenfurt},
        {name:'Landskron', city: klagenfurt},
        {name:'Latschach', city: klagenfurt},
        {name:'Ledenitzen', city: klagenfurt},
        {name:'Lendorf', city: klagenfurt},
        {name:'Lieserbrucke', city: klagenfurt},
        {name:'Malta', city: klagenfurt},
        {name:'Maria Worth', city: klagenfurt},
        {name:'Mariahof', city: klagenfurt},
        {name:'Millstatt', city: klagenfurt},
        {name:'Nassfeld', city: klagenfurt},
        {name:'Notsch im Gailtal', city: klagenfurt},
        {name:'Obermillstatt', city: klagenfurt},
        {name:'Obervellach', city: klagenfurt},
        {name:'Ossiach', city: klagenfurt},
        {name:'Patergassen', city: klagenfurt},
        {name:'Portschach am Worthersee', city: klagenfurt},
        {name:'Pressegger See', city: klagenfurt},
        {name:'Radenthein', city: klagenfurt},
        {name:'Ramingstein', city: klagenfurt},
        {name:'Rattendorf', city: klagenfurt},
        {name:'Reifnitz', city: klagenfurt},
        {name:'Rennweg am Katschberg', city: klagenfurt},
        {name:'Sattendorf', city: klagenfurt},
        {name:'Schiefling am See', city: klagenfurt},
        {name:'Seeboden', city: klagenfurt},
        {name:'Spittal an der Drau', city: klagenfurt},
        {name:'St  Michael im Lungau', city: klagenfurt},
        {name:'St Kanzian am Klopeiner See', city: klagenfurt},
        {name:'St Margarethen im Lungau', city: klagenfurt},
        {name:'St Oswald', city: klagenfurt},
        {name:'St Veit', city: klagenfurt},
        {name:'Steindorf am Ossiacher See', city: klagenfurt},
        {name:'Tamsweg', city: klagenfurt},
        {name:'Trebesing', city: klagenfurt},
        {name:'Tropolach', city: klagenfurt},
        {name:'Turracher Hohe', city: klagenfurt},
        {name:'Unzmarkt Frauenburg', city: klagenfurt},
        {name:'Velden am Worther See', city: klagenfurt},
        {name:'Verditz', city: klagenfurt},
        {name:'Villach', city: klagenfurt},
        {name:'Waidegg', city: klagenfurt},
        {name:'Watschig', city: klagenfurt},
        {name:'Zauchensee', city: klagenfurt},
         {name:'Salzburg Airport', city: salzburg},
         {name:'Salzburg Train Station', city: salzburg},
         {name:'Saalbach', city: salzburg},
         {name:'Hinterglemm', city: salzburg},
         {name:'Wagrain', city: salzburg},
         {name:'Flachau', city: salzburg},
         {name:'Bad Gastein', city: salzburg},
         {name:'Zell am See', city: salzburg},
         {name:'Abtenau', city: salzburg},
         {name:'Achensee', city: salzburg},
         {name:'Afritz am See', city: salzburg},
         {name:'Aigen Schlaegl', city: salzburg},
         {name:'Alpendorf', city: salzburg},
         {name:'Altmunster', city: salzburg},
         {name:'Andorf ', city: salzburg},
         {name:'Annaberg im Lammatal', city: salzburg},
         {name:'Ansfelden', city: salzburg},
         {name:'Aschbach Markt', city: salzburg},
         {name:'Aspach', city: salzburg},
         {name:'Asten', city: salzburg},
         {name:'Attersee', city: salzburg},
         {name:'Bachmanning', city: salzburg},
         {name:'Bad Aussee', city: salzburg},
         {name:'Bad Gastein', city: salzburg},
         {name:'Bad Goisern', city: salzburg},
         {name:'Bad Hall', city: salzburg},
         {name:'Bad Hofgastein', city: salzburg},
         {name:'Bad Ischl', city: salzburg},
         {name:'Bad Kreuzen', city: salzburg},
         {name:'Bad Leonfelden', city: salzburg},
         {name:'Bad Mitterndorf', city: salzburg},
         {name:'Bad Schallerbach', city: salzburg},
         {name:'Bad Vigaun', city: salzburg},
         {name:'Baumkirchen', city: salzburg},
         {name:'Bischofshofen', city: salzburg},
         {name:'Blindenmarkt', city: salzburg},
         {name:'Bramberg', city: salzburg},
         {name:'Brand Nagelberg', city: salzburg},
         {name:'Braunau', city: salzburg},
         {name:'Breitenschuetzing', city: salzburg},
         {name:'Bruck an der Grossglocknerstrasse', city: salzburg},
         {name:'Buermoos', city: salzburg},
         {name:'Burghausen', city: salzburg},
         {name:'Dellach', city: salzburg},
         {name:'Deutschlandsberg', city: salzburg},
         {name:'Dienten', city: salzburg},
         {name:'Dolsach', city: salzburg},
         {name:'Donawitz', city: salzburg},
         {name:'Donnersbachwald', city: salzburg},
         {name:'Dorfbeuern', city: salzburg},
         {name:'Dorfgastein', city: salzburg},
         {name:'Ebelsberg', city: salzburg},
         {name:'Eben im Pongau', city: salzburg},
         {name:'Ebenau', city: salzburg},
         {name:'Ebensee', city: salzburg},
         {name:'Eberschwang', city: salzburg},
         {name:'Eferding', city: salzburg},
         {name:'Eggelsberg', city: salzburg},
         {name:'Eisenerz', city: salzburg},
         {name:'Engelhartszell', city: salzburg},
         {name:'Enns', city: salzburg},
         {name:'Eugendorf', city: salzburg},
         {name:'Faistenau', city: salzburg},
         {name:'Felbertauern', city: salzburg},
         {name:'Feldbach', city: salzburg},
         {name:'Ferleiten', city: salzburg},
         {name:'Filzmoos', city: salzburg},
         {name:'Flachau', city: salzburg},
         {name:'Fohnsdorf', city: salzburg},
         {name:'Forstau', city: salzburg},
         {name:'Frankenburg', city: salzburg},
         {name:'Frankenmarkt', city: salzburg},
         {name:'Friedburg', city: salzburg},
         {name:'Fuerstenfeld', city: salzburg},
         {name:'Fusch an der Grossglocknerstrasse', city: salzburg},
         {name:'Fuschl', city: salzburg},
         {name:'Gaishorn', city: salzburg},
         {name:'Gallneukirchen', city: salzburg},
         {name:'Gallspach', city: salzburg},
         {name:'Geretsberg', city: salzburg},
         {name:'Gerlos Pass', city: salzburg},
         {name:'Gmuend', city: salzburg},
         {name:'Gmunden', city: salzburg},
         {name:'Goestling', city: salzburg},
         {name:'Going', city: salzburg},
         {name:'Goldegg', city: salzburg},
         {name:'Golling', city: salzburg},
         {name:'Gosau', city: salzburg},
         {name:'Gossl', city: salzburg},
         {name:'Gostling', city: salzburg},
         {name:'Graukogel', city: salzburg},
         {name:'Greifenburg', city: salzburg},
         {name:'Grein', city: salzburg},
         {name:'Grieskirchen', city: salzburg},
         {name:'Grobming', city: salzburg},
         {name:'Grodig', city: salzburg},
         {name:'Grossarl', city: salzburg},
         {name:'Grossgmain', city: salzburg},
         {name:'Grossraming', city: salzburg},
         {name:'Grossreifling', city: salzburg},
         {name:'Grunau im Almtal', city: salzburg},
         {name:'Grundlsee', city: salzburg},
         {name:'Gundertshausen', city: salzburg},
         {name:'Gunskirchen', city: salzburg},
         {name:'Haag am Hausruck', city: salzburg},
         {name:'Hagen Lofer', city: salzburg},
         {name:'Hallein', city: salzburg},
         {name:'Hallstatt', city: salzburg},
         {name:'Haus im Ennstal', city: salzburg},
         {name:'Hinterglemm', city: salzburg},
         {name:'Hinterstoder', city: salzburg},
         {name:'Hof bei Salzburg ', city: salzburg},
         {name:'Hohentauren', city: salzburg},
         {name:'Holzoster', city: salzburg},
         {name:'Huettschlag', city: salzburg},
         {name:'Irdning', city: salzburg},
         {name:'Jochberg', city: salzburg},
         {name:'Kals am Grossglockner', city: salzburg},
         {name:'Kaprun', city: salzburg},
         {name:'Kirchdorf an der Krems', city: salzburg},
         {name:'Kirchdorf in Tirol', city: salzburg},
         {name:'Kitzbuehel', city: salzburg},
         {name:'Klagenfurt', city: salzburg},
         {name:'Kleinarl', city: salzburg},
         {name:'Knittelfeld', city: salzburg},
         {name:'Koenigswiesen', city: salzburg},
         {name:'Koppl', city: salzburg},
         {name:'Kostendorf', city: salzburg},
         {name:'Kuchl', city: salzburg},
         {name:'Laakirchen', city: salzburg},
         {name:'Lambach', city: salzburg},
         {name:'Lammertal', city: salzburg},
         {name:'Lamprechtshausen', city: salzburg},
         {name:'Lenzing', city: salzburg},
         {name:'Leoben', city: salzburg},
         {name:'Leogang', city: salzburg},
         {name:'Lessach', city: salzburg},
         {name:'Liezen', city: salzburg},
         {name:'Linz ', city: salzburg},
         {name:'Lohnsburg', city: salzburg},
         {name:'Maishofen', city: salzburg},
         {name:'Mallnitz', city: salzburg},
         {name:'Mandling', city: salzburg},
         {name:'Manning', city: salzburg},
         {name:'Marchtrenk', city: salzburg},
         {name:'Maria Alm', city: salzburg},
         {name:'Mariapfarr', city: salzburg},
         {name:'Mattighofen', city: salzburg},
         {name:'Mattsee', city: salzburg},
         {name:'Mauerkirchen', city: salzburg},
         {name:'Mauterndorf', city: salzburg},
         {name:'Mauthausen', city: salzburg},
         {name:'Mettmach', city: salzburg},
         {name:'Michaelbeuern', city: salzburg},
         {name:'Micheldorf', city: salzburg},
         {name:'Mondsee', city: salzburg},
         {name:'Moosdorf', city: salzburg},
         {name:'Muenzkirchen', city: salzburg},
         {name:'Muhlbach am Hochkonig', city: salzburg},
         {name:'Munderfing', city: salzburg},
         {name:'Murau', city: salzburg},
         {name:'Neumarkt am Wallersee', city: salzburg},
         {name:'Niederalm', city: salzburg},
         {name:'Niederndorf', city: salzburg},
         {name:'Niedernsill', city: salzburg},
         {name:'Nussdorf am Attersee', city: salzburg},
         {name:'Nussdorf am Haunsberg', city: salzburg},
         {name:'Obernberg am Inn', city: salzburg},
         {name:'Oberndorf bei Salzburg', city: salzburg},
         {name:'Oberndorf in Tirol', city: salzburg},
         {name:'Obertauern', city: salzburg},
         {name:'Obertilliach', city: salzburg},
         {name:'Obertraun', city: salzburg},
         {name:'Obertrum', city: salzburg},
         {name:'Offenhausen', city: salzburg},
         {name:'Ostermiething', city: salzburg},
         {name:'Ottensheim', city: salzburg},
         {name:'Perg', city: salzburg},
         {name:'Pertisau am Achensee', city: salzburg},
         {name:'Pettneu am Arlberg', city: salzburg},
         {name:'Peuerbach', city: salzburg},
         {name:'Pfarrkirchen', city: salzburg},
         {name:'Piesendorf', city: salzburg},
         {name:'Pinzgau', city: salzburg},
         {name:'Postalm', city: salzburg},
         {name:'Pramet', city: salzburg},
         {name:'Pregarten', city: salzburg},
         {name:'Prien am Chiemsee', city: salzburg},
         {name:'Pruggern', city: salzburg},
         {name:'Puch bei Hallein', city: salzburg},
         {name:'Radstadt', city: salzburg},
         {name:'Ramsau am Dachstein', city: salzburg},
         {name:'Rauris', city: salzburg},
         {name:'Reith', city: salzburg},
         {name:'Rennweg', city: salzburg},
         {name:'Ried im Innkreis', city: salzburg},
         {name:'Riedau', city: salzburg},
         {name:'Rohrbach in Oberosterreich', city: salzburg},
         {name:'Rohrmoos', city: salzburg},
         {name:'Rossbach', city: salzburg},
         {name:'Russbach', city: salzburg},
         {name:'Saalbach', city: salzburg},
         {name:'Saalfelden', city: salzburg},
         {name:'Salzburg City Centre', city: salzburg},
         {name:'Schaerding', city: salzburg},
         {name:'Scheffau am Wilden Kaiser', city: salzburg},
         {name:'Scheibbs', city: salzburg},
         {name:'Schladming', city: salzburg},
         {name:'Schlagl', city: salzburg},
         {name:'Schmieden', city: salzburg},
         {name:'Schneegattern', city: salzburg},
         {name:'Schorfling', city: salzburg},
         {name:'Schwanenstadt', city: salzburg},
         {name:'Schwertberg', city: salzburg},
         {name:'Seefeld', city: salzburg},
         {name:'Seeham', city: salzburg},
         {name:'Seekirchen', city: salzburg},
         {name:'Seewalchen', city: salzburg},
         {name:'Sierning', city: salzburg},
         {name:'Spital am Pyhrn', city: salzburg},
         {name:'Sportgastein', city: salzburg},
         {name:'St Aegydi', city: salzburg},
         {name:'St Gilgen ', city: salzburg},
         {name:'St Johann im Pongau', city: salzburg},
         {name:'St Lorenz', city: salzburg},
         {name:'St Martin bei Lofer', city: salzburg},
         {name:'St Martin im Innkreis', city: salzburg},
         {name:'St Michael im Lungau', city: salzburg},
         {name:'St Ulrich am Pillersee', city: salzburg},
         {name:'St Wolfgang', city: salzburg},
         {name:'Steinbach am Attersee', city: salzburg},
         {name:'Steyr', city: salzburg},
         {name:'Steyregg', city: salzburg},
         {name:'Strasswalchen', city: salzburg},
         {name:'Strobl', city: salzburg},
         {name:'Suben', city: salzburg},
         {name:'Sulzau', city: salzburg},
         {name:'Taiskirchen', city: salzburg},
         {name:'Tamsweg', city: salzburg},
         {name:'Tarsdorf', city: salzburg},
         {name:'Tauplitz', city: salzburg},
         {name:'Taxenbach', city: salzburg},
         {name:'Ternberg', city: salzburg},
         {name:'Thalgau', city: salzburg},
         {name:'Timmelkam', city: salzburg},
         {name:'Traun', city: salzburg},
         {name:'Traunkirchen', city: salzburg},
         {name:'Trimmelkam', city: salzburg},
         {name:'Turracherhohe', city: salzburg},
         {name:'Ulrichsberg', city: salzburg},
         {name:'Unken', city: salzburg},
         {name:'Unterach am Attersee', city: salzburg},
         {name:'Untertauern', city: salzburg},
         {name:'Uttendorf', city: salzburg},
         {name:'Viehhofen', city: salzburg},
         {name:'Vocklabruck', city: salzburg},
         {name:'Vocklamarkt', city: salzburg},
         {name:'Voitsberg', city: salzburg},
         {name:'Volkermarkt', city: salzburg},
         {name:'Vorchdorf', city: salzburg},
         {name:'Wagrain', city: salzburg},
         {name:'Waidhofen an der Thaya', city: salzburg},
         {name:'Waizenkirchen', city: salzburg},
         {name:'Waldzell', city: salzburg},
         {name:'Weissbach bei Lofer', city: salzburg},
         {name:'Wels', city: salzburg},
         {name:'Werfen', city: salzburg},
         {name:'Werfenweng', city: salzburg},
         {name:'Windischgarsten', city: salzburg},
         {name:'Wolfsberg', city: salzburg},
         {name:'Worschach', city: salzburg},
         {name:'Zell am Moos', city: salzburg},
         {name:'Zell am See', city: salzburg},
         {name:'Zell an der Pram', city: salzburg},
         {name:'Zinkenbach', city: salzburg},
          {name:'Vienna Airport', city: vienna},
          {name:'Vienna Train Station', city: vienna},
          {name:'Vienna City Centre', city: vienna},
          {name:'Wiener Neustadt', city: vienna},
          {name:'Hopfgarten', city: vienna},
          {name:'Kohfidisch', city: vienna},
          {name:'Neustift', city: vienna},
          {name:'Krems', city: vienna},
          {name:'Aderklaa', city: vienna},
          {name:'Aflenz Kurort', city: vienna},
          {name:'Amstetten', city: vienna},
          {name:'Annaberg', city: vienna},
          {name:'Bad Radkersburg', city: vienna},
          {name:'Baden', city: vienna},
          {name:'Berndorf', city: vienna},
          {name:'Bisamberg', city: vienna},
          {name:'Breitenfurt', city: vienna},
          {name:'Bruck an der Leitha', city: vienna},
          {name:'Bruck an der Mur', city: vienna},
          {name:'Brunn am Gebirge', city: vienna},
          {name:'Deutsch Wagram', city: vienna},
          {name:'Eisenstadt', city: vienna},
          {name:'Freistadt', city: vienna},
          {name:'Furstenfeld', city: vienna},
          {name:'Gablitz', city: vienna},
          {name:'Gaenserndorf', city: vienna},
          {name:'Gerasdorf', city: vienna},
          {name:'Gmund', city: vienna},
          {name:'Goriach', city: vienna},
          {name:'Graz', city: vienna},
          {name:'Gross Enzersdorf', city: vienna},
          {name:'Guessing', city: vienna},
          {name:'Guntramsdorf', city: vienna},
          {name:'Gussing', city: vienna},
          {name:'Hagenbrunn', city: vienna},
          {name:'Hainburg', city: vienna},
          {name:'Hainburg an der Donau', city: vienna},
          {name:'Himberg', city: vienna},
          {name:'Hinterbruhl', city: vienna},
          {name:'Hollabrunn', city: vienna},
          {name:'Hopfgarten', city: vienna},
          {name:'Jennersdorf', city: vienna},
          {name:'Kirchberg am Wechsel', city: vienna},
          {name:'Klosterneuburg', city: vienna},
          {name:'Kohfidisch', city: vienna},
          {name:'Korneuburg', city: vienna},
          {name:'Krems', city: vienna},
          {name:'Lackenhof', city: vienna},
          {name:'Langenzersdorf', city: vienna},
          {name:'Leopoldsdorf', city: vienna},
          {name:'Liesing', city: vienna},
          {name:'Lilienfeld', city: vienna},
          {name:'Mattersburg', city: vienna},
          {name:'Mauerbach', city: vienna},
          {name:'Melk', city: vienna},
          {name:'Mistelbach', city: vienna},
          {name:'Modling', city: vienna},
          {name:'Muerzzuschlag', city: vienna},
          {name:'Munchendorf', city: vienna},
          {name:'Neusiedl am See', city: vienna},
          {name:'Neustift', city: vienna},
          {name:'Oberpullendorf', city: vienna},
          {name:'Oberwart', city: vienna},
          {name:'Parndorf', city: vienna},
          {name:'Perchtoldsdorf', city: vienna},
          {name:'Pressbaum', city: vienna},
          {name:'Purkersdorf', city: vienna},
          {name:'Raasdorf', city: vienna},
          {name:'Rust Austria', city: vienna},
          {name:'Schwechat', city: vienna},
          {name:'Semmering', city: vienna},
          {name:'Spitz', city: vienna},
          {name:'St Polten', city: vienna},
          {name:'Stockerau', city: vienna},
          {name:'Tulln', city: vienna},
          {name:'Vienna City Centre', city: vienna},
          {name:'Waidhofen An Der Ybbs', city: vienna},
          {name:'Weidling', city: vienna},
          {name:'Weiz', city: vienna},
          {name:'Wiener Neudorf', city: vienna},
          {name:'Wiener Neustadt', city: vienna},
          {name:'Wolfsgraben', city: vienna},
          {name:'Zwettl', city: vienna}
          ])

  puts 'Cities of Portugal'
  beja = City.find_by(name: 'Beja')
  faro = City.find_by(name: 'Faro')
  funchal = City.find_by(name: 'Funchal')
  lisbon = City.find_by(name: 'Lisbon')
  porto = City.find_by(name: 'Porto')
  PickUpLocation.create([
          {name:'Beja Airport',city: beja},
          {name:'Beja City Centre',city: beja},
          {name:'Almeirim',city: beja},
          {name:'Amieira',city: beja},
          {name:'Elvas',city: beja},
          {name:'Esporao',city: beja},
          {name:'Estremoz',city: beja},
          {name:'Almeirim',city: beja},
          {name:'Amieira',city: beja},
          {name:'Beja City Centre',city: beja},
          {name:'Elvas',city: beja},
          {name:'Esporao',city: beja},
          {name:'Estremoz',city: beja},
          {name:'Manta Rota',city: beja},
          {name:'Odemira',city: beja},
          {name:'Olhos de Agua',city: beja},
          {name:'Portalegre',city: beja},
          {name:'Reguengos de Monsaraz',city: beja},
          {name:'Serra da Estrela',city: beja},
          {name:'Faro Airport', city: faro},
          {name:'Albufeira', city: faro},
          {name:'Vilamoura', city: faro},
          {name:'Praia da Luz', city: faro},
          {name:'Alvor', city: faro},
          {name:'Quarteira', city: faro},
          {name:'Carvoeiro', city: faro},
          {name:'Acoteias', city: faro},
          {name:'Albufeira', city: faro},
          {name:'Alcantarilha', city: faro},
          {name:'Alcoutim', city: faro},
          {name:'Alfontes', city: faro},
          {name:'Algoz', city: faro},
          {name:'Aljezur', city: faro},
          {name:'Almadena', city: faro},
          {name:'Almancil', city: faro},
          {name:'Altura', city: faro},
          {name:'Alvor', city: faro},
          {name:'Areias de Sao Joao', city: faro},
          {name:'Armacao de Pera', city: faro},
          {name:'Ayamonte', city: faro},
          {name:'Balaia Golf Resort', city: faro},
          {name:'Boliqueime', city: faro},
          {name:'Bordeira', city: faro},
          {name:'Budens', city: faro},
          {name:'Burgau', city: faro},
          {name:'Cabanas de Tavira', city: faro},
          {name:'Carrapateira', city: faro},
          {name:'Carvoeiro', city: faro},
          {name:'Castro Marim', city: faro},
          {name:'El Rompido', city: faro},
          {name:'Estoi', city: faro},
          {name:'Falesia', city: faro},
          {name:'Faro City Centre', city: faro},
          {name:'Ferragudo', city: faro},
          {name:'Fuseta', city: faro},
          {name:'Gale', city: faro},
          {name:'Guia', city: faro},
          {name:'Isla Antilla', city: faro},
          {name:'Isla Canela', city: faro},
          {name:'Isla Critina', city: faro},
          {name:'Lagoa', city: faro},
          {name:'Lepe', city: faro},
          {name:'Loule', city: faro},
          {name:'Matalascanas', city: faro},
          {name:'Meia Praia', city: faro},
          {name:'Moncarapacho', city: faro},
          {name:'Monchique', city: faro},
          {name:'Monte Gordo', city: faro},
          {name:'Montechoro', city: faro},
          {name:'Montenegro', city: faro},
          {name:'Olhao', city: faro},
          {name:'Paderne', city: faro},
          {name:'Pechao', city: faro},
          {name:'Pedras Del Rei', city: faro},
          {name:'Penina', city: faro},
          {name:'Porches', city: faro},
          {name:'Praia da Falesia', city: faro},
          {name:'Praia da Luz', city: faro},
          {name:'Praia da Oura', city: faro},
          {name:'Praia da Rocha', city: faro},
          {name:'Praia do Vau', city: faro},
          {name:'Punta Umbria', city: faro},
          {name:'Quarteira', city: faro},
          {name:'Quinta do Lago', city: faro},
          {name:'Rocha Brava Resort', city: faro},
          {name:'Sagres', city: faro},
          {name:'Salema', city: faro},
          {name:'Santa Barbara de Nexe', city: faro},
          {name:'Santa Eulalia', city: faro},
          {name:'Santa Luzia', city: faro},
          {name:'Sao Bras de Alportel', city: faro},
          {name:'Sao Rafael', city: faro},
          {name:'Sesmarias', city: faro},
          {name:'Silves', city: faro},
          {name:'Tavira', city: faro},
          {name:'Vale Carros', city: faro},
          {name:'Vale Garrao', city: faro},
          {name:'Vale Parra', city: faro},
          {name:'Vale do Lobo', city: faro},
          {name:'Vila Real De Santo Antonio', city: faro},
          {name:'Vilamoura', city: faro},
          {name:'Madeira Funchal Airport', city: funchal},
          {name:'Funchal City Centre', city: funchal},
          {name:'Santa Cruz Funchal', city: funchal},
          {name:'Machico', city: funchal},
          {name:'Canico', city: funchal},
          {name:'Ribeira Brava', city: funchal},
          {name:'Calheta', city: funchal},
          {name:'Boaventura', city: funchal},
          {name:'Calheta', city: funchal},
          {name:'Camara de Lobos', city: funchal},
          {name:'Canico', city: funchal},
          {name:'Choupana Hills Resort', city: funchal},
          {name:'Encumeada', city: funchal},
          {name:'Funchal City Centre', city: funchal},
          {name:'Jardim da Serra', city: funchal},
          {name:'Machico', city: funchal},
          {name:'Ponta Delgada', city: funchal},
          {name:'Ponta do Pargo', city: funchal},
          {name:'Ponta do Sol', city: funchal},
          {name:'Porto Moniz', city: funchal},
          {name:'Porto da Cruz', city: funchal},
          {name:'Ribeira Brava', city: funchal},
          {name:'Santa Cruz Funchal', city: funchal},
          {name:'Santana', city: funchal},
          {name:'Santo da Serra', city: funchal},
          {name:'Sao Jorge', city: funchal},
          {name:'Sao Vicente', city: funchal},
          {name:'Lisbon Airport', city: lisbon},
          {name:'Belem Cruise Port', city: lisbon},
          {name:'Lisbon Cruise Port', city: lisbon},
          {name:'Lisbon Train Station', city: lisbon},
          {name:'Lisbon City Centre', city: lisbon},
          {name:'Cascais', city: lisbon},
          {name:'Lagos', city: lisbon},
          {name:'Estoril', city: lisbon},
          {name:'Sintra', city: lisbon},
          {name:'Fatima', city: lisbon},
          {name:'Alcobaca', city: lisbon},
          {name:'Alcochete', city: lisbon},
          {name:'Algarve', city: lisbon},
          {name:'Azinhaga', city: lisbon},
          {name:'Batalha', city: lisbon},
          {name:'Bombarral', city: lisbon},
          {name:'Caldas da Rainha', city: lisbon},
          {name:'Caparica', city: lisbon},
          {name:'Cascais', city: lisbon},
          {name:'Castelo Branco', city: lisbon},
          {name:'Charneca da Caparica', city: lisbon},
          {name:'Coimbra', city: lisbon},
          {name:'Colares', city: lisbon},
          {name:'Costa da Caparica', city: lisbon},
          {name:'Ericeira', city: lisbon},
          {name:'Estoril', city: lisbon},
          {name:'Evora', city: lisbon},
          {name:'Fatima', city: lisbon},
          {name:'Figueira da Foz', city: lisbon},
          {name:'Foros de Salvaterra', city: lisbon},
          {name:'Foz do Arelho', city: lisbon},
          {name:'Fundao', city: lisbon},
          {name:'Gradil', city: lisbon},
          {name:'Guincho', city: lisbon},
          {name:'Lagos', city: lisbon},
          {name:'Leiria', city: lisbon},
          {name:'Lisbon City Centre', city: lisbon},
          {name:'Luso', city: lisbon},
          {name:'Mafra', city: lisbon},
          {name:'Marinha Grande', city: lisbon},
          {name:'Mindelo', city: lisbon},
          {name:'Miraflores', city: lisbon},
          {name:'Montijo', city: lisbon},
          {name:'Nazare', city: lisbon},
          {name:'Obidos', city: lisbon},
          {name:'Oeiras', city: lisbon},
          {name:'Paco de Arcos', city: lisbon},
          {name:'Palmela', city: lisbon},
          {name:'Penha Longa Golf Resort', city: lisbon},
          {name:'Peniche', city: lisbon},
          {name:'Portimao', city: lisbon},
          {name:'Praia Grande', city: lisbon},
          {name:'Praia del Rey', city: lisbon},
          {name:'Private tour of Lisbon', city: lisbon},
          {name:'Queijas', city: lisbon},
          {name:'Queluz', city: lisbon},
          {name:'Salir do Porto', city: lisbon},
          {name:'Santa Cruz', city: lisbon},
          {name:'Santa Iria da Azoia', city: lisbon},
          {name:'Santa Maria de Belem', city: lisbon},
          {name:'Santarem', city: lisbon},
          {name:'Santiago de Cacem', city: lisbon},
          {name:'Santo Estevao', city: lisbon},
          {name:'Sao Martinho do Porto', city: lisbon},
          {name:'Seixal', city: lisbon},
          {name:'Sesimbra', city: lisbon},
          {name:'Setubal', city: lisbon},
          {name:'Sevilha', city: lisbon},
          {name:'Sines', city: lisbon},
          {name:'Sintra', city: lisbon},
          {name:'Sintra Private Tour', city: lisbon},
          {name:'Tomar', city: lisbon},
          {name:'Torres Vedras', city: lisbon},
          {name:'Troia by Ferry', city: lisbon},
          {name:'Troia by road', city: lisbon},
          {name:'Turcifal', city: lisbon},
          {name:'Vieira de Leiria', city: lisbon},
          {name:'Vila do Bispo', city: lisbon},
          {name:'Villa Nova de Milfontes', city: lisbon},
          {name:'Porto Airport', city: porto},
          {name:'Porto Cruise Port', city: porto},
          {name:'Porto City Centre', city: porto},
          {name:'Vila Nova de Gaia', city: porto},
          {name:'Aveiro', city: porto},
          {name:'Esposende', city: porto},
          {name:'Braga', city: porto},
          {name:'Viseu', city: porto},
          {name:'Amarante', city: porto},
          {name:'Arcos de Valdevez', city: porto},
          {name:'Aveiro', city: porto},
          {name:'Baiona', city: porto},
          {name:'Barcelos', city: porto},
          {name:'Braga', city: porto},
          {name:'Braganca', city: porto},
          {name:'Bussaco', city: porto},
          {name:'Chaves', city: porto},
          {name:'Espinho', city: porto},
          {name:'Esposende', city: porto},
          {name:'Estarreja', city: porto},
          {name:'Europarque', city: porto},
          {name:'Guarda', city: porto},
          {name:'Guimaraes', city: porto},
          {name:'Lamego', city: porto},
          {name:'Mirandela', city: porto},
          {name:'Moncao', city: porto},
          {name:'Oliveira de Azemeis', city: porto},
          {name:'Ovar', city: porto},
          {name:'Pacos de Ferreira', city: porto},
          {name:'Paredes de Coura', city: porto},
          {name:'Penafiel', city: porto},
          {name:'Peso da Regua', city: porto},
          {name:'Pinhao', city: porto},
          {name:'Ponte da Barca', city: porto},
          {name:'Ponte de Lima', city: porto},
          {name:'Porto City Centre', city: porto},
          {name:'Povoa de Varzim', city: porto},
          {name:'Santa Maria da Feira', city: porto},
          {name:'Santo Tirso', city: porto},
          {name:'Sao Joao da Madeira', city: porto},
          {name:'Tui', city: porto},
          {name:'Valenca do Minho', city: porto},
          {name:'Viana do Castelo', city: porto},
          {name:'Vidago', city: porto},
          {name:'Vila Nova de Gaia', city: porto},
          {name:'Vila Real', city: porto},
          {name:'Vila do Conde', city: porto},
          {name:'Viseu', city: porto}
        ])
  puts 'Cities of Slovakia'
  bratislava = City.find_by(name:'Bratislava')
  PickUpLocation.create([
          {name:'Bratislava Airport', city: bratislava},
          {name:'Kosice Airport', city: bratislava},
          {name:'Bratislava Train Station', city: bratislava},
          {name:'Bratislava City Centre', city: bratislava},
          {name:'Zdiar', city: bratislava},
          {name:'Poprad', city: bratislava},
          {name:'Trnava', city: bratislava},
          {name:'Strbske Pleso', city: bratislava},
          {name:'Nitra', city: bratislava},
          {name:'Banska Bystrica', city: bratislava},
          {name:'Biele Vody nad Hrinova', city: bratislava},
          {name:'Bratislava City Centre', city: bratislava},
          {name:'Brusno', city: bratislava},
          {name:'Bukovina', city: bratislava},
          {name:'Bystricka', city: bratislava},
          {name:'Certovica', city: bratislava},
          {name:'Drienica', city: bratislava},
          {name:'Dubovica Zliabky', city: bratislava},
          {name:'Fackov', city: bratislava},
          {name:'Fackovske Sedlo', city: bratislava},
          {name:'High Tatras', city: bratislava},
          {name:'Hlohovec', city: bratislava},
          {name:'Jasenska Dolina', city: bratislava},
          {name:'Kokava nad Rimavicou', city: bratislava},
          {name:'Komarno', city: bratislava},
          {name:'Kosice', city: bratislava},
          {name:'Krahule', city: bratislava},
          {name:'Kraliky', city: bratislava},
          {name:'Kremnica', city: bratislava},
          {name:'Krompachy', city: bratislava},
          {name:'Kubinska Hola', city: bratislava},
          {name:'Limbach', city: bratislava},
          {name:'Liptovska Teplicka', city: bratislava},
          {name:'Liptovske Jan', city: bratislava},
          {name:'Lubochna', city: bratislava},
          {name:'Lubovnianske Kupele', city: bratislava},
          {name:'Makov', city: bratislava},
          {name:'Mala Lucivna', city: bratislava},
          {name:'Martin', city: bratislava},
          {name:'Martinske Hole', city: bratislava},
          {name:'Mlynky', city: bratislava},
          {name:'Myto pod Dumbierom', city: bratislava},
          {name:'Nitra', city: bratislava},
          {name:'Oscadnica', city: bratislava},
          {name:'Pezinok', city: bratislava},
          {name:'Pezinska Baba', city: bratislava},
          {name:'Piestany', city: bratislava},
          {name:'Plejsy', city: bratislava},
          {name:'Podbanske', city: bratislava},
          {name:'Poprad', city: bratislava},
          {name:'Poruba', city: bratislava},
          {name:'Rackova Dolina', city: bratislava},
          {name:'Rajecke Teplice', city: bratislava},
          {name:'Regetovka', city: bratislava},
          {name:'Remata', city: bratislava},
          {name:'Rohace', city: bratislava},
          {name:'Senec', city: bratislava},
          {name:'Sered', city: bratislava},
          {name:'Skalite Serafinov', city: bratislava},
          {name:'Skalka', city: bratislava},
          {name:'Stary Smokovec', city: bratislava},
          {name:'Strbske Pleso', city: bratislava},
          {name:'Svit', city: bratislava},
          {name:'Telgart', city: bratislava},
          {name:'Teplica', city: bratislava},
          {name:'Trencianske Teplice', city: bratislava},
          {name:'Trencin', city: bratislava},
          {name:'Trnava', city: bratislava},
          {name:'Turany', city: bratislava},
          {name:'Turcianske Klacany', city: bratislava},
          {name:'Turecka', city: bratislava},
          {name:'Utekac', city: bratislava},
          {name:'Velka Raca', city: bratislava},
          {name:'Vernar', city: bratislava},
          {name:'Vratna', city: bratislava},
          {name:'Vrutky', city: bratislava},
          {name:'Vysne Ruzbachy', city: bratislava},
          {name:'Zavada', city: bratislava},
          {name:'Zdiar', city: bratislava},
          {name:'Zilina', city: bratislava}
        ])
  puts 'Cities of Serbia'
  belgrade = City.find_by(name:'Belgrade')
  PickUpLocation.create([
          {name:'Belgrade Airport', city: belgrade},
          {name:'Belgrade City Centre', city: belgrade},
          {name:'Jagodina', city: belgrade},
          {name:'Kopaonik', city: belgrade},
          {name:'Sarajevo City Centre', city: belgrade},
          {name:'Batocina', city: belgrade},
          {name:'Bor', city: belgrade},
          {name:'Batocina', city: belgrade},
          {name:'Belgrade City Centre', city: belgrade},
          {name:'Bor', city: belgrade},
          {name:'Cacak', city: belgrade},
          {name:'Cuprija', city: belgrade},
          {name:'Debeljaca', city: belgrade},
          {name:'Durdevi Stupovi', city: belgrade},
          {name:'Golubac', city: belgrade},
          {name:'Hopovo', city: belgrade},
          {name:'Indija', city: belgrade},
          {name:'Jagodina', city: belgrade},
          {name:'Kikinda', city: belgrade},
          {name:'Knjazevac', city: belgrade},
          {name:'Kopaonik', city: belgrade},
          {name:'Kragujevac', city: belgrade},
          {name:'Kraljevo', city: belgrade},
          {name:'Krusevac', city: belgrade},
          {name:'Leskovac', city: belgrade},
          {name:'Mediana', city: belgrade},
          {name:'Mladenovac', city: belgrade},
          {name:'Nis', city: belgrade},
          {name:'Niska Banja', city: belgrade},
          {name:'Novi Pazar', city: belgrade},
          {name:'Novi Sad', city: belgrade},
          {name:'Pancevo', city: belgrade},
          {name:'Paracin', city: belgrade},
          {name:'Petrovaradin', city: belgrade},
          {name:'Pozarevac', city: belgrade},
          {name:'Ruma', city: belgrade},
          {name:'Sabac', city: belgrade},
          {name:'Sarajevo City Centre', city: belgrade},
          {name:'Sokobanja', city: belgrade},
          {name:'Sombor', city: belgrade},
          {name:'Sremska Mitrovica', city: belgrade},
          {name:'Subotica', city: belgrade},
          {name:'Uzice', city: belgrade},
          {name:'Valjevo', city: belgrade},
          {name:'Vranje', city: belgrade},
          {name:'Vrnjacka Banja', city: belgrade},
          {name:'Vrsac', city: belgrade},
          {name:'Zajecar', city: belgrade},
          {name:'Zlatibor', city: belgrade},
          {name:'Zrenjanin', city: belgrade}
        ])
  puts 'Cities of Norway'
  oslo = City.find_by(name:'Oslo')
  PickUpLocation.create([
          {name:'Oslo Airport', city: oslo},
          {name:'Sandefjord Airport', city: oslo},
          {name:'Oslo City Centre', city: oslo},
          {name:'Stavanger', city: oslo},
          {name:'Bergen', city: oslo},
          {name:'Trondheim', city: oslo},
          {name:'Tromso', city: oslo},
          {name:'Rygge Airport', city: oslo},
          {name:'Bergen', city: oslo},
          {name:'Hamar', city: oslo},
          {name:'Oslo City Centre', city: oslo},
          {name:'Rygge Airport', city: oslo},
          {name:'Stavanger', city: oslo},
          {name:'Tromso', city: oslo},
          {name:'Trondheim', city: oslo}
        ])
  puts 'Cities of Malta'
  valletta = City.find_by(name: 'Valletta')
  PickUpLocation.create([
          {name:'Malta Airport',city: valletta},
          {name:'Sliema',city: valletta},
          {name:'Bugibba',city: valletta},
          {name:'Mellieha',city: valletta},
          {name:'St Julians',city: valletta},
          {name:'St Paul Bay',city: valletta},
          {name:'Valletta City Centre',city: valletta},
          {name:'Bugibba',city: valletta},
          {name:'Mellieha',city: valletta},
          {name:'Msida',city: valletta},
          {name:'Sliema',city: valletta},
          {name:'St Julians',city: valletta},
          {name:'St Paul Bay',city: valletta},
          {name:'Valletta City Centre',city: valletta}
        ])
  puts 'Cities of Luxembourg'
  luxembourg = City.find_by(name: 'Luxembourg')
  PickUpLocation.create([
          {name:'Luxembourg Airport', city: luxembourg},
          {name:'Luxembourg Train Station', city: luxembourg},
          {name:'Luxembourg City Centre', city: luxembourg},
          {name:'Bascharage', city: luxembourg},
          {name:'Capellen', city: luxembourg},
          {name:'Diekirch', city: luxembourg},
          {name:'Differdange', city: luxembourg},
          {name:'Dippach', city: luxembourg},
          {name:'Bascharage', city: luxembourg},
          {name:'Capellen', city: luxembourg},
          {name:'Diekirch', city: luxembourg},
          {name:'Differdange', city: luxembourg},
          {name:'Dippach', city: luxembourg},
          {name:'Dudelange', city: luxembourg},
          {name:'Esch sur Alzette', city: luxembourg},
          {name:'Ettelbruck', city: luxembourg},
          {name:'Grevenmacher', city: luxembourg},
          {name:'Luxembourg City Centre', city: luxembourg},
          {name:'Mersch', city: luxembourg},
          {name:'Mondorf les Bains', city: luxembourg},
          {name:'Petange', city: luxembourg},
          {name:'Remich', city: luxembourg},
          {name:'Steinsel', city: luxembourg},
          {name:'Vianden', city: luxembourg},
          {name:'Wasserbillig', city: luxembourg},
          {name:'Wiltz', city: luxembourg}
        ])
  puts 'Cities of Hungary'
  budapest = City.find_by(name:'Budapest')
  PickUpLocation.create([
          {name:'Budapest Airport', city: budapest},
          {name:'Sarmellek Balaton Airport', city: budapest},
          {name:'Budapest Cruise Port', city: budapest},
          {name:'Budapest Train Station', city: budapest},
          {name:'Budapest City Centre', city: budapest},
          {name:'Nagykanizsa', city: budapest},
          {name:'Pecs', city: budapest},
          {name:'Vonyarcvashegy', city: budapest},
          {name:'Heviz', city: budapest},
          {name:'Szekesfehervar', city: budapest},
          {name:'Abrahamhegy', city: budapest},
          {name:'Alsopahok', city: budapest},
          {name:'Badacsony', city: budapest},
          {name:'Badacsonytomaj', city: budapest},
          {name:'Balaton Ring', city: budapest},
          {name:'Balatonakali', city: budapest},
          {name:'Balatonakarattya', city: budapest},
          {name:'Balatonaliga', city: budapest},
          {name:'Balatonalmadi', city: budapest},
          {name:'Balatonbereny', city: budapest},
          {name:'Balatonboglar', city: budapest},
          {name:'Balatonfenyves', city: budapest},
          {name:'Balatonfoldvar', city: budapest},
          {name:'Balatonfured', city: budapest},
          {name:'Balatongyorok', city: budapest},
          {name:'Balatonkenese', city: budapest},
          {name:'Balatonkeresztur', city: budapest},
          {name:'Balatonlelle', city: budapest},
          {name:'Balatonmariafurdo', city: budapest},
          {name:'Balatonudvari', city: budapest},
          {name:'Balatonvilagos', city: budapest},
          {name:'Budapest City Centre', city: budapest},
          {name:'Bukfurdo', city: budapest},
          {name:'Csepreg', city: budapest},
          {name:'Csopak', city: budapest},
          {name:'Debrecen', city: budapest},
          {name:'Eger', city: budapest},
          {name:'Felsopahok', city: budapest},
          {name:'Fonyod', city: budapest},
          {name:'God', city: budapest},
          {name:'Gyenesdias', city: budapest},
          {name:'Gyor', city: budapest},
          {name:'Halaszi', city: budapest},
          {name:'Heviz', city: budapest},
          {name:'Hungaroring', city: budapest},
          {name:'Kaposvar', city: budapest},
          {name:'Keszthely', city: budapest},
          {name:'Komlo', city: budapest},
          {name:'Mosonmagyarovar', city: budapest},
          {name:'Nagykanizsa', city: budapest},
          {name:'Pecs', city: budapest},
          {name:'Revfulop', city: budapest},
          {name:'Rojtokmuzsaj', city: budapest},
          {name:'Sarvar', city: budapest},
          {name:'Siofok', city: budapest},
          {name:'Sopron', city: budapest},
          {name:'Szantod', city: budapest},
          {name:'Szeged', city: budapest},
          {name:'Szekesfehervar', city: budapest},
          {name:'Szentgotthard', city: budapest},
          {name:'Szombathely', city: budapest},
          {name:'Tapolca', city: budapest},
          {name:'Tihany', city: budapest},
          {name:'Vonyarcvashegy', city: budapest},
          {name:'Zalaegerszeg', city: budapest},
          {name:'Zalakaros', city: budapest},
          {name:'Zamardi', city: budapest},
          {name:'Zanka', city: budapest}
        ])
  puts 'Cities of Finland'
  helsinki = City.find_by(name:'Helsinki')
  PickUpLocation.create([
          {name:'Helsinki Airport', city: helsinki},
          {name:'Helsinki Cruise Port', city: helsinki},
          {name:'Helsinki Train Station', city: helsinki},
          {name:'Helsinki City Centre', city: helsinki},
          {name:'Espoo', city: helsinki},
          {name:'Tempere', city: helsinki},
          {name:'Naantali', city: helsinki},
          {name:'Vantaa', city: helsinki},
          {name:'Turku', city: helsinki},
          {name:'Dalsbruk', city: helsinki},
          {name:'Espoo', city: helsinki},
          {name:'Hamina', city: helsinki},
          {name:'Hanko', city: helsinki},
          {name:'Helsinki City Centre', city: helsinki},
          {name:'Korpilampi', city: helsinki},
          {name:'Kotka', city: helsinki},
          {name:'Lahti', city: helsinki},
          {name:'Lappeenranta', city: helsinki},
          {name:'Loviisa', city: helsinki},
          {name:'Mikkeli', city: helsinki},
          {name:'Naantali', city: helsinki},
          {name:'Pori', city: helsinki},
          {name:'Porvoo', city: helsinki},
          {name:'Taalindtehdas', city: helsinki},
          {name:'Tempere', city: helsinki},
          {name:'Turku', city: helsinki},
          {name:'Vantaa', city: helsinki}
        ])
  puts 'Cities of Belgium'
  antwerp = City.find_by(name:'Antwerp')
  bruges  = City.find_by(name:'Bruges')
  brussels = City.find_by(name:'Brussels')
  PickUpLocation.create([
          {name:'Antwerp Airport', city: antwerp},
          {name:'Antwerp Cruise Port', city: antwerp},
          {name:'Antwerp City Centre', city: antwerp},
          {name:'Sint Niklaas', city: antwerp},
          {name:'Knokke Heist', city: antwerp},
          {name:'Lier', city: antwerp},
          {name:'Geel', city: antwerp},
          {name:'Kontich', city: antwerp},
          {name:'Antwerp City Centre', city: antwerp},
          {name:'Beveren Waas', city: antwerp},
          {name:'Eeklo', city: antwerp},
          {name:'Geel', city: antwerp},
          {name:'Heist op den Berg', city: antwerp},
          {name:'Knokke Heist', city: antwerp},
          {name:'Kontich', city: antwerp},
          {name:'Lier', city: antwerp},
          {name:'Lommel', city: antwerp},
          {name:'Mol', city: antwerp},
          {name:'Oud Turnhout', city: antwerp},
          {name:'Ruisbroek', city: antwerp},
          {name:'Sint Niklaas', city: antwerp},
          {name:'Turnhout', city: antwerp},
          {name:'Waasmunster', city: antwerp},
          {name:'Zwijndrecht', city: antwerp},
          {name:'Bruges Airport', city: bruges},
          {name:'Zeebruges Port', city: bruges},
          {name:'Bruges Train Station', city: bruges},
          {name:'Bruges City Centre', city: bruges},
          {name:'Zeebruges', city: bruges},
          {name:'Bruges City Centre', city: bruges},
          {name:'Zeebruges', city: bruges},
          {name:'Brussels Airport', city: brussels},
          {name:'Charleroi Airport', city: brussels},
          {name:'Liege Airport', city: brussels},
          {name:'Brussels Central Train Station', city: brussels},
          {name:'Brussels Midi Train Station', city: brussels},
          {name:'Brussels Nord Train Station', city: brussels},
          {name:'Brussels City Centre', city: brussels},
          {name:'Leuven', city: brussels},
          {name:'La Hulpe', city: brussels},
          {name:'Louvain la Neuve', city: brussels},
          {name:'Waterloo', city: brussels},
          {name:'Ghent', city: brussels},
          {name:'Aalst', city: brussels},
          {name:'Aarschot', city: brussels},
          {name:'Affligem', city: brussels},
          {name:'Alsemberg', city: brussels},
          {name:'Andenne', city: brussels},
          {name:'Anderlues', city: brussels},
          {name:'Annevoie Rouillon', city: brussels},
          {name:'Antoing', city: brussels},
          {name:'Arlon', city: brussels},
          {name:'Asse', city: brussels},
          {name:'Ath', city: brussels},
          {name:'Athus', city: brussels},
          {name:'Barvaux sur Ourthe', city: brussels},
          {name:'Bastogne', city: brussels},
          {name:'Baudour', city: brussels},
          {name:'Beaumont', city: brussels},
          {name:'Beerse', city: brussels},
          {name:'Beersel', city: brussels},
          {name:'Beloeil', city: brussels},
          {name:'Bertrix', city: brussels},
          {name:'Bierges', city: brussels},
          {name:'Binche', city: brussels},
          {name:'Blanden', city: brussels},
          {name:'Blankenberge', city: brussels},
          {name:'Bocholt', city: brussels},
          {name:'Boom', city: brussels},
          {name:'Bouillon', city: brussels},
          {name:'Braine Le Chateau', city: brussels},
          {name:'Braine l Alleud', city: brussels},
          {name:'Braine le Comte', city: brussels},
          {name:'Bredene', city: brussels},
          {name:'Bree', city: brussels},
          {name:'Bruges', city: brussels},
          {name:'Brussegem', city: brussels},
          {name:'Brussels Airport Hotel', city: brussels},
          {name:'Brussels City Centre', city: brussels},
          {name:'Brussels Port', city: brussels},
          {name:'Cambron Casteau', city: brussels},
          {name:'Charleroi', city: brussels},
          {name:'Chevetogne', city: brussels},
          {name:'Chievres', city: brussels},
          {name:'Chimay', city: brussels},
          {name:'Chiny', city: brussels},
          {name:'Ciney', city: brussels},
          {name:'Court Saint Etienne', city: brussels},
          {name:'Couvin', city: brussels},
          {name:'De Haan', city: brussels},
          {name:'De Panne', city: brussels},
          {name:'Dendermonde', city: brussels},
          {name:'Diegem', city: brussels},
          {name:'Diepenbeek', city: brussels},
          {name:'Diest', city: brussels},
          {name:'Diksmuide', city: brussels},
          {name:'Dilbeek', city: brussels},
          {name:'Dinant', city: brussels},
          {name:'Dour', city: brussels},
          {name:'Drogenbos', city: brussels},
          {name:'Dunkerque', city: brussels},
          {name:'Durbuy', city: brussels},
          {name:'Dworp', city: brussels},
          {name:'Enghien', city: brussels},
          {name:'Erpe Mere', city: brussels},
          {name:'Erps Kwerps', city: brussels},
          {name:'Erquelinnes', city: brussels},
          {name:'Feluy', city: brussels},
          {name:'Flobecq', city: brussels},
          {name:'Floreffe', city: brussels},
          {name:'Florennes', city: brussels},
          {name:'Florenville', city: brussels},
          {name:'Fosses la Ville', city: brussels},
          {name:'Francorchamps', city: brussels},
          {name:'Gedinne', city: brussels},
          {name:'Gembloux', city: brussels},
          {name:'Genappe', city: brussels},
          {name:'Genk', city: brussels},
          {name:'Genval', city: brussels},
          {name:'Geraardsbergen', city: brussels},
          {name:'Gerpinnes', city: brussels},
          {name:'Ghent', city: brussels},
          {name:'Godinne', city: brussels},
          {name:'Gooik', city: brussels},
          {name:'Grimbergen', city: brussels},
          {name:'Groot Bijgaarden', city: brussels},
          {name:'Haacht', city: brussels},
          {name:'Haasrode', city: brussels},
          {name:'Habay la Neuve', city: brussels},
          {name:'Halle', city: brussels},
          {name:'Hamoir', city: brussels},
          {name:'Han sur Lesse', city: brussels},
          {name:'Hannut', city: brussels},
          {name:'Hasselt', city: brussels},
          {name:'Hastiere', city: brussels},
          {name:'Havelange', city: brussels},
          {name:'Herentals', city: brussels},
          {name:'Heusden Zolder', city: brussels},
          {name:'Heverlee', city: brussels},
          {name:'Hoeilaart', city: brussels},
          {name:'Hofstade', city: brussels},
          {name:'Houffalize', city: brussels},
          {name:'Huizingen', city: brussels},
          {name:'Huldenberg', city: brussels},
          {name:'Huy', city: brussels},
          {name:'Itterbeek', city: brussels},
          {name:'Jemeppe sur Sambre', city: brussels},
          {name:'Jodoigne', city: brussels},
          {name:'Kessel Lo', city: brussels},
          {name:'Kester', city: brussels},
          {name:'Koksijde', city: brussels},
          {name:'Korbeek Dijle', city: brussels},
          {name:'Kortenberg', city: brussels},
          {name:'Kortrijk', city: brussels},
          {name:'Kraainem', city: brussels},
          {name:'La Hulpe', city: brussels},
          {name:'La Louviere', city: brussels},
          {name:'La Roche en Ardenne', city: brussels},
          {name:'Landen', city: brussels},
          {name:'Lavaux Sainte Anne', city: brussels},
          {name:'Le Roeulx', city: brussels},
          {name:'Leefdaal', city: brussels},
          {name:'Lennik', city: brussels},
          {name:'Lessines', city: brussels},
          {name:'Lessive', city: brussels},
          {name:'Leuven', city: brussels},
          {name:'Leuze en Hainaut', city: brussels},
          {name:'Libramont Chevigny', city: brussels},
          {name:'Liege', city: brussels},
          {name:'Limal', city: brussels},
          {name:'Linkebeek', city: brussels},
          {name:'Lokeren', city: brussels},
          {name:'Londerzeel', city: brussels},
          {name:'Lot', city: brussels},
          {name:'Louvain la Neuve', city: brussels},
          {name:'Maaseik', city: brussels},
          {name:'Machelen', city: brussels},
          {name:'Maillen', city: brussels},
          {name:'Maldegem', city: brussels},
          {name:'Malmedy', city: brussels},
          {name:'Manage', city: brussels},
          {name:'Marbehan', city: brussels},
          {name:'Marche en Famenne', city: brussels},
          {name:'Martelange', city: brussels},
          {name:'Mechelen', city: brussels},
          {name:'Meise', city: brussels},
          {name:'Merchtem', city: brussels},
          {name:'Messancy', city: brussels},
          {name:'Middelkerke', city: brussels},
          {name:'Mons', city: brussels},
          {name:'Mouscron', city: brussels},
          {name:'Namur', city: brussels},
          {name:'Nazareth', city: brussels},
          {name:'Neufchateau', city: brussels},
          {name:'Nieuwpoort', city: brussels},
          {name:'Ninove', city: brussels},
          {name:'Nivelles', city: brussels},
          {name:'Ohain', city: brussels},
          {name:'Oostduinkerke', city: brussels},
          {name:'Opwijk', city: brussels},
          {name:'Ostend', city: brussels},
          {name:'Ottignies', city: brussels},
          {name:'Oud Heverlee', city: brussels},
          {name:'Overijse', city: brussels},
          {name:'Perk', city: brussels},
          {name:'Peruwelz', city: brussels},
          {name:'Peutie', city: brussels},
          {name:'Philippeville', city: brussels},
          {name:'Pommeroeul', city: brussels},
          {name:'Quievrain', city: brussels},
          {name:'Rebecq Rognon', city: brussels},
          {name:'Renaix', city: brussels},
          {name:'Rhode Saint Genese', city: brussels},
          {name:'Rixensart', city: brussels},
          {name:'Rochefort', city: brussels},
          {name:'Roeselare', city: brussels},
          {name:'Ronse', city: brussels},
          {name:'Roosdaal', city: brussels},
          {name:'Rosieres', city: brussels},
          {name:'Saint Vith', city: brussels},
          {name:'Sambreville', city: brussels},
          {name:'Sint Joris Weert', city: brussels},
          {name:'Sint Pieters Leeuw', city: brussels},
          {name:'Sint Truiden', city: brussels},
          {name:'Soignies', city: brussels},
          {name:'Spa', city: brussels},
          {name:'Steenokkerzeel', city: brussels},
          {name:'Sterrebeek', city: brussels},
          {name:'Strombeek Bever', city: brussels},
          {name:'Ternat', city: brussels},
          {name:'Tertre', city: brussels},
          {name:'Tervuren', city: brussels},
          {name:'Thuin', city: brussels},
          {name:'Tielt Winge', city: brussels},
          {name:'Tienen', city: brussels},
          {name:'Tongeren', city: brussels},
          {name:'Tournai', city: brussels},
          {name:'Tubize', city: brussels},
          {name:'Verviers', city: brussels},
          {name:'Veurne', city: brussels},
          {name:'Viller sur Semois', city: brussels},
          {name:'Vilvoorde', city: brussels},
          {name:'Vlezenbeek', city: brussels},
          {name:'Vresse sur Semois', city: brussels},
          {name:'Waremme', city: brussels},
          {name:'Waterloo', city: brussels},
          {name:'Waulsort', city: brussels},
          {name:'Wavre', city: brussels},
          {name:'Wemmel', city: brussels},
          {name:'Westende', city: brussels},
          {name:'Wevelgem', city: brussels},
          {name:'Wezembeek Oppem', city: brussels},
          {name:'Wilsele', city: brussels},
          {name:'Wolvertem', city: brussels},
          {name:'Yvoir', city: brussels},
          {name:'Zellik', city: brussels},
          {name:'Zemst', city: brussels},
          {name:'Zottegem', city: brussels}
        ])
  puts 'Cities of Bulgaria'
  burgas = City.find_by(name:'Burgas')
  plovdiv = City.find_by(name:'Plovdiv')
  sofia = City.find_by(name:'Sofia')
  varna = City.find_by(name:'Varna')
  PickUpLocation.create([
          {name:'Burgas Airport', city: burgas},
          {name:'Burgas Port', city: burgas},
          {name:'Burgas Train Station', city: burgas},
          {name:'Ahtopol', city: burgas},
          {name:'Slanchev Briag', city: burgas},
          {name:'Primorsko', city: burgas},
          {name:'Burgas', city: burgas},
          {name:'Burgas City Centre', city: burgas},
          {name:'Ahtopol', city: burgas},
          {name:'Burgas City Centre', city: burgas},
          {name:'Chernomorets', city: burgas},
          {name:'Duni', city: burgas},
          {name:'Elena', city: burgas},
          {name:'Elenite', city: burgas},
          {name:'Elhovo', city: burgas},
          {name:'Kamchia', city: burgas},
          {name:'Kardam', city: burgas},
          {name:'Karnobat', city: burgas},
          {name:'Kiten', city: burgas},
          {name:'Kosharitsa', city: burgas},
          {name:'Lozenets', city: burgas},
          {name:'Malko Tarnovo', city: burgas},
          {name:'Nessebar', city: burgas},
          {name:'Obzor', city: burgas},
          {name:'Pomorie', city: burgas},
          {name:'Primorsko', city: burgas},
          {name:'Ravda', city: burgas},
          {name:'Sinemorets', city: burgas},
          {name:'Slanchev Briag', city: burgas},
          {name:'Sliven', city: burgas},
          {name:'Sozopol', city: burgas},
          {name:'Sveti Vlas', city: burgas},
          {name:'Svilengrad', city: burgas},
          {name:'Tsarevo', city: burgas},
          {name:'Veliko Tarnovo', city: burgas},
          {name:'Yambol', city: burgas},
          {name:'Plovdiv Airport', city: plovdiv},
          {name:'Pamporovo', city: plovdiv},
          {name:'Haskovo', city: plovdiv},
          {name:'Plovdiv City Centre', city: plovdiv},
          {name:'Chepelare', city: plovdiv},
          {name:'Koprivshtitsa', city: plovdiv},
          {name:'Velingrad', city: plovdiv},
          {name:'Apriltsi', city: plovdiv},
          {name:'Arbanassi', city: plovdiv},
          {name:'Asenovgrad', city: plovdiv},
          {name:'Bachkovo', city: plovdiv},
          {name:'Bozhentsi', city: plovdiv},
          {name:'Chepelare', city: plovdiv},
          {name:'Chirpan', city: plovdiv},
          {name:'Devin', city: plovdiv},
          {name:'Dospat', city: plovdiv},
          {name:'Gabrovo', city: plovdiv},
          {name:'Gotse Delchev', city: plovdiv},
          {name:'Haskovo', city: plovdiv},
          {name:'Hisarya', city: plovdiv},
          {name:'Kalofer', city: plovdiv},
          {name:'Kapitan Andreevo', city: plovdiv},
          {name:'Kardzhali', city: plovdiv},
          {name:'Karlovo', city: plovdiv},
          {name:'Kazanlak', city: plovdiv},
          {name:'Koprivshtitsa', city: plovdiv},
          {name:'Kulata', city: plovdiv},
          {name:'Leshten', city: plovdiv},
          {name:'Levski', city: plovdiv},
          {name:'Momchilgrad', city: plovdiv},
          {name:'Pamporovo', city: plovdiv},
          {name:'Pavel Bania', city: plovdiv},
          {name:'Pazardjik', city: plovdiv},
          {name:'Plovdiv City Centre', city: plovdiv},
          {name:'Sevlievo', city: plovdiv},
          {name:'Shipka', city: plovdiv},
          {name:'Shiroka Laka', city: plovdiv},
          {name:'Smolyan', city: plovdiv},
          {name:'Stara Zagora', city: plovdiv},
          {name:'Stoykite', city: plovdiv},
          {name:'Svishtov', city: plovdiv},
          {name:'Trigrad', city: plovdiv},
          {name:'Troyan', city: plovdiv},
          {name:'Tryavna', city: plovdiv},
          {name:'Velingrad', city: plovdiv},
          {name:'Sofia Airport', city: sofia},
          {name:'Bansko', city: sofia},
          {name:'Sofia City Centre', city: sofia},
          {name:'Borovets', city: sofia},
          {name:'Bankya', city: sofia},
          {name:'Belogradchik', city: sofia},
          {name:'Blagoevgrad', city: sofia},
          {name:'Bankya', city: sofia},
          {name:'Bansko', city: sofia},
          {name:'Belogradchik', city: sofia},
          {name:'Blagoevgrad', city: sofia},
          {name:'Borovets', city: sofia},
          {name:'Botevgrad', city: sofia},
          {name:'Dolna Banya', city: sofia},
          {name:'Dupnica', city: sofia},
          {name:'Elin Pelin', city: sofia},
          {name:'Govedartsi', city: sofia},
          {name:'Ihtiman', city: sofia},
          {name:'Kalotina', city: sofia},
          {name:'Kozloduy', city: sofia},
          {name:'Krapets', city: sofia},
          {name:'Kyustendil', city: sofia},
          {name:'Logodazh', city: sofia},
          {name:'Lovech', city: sofia},
          {name:'Melnik', city: sofia},
          {name:'Montana', city: sofia},
          {name:'Pernik', city: sofia},
          {name:'Petrich', city: sofia},
          {name:'Pleven', city: sofia},
          {name:'Pravets', city: sofia},
          {name:'Razlog', city: sofia},
          {name:'Ribaritsa', city: sofia},
          {name:'Rila', city: sofia},
          {name:'Samokov', city: sofia},
          {name:'Sandanski', city: sofia},
          {name:'Sofia City Centre', city: sofia},
          {name:'Vidin', city: sofia},
          {name:'Vitosha', city: sofia},
          {name:'Vratsa', city: sofia},
          {name:'Zlatna Panega', city: sofia},
          {name:'Varna Airport', city: varna},
          {name:'Balchik', city: varna},
          {name:'Golden Sands', city: varna},
          {name:'Byala', city: varna},
          {name:'Kavarna', city: varna},
          {name:'Rogachevo', city: varna},
          {name:'Ruse', city: varna},
          {name:'Albena', city: varna},
          {name:'Balchik', city: varna},
          {name:'Byala', city: varna},
          {name:'Dobrich', city: varna},
          {name:'Durankulak', city: varna},
          {name:'Golden Sands', city: varna},
          {name:'Kavarna', city: varna},
          {name:'Kranevo', city: varna},
          {name:'Rogachevo', city: varna},
          {name:'Ruse', city: varna},
          {name:'Shabla', city: varna},
          {name:'Shumen', city: varna},
          {name:'Silistra', city: varna},
          {name:'Slanchev Den', city: varna},
          {name:'Staro Oryahovo', city: varna},
          {name:'Tetovo', city: varna},
          {name:'Turgoviste', city: varna},
          {name:'Varna City Centre', city: varna}
        ])
  puts 'Cities of Croatia'
  dubrovnik = City.find_by(name:'Dubrovnik')
  osijek = City.find_by(name:'Osijek')
  pula = City.find_by(name:'Pula')
  rijeka = City.find_by(name:'Rijeka')
  split = City.find_by(name:'Split')
  zadar = City.find_by(name:'Zadar')
  zagreb = City.find_by(name:'Zagreb')
  PickUpLocation.create([
           {name:'Dubrovnik Airport', city: dubrovnik},
           {name:'Dubrovnik City Centre', city: dubrovnik},
           {name:'Cavtat', city: dubrovnik},
           {name:'Orasac', city: dubrovnik},
           {name:'Plat', city: dubrovnik},
           {name:'Zaton', city: dubrovnik},
           {name:'Brsecine', city: dubrovnik},
           {name:'Bar', city: dubrovnik},
           {name:'Brsecine', city: dubrovnik},
           {name:'Budva', city: dubrovnik},
           {name:'Cavtat', city: dubrovnik},
           {name:'Dubrovnik City Centre', city: dubrovnik},
           {name:'Herceg Novi', city: dubrovnik},
           {name:'Klek', city: dubrovnik},
           {name:'Kolocep', city: dubrovnik},
           {name:'Komolac', city: dubrovnik},
           {name:'Korcula', city: dubrovnik},
           {name:'Kupari', city: dubrovnik},
           {name:'Lopud', city: dubrovnik},
           {name:'Lozica', city: dubrovnik},
           {name:'Medjugorje', city: dubrovnik},
           {name:'Metkovic', city: dubrovnik},
           {name:'Mlini', city: dubrovnik},
           {name:'Molunat', city: dubrovnik},
           {name:'Orasac', city: dubrovnik},
           {name:'Orebic', city: dubrovnik},
           {name:'Perast', city: dubrovnik},
           {name:'Plat', city: dubrovnik},
           {name:'Ploce', city: dubrovnik},
           {name:'Sipan', city: dubrovnik},
           {name:'Slano', city: dubrovnik},
           {name:'Ston', city: dubrovnik},
           {name:'Tivat', city: dubrovnik},
           {name:'Trebinje', city: dubrovnik},
           {name:'Trpanj', city: dubrovnik},
           {name:'Trsteno', city: dubrovnik},
           {name:'Zaton', city: dubrovnik},
           {name:'Zupa Dubrovacka', city: dubrovnik},
           {name:'Osijek Airport', city: osijek},
           {name:'Slavonski Brod', city: osijek},
           {name:'Osijek City Centre', city: osijek},
           {name:'Vinkovci', city: osijek},
           {name:'Vukovar', city: osijek},
           {name:'Zupanja', city: osijek},
           {name:'Osijek City Centre', city: osijek},
           {name:'Slavonski Brod', city: osijek},
           {name:'Vinkovci', city: osijek},
           {name:'Vukovar', city: osijek},
           {name:'Zupanja', city: osijek},
           {name:'Pula Airport', city: pula},
           {name:'Pula', city: pula},
           {name:'Rijeka Airport', city: rijeka},
           {name:'Rijeka City Centre', city: rijeka},
           {name:'Split Airport', city: split},
           {name:'Split City Centre', city: split},
           {name:'Podgora', city: split},
           {name:'Marina', city: split},
           {name:'Sibenik', city: split},
           {name:'Podstrana', city: split},
           {name:'Makarska', city: split},
           {name:'Arbania', city: split},
           {name:'Baska Voda', city: split},
           {name:'Bol', city: split},
           {name:'Brela', city: split},
           {name:'Brodarica', city: split},
           {name:'Drvenik', city: split},
           {name:'Duce', city: split},
           {name:'Dugi Rat', city: split},
           {name:'Gradac', city: split},
           {name:'Grebastica', city: split},
           {name:'Igrane', city: split},
           {name:'Kastela', city: split},
           {name:'Komiza', city: split},
           {name:'Makarska', city: split},
           {name:'Marina', city: split},
           {name:'Marina ACI Trogir', city: split},
           {name:'Marina Kremik', city: split},
           {name:'Okrug Donji', city: split},
           {name:'Omis', city: split},
           {name:'Podgora', city: split},
           {name:'Podstrana', city: split},
           {name:'Primosten', city: split},
           {name:'Rogoznica', city: split},
           {name:'Seget Donji', city: split},
           {name:'Seget Vranjica', city: split},
           {name:'Sibenik', city: split},
           {name:'Skradin', city: split},
           {name:'Slatine', city: split},
           {name:'Solaris', city: split},
           {name:'Solin', city: split},
           {name:'Split Bus Station', city: split},
           {name:'Split City Centre', city: split},
           {name:'Split Ferry Port', city: split},
           {name:'Split Marina ACI', city: split},
           {name:'Stari Grad', city: split},
           {name:'Stobrec', city: split},
           {name:'Supetar', city: split},
           {name:'Trogir', city: split},
           {name:'Tucepi', city: split},
           {name:'Vela Luka', city: split},
           {name:'Vinisce', city: split},
           {name:'Vis', city: split},
           {name:'Zivogosce', city: split},
           {name:'Zadar Airport', city: zadar},
           {name:'Novalja', city: zadar},
           {name:'Zadar City Centre', city: zadar},
           {name:'Tisno', city: zadar},
           {name:'Starigrad Paklenica', city: zadar},
           {name:'Sukosan', city: zadar},
           {name:'Vodice', city: zadar},
           {name:'Biograd', city: zadar},
           {name:'Gornji Karin', city: zadar},
           {name:'Karlobag', city: zadar},
           {name:'Mali Losinj', city: zadar},
           {name:'Murter', city: zadar},
           {name:'Novalja', city: zadar},
           {name:'Pakostane', city: zadar},
           {name:'Petrcane', city: zadar},
           {name:'Starigrad Paklenica', city: zadar},
           {name:'Sukosan', city: zadar},
           {name:'Tisno', city: zadar},
           {name:'Vodice', city: zadar},
           {name:'Zadar City Centre', city: zadar},
           {name:'Zagreb Airport', city: zagreb},
           {name:'Zagreb Train Station', city: zagreb},
           {name:'Zagreb City Centre', city: zagreb},
           {name:'Opatija', city: zagreb},
           {name:'Plitvice Lakes', city: zagreb},
           {name:'Krk', city: zagreb},
           {name:'Rovinj', city: zagreb},
           {name:'Pag', city: zagreb},
           {name:'Baska', city: zagreb},
           {name:'Bednja', city: zagreb},
           {name:'Bihac', city: zagreb},
           {name:'Bjelovar', city: zagreb},
           {name:'Bosanska Kostajnica', city: zagreb},
           {name:'Cakovec', city: zagreb},
           {name:'Crikvenica', city: zagreb},
           {name:'Dakovo', city: zagreb},
           {name:'Daruvar', city: zagreb},
           {name:'Dreznik Grad', city: zagreb},
           {name:'Dugo Selo', city: zagreb},
           {name:'Fazana', city: zagreb},
           {name:'Grabovac', city: zagreb},
           {name:'Irinovac', city: zagreb},
           {name:'Jastrebarsko', city: zagreb},
           {name:'Jezerce', city: zagreb},
           {name:'Karlovac', city: zagreb},
           {name:'Koprivnica', city: zagreb},
           {name:'Krk', city: zagreb},
           {name:'Lovran', city: zagreb},
           {name:'Medulin', city: zagreb},
           {name:'Motovun', city: zagreb},
           {name:'Novi Vinodolski', city: zagreb},
           {name:'Novigrad', city: zagreb},
           {name:'Novigrad Istarski', city: zagreb},
           {name:'Opatija', city: zagreb},
           {name:'Pag', city: zagreb},
           {name:'Pazin', city: zagreb},
           {name:'Plitvice Lakes', city: zagreb},
           {name:'Podsused', city: zagreb},
           {name:'Porec', city: zagreb},
           {name:'Rab', city: zagreb},
           {name:'Rakovica', city: zagreb},
           {name:'Rovinj', city: zagreb},
           {name:'Rudanovac', city: zagreb},
           {name:'Samobor', city: zagreb},
           {name:'Senj', city: zagreb},
           {name:'Sesvete', city: zagreb},
           {name:'Sisak', city: zagreb},
           {name:'Smoljanac', city: zagreb},
           {name:'Stubicke Toplice', city: zagreb},
           {name:'Tuheljske Toplice', city: zagreb},
           {name:'Umag', city: zagreb},
           {name:'Varazdin', city: zagreb},
           {name:'Virovitica', city: zagreb},
           {name:'Vrsar', city: zagreb},
           {name:'Zagreb City Centre', city: zagreb},
           {name:'Zapresic', city: zagreb}
          ])
  puts 'Cities of Cyprus'
  larnaca = City.find_by(name:'Larnaca')
  limassol = City.find_by(name:'Limassol')
  paphos = City.find_by(name:'Paphos')
  PickUpLocation.create([
           {name:'Ercan Airport', city: larnaca},
           {name:'Larnaca Airport', city: larnaca},
           {name:'Ayia Napa', city: larnaca},
           {name:'Nicosia', city: larnaca},
           {name:'Protaras', city: larnaca},
           {name:'Kyrenia', city: larnaca},
           {name:'Larnaca City Centre', city: larnaca},
           {name:'Kiti', city: larnaca},
           {name:'Alaminos', city: larnaca},
           {name:'Anassa', city: larnaca},
           {name:'Aradippou', city: larnaca},
           {name:'Ayia Napa', city: larnaca},
           {name:'Ayia Thekla', city: larnaca},
           {name:'Bogaz', city: larnaca},
           {name:'Deryneia', city: larnaca},
           {name:'Dhekelia', city: larnaca},
           {name:'Droushia', city: larnaca},
           {name:'Esentepe', city: larnaca},
           {name:'Famagusta', city: larnaca},
           {name:'Governors Beach', city: larnaca},
           {name:'Kalavasos', city: larnaca},
           {name:'Kapparis', city: larnaca},
           {name:'Kiti', city: larnaca},
           {name:'Kyrenia', city: larnaca},
           {name:'Larnaca Bay', city: larnaca},
           {name:'Larnaca City Centre', city: larnaca},
           {name:'Letymbou', city: larnaca},
           {name:'Liopetri', city: larnaca},
           {name:'Maroni', city: larnaca},
           {name:'Mazotos', city: larnaca},
           {name:'Meniko', city: larnaca},
           {name:'Nicosia', city: larnaca},
           {name:'Ormidhia', city: larnaca},
           {name:'Oroklini', city: larnaca},
           {name:'Paralimni', city: larnaca},
           {name:'Pernera', city: larnaca},
           {name:'Pervolia', city: larnaca},
           {name:'Protaras', city: larnaca},
           {name:'Pyla', city: larnaca},
           {name:'Sotira', city: larnaca},
           {name:'Tochni', city: larnaca},
           {name:'RAF Akrotiri Airport', city: limassol},
           {name:'Limassol Cruise Port', city: limassol},
           {name:'Limassol', city: limassol},
           {name:'Nissi Bay', city: limassol},
           {name:'Episkopi', city: limassol},
           {name:'Agios Athanasios', city: limassol},
           {name:'Germasoyia', city: limassol},
           {name:'Pentakomo', city: limassol},
           {name:'Agios Athanasios', city: limassol},
           {name:'Egkomi', city: limassol},
           {name:'Episkopi', city: limassol},
           {name:'Germasoyia', city: limassol},
           {name:'Limassol', city: limassol},
           {name:'Makounta', city: limassol},
           {name:'Makronissos Agia Napa', city: limassol},
           {name:'Neo Chorio', city: limassol},
           {name:'Nissi Bay', city: limassol},
           {name:'Ora', city: limassol},
           {name:'Pano Akourdaleia', city: limassol},
           {name:'Pedoulas', city: limassol},
           {name:'Pentakomo', city: limassol},
           {name:'Prodromi', city: limassol},
           {name:'Skarinou', city: limassol},
           {name:'Skoulli', city: limassol},
           {name:'Steni', city: limassol},
           {name:'Tombs of Kings Road', city: limassol},
           {name:'Paphos Airport', city: paphos},
           {name:'Paphos City Centre', city: paphos},
           {name:'Pissouri', city: paphos},
           {name:'Aphrodite Hills', city: paphos},
           {name:'Polis', city: paphos},
           {name:'Coral Bay', city: paphos},
           {name:'Kissonerga', city: paphos},
           {name:'Agia Marina Chrysochous', city: paphos},
           {name:'Agios Georgios Peyia  ', city: paphos},
           {name:'Agros', city: paphos},
           {name:'Amathus', city: paphos},
           {name:'Anarita', city: paphos},
           {name:'Anavargos', city: paphos},
           {name:'Aphrodite Hills', city: paphos},
           {name:'Argaka', city: paphos},
           {name:'Ascos Coral Beach', city: paphos},
           {name:'Ayia Triada', city: paphos},
           {name:'Azia', city: paphos},
           {name:'Chloraka', city: paphos},
           {name:'Coral Bay', city: paphos},
           {name:'Drouseia', city: paphos},
           {name:'Emba', city: paphos},
           {name:'Erimi', city: paphos},
           {name:'Kakopetria', city: paphos},
           {name:'Kathikas', city: paphos},
           {name:'Kato Paphos', city: paphos},
           {name:'Kissonerga', city: paphos},
           {name:'Konia', city: paphos},
           {name:'Kouklia', city: paphos},
           {name:'Latchi', city: paphos},
           {name:'Latsia', city: paphos},
           {name:'Mandria', city: paphos},
           {name:'Miliou', city: paphos},
           {name:'Morphou', city: paphos},
           {name:'Nata', city: paphos},
           {name:'Nikokleia', city: paphos},
           {name:'Paphos City Centre', city: paphos},
           {name:'Peyia', city: paphos},
           {name:'Pissouri', city: paphos},
           {name:'Platres', city: paphos},
           {name:'Polis', city: paphos},
           {name:'Pomos', city: paphos},
           {name:'Tala', city: paphos},
           {name:'Troodos', city: paphos},
           {name:'Tsada', city: paphos}
          ])
  puts 'Cities of Czech Republic'
  prague = City.find_by(name:'Prague')
  PickUpLocation.create([
           {name:'Brno Airport', city: prague},
           {name:'Prague Airport', city: prague},
           {name:'Prague City Centre', city: prague},
           {name:'Brno', city: prague},
           {name:'Karlovy Vary', city: prague},
           {name:'Spindleruv Mlyn', city: prague},
           {name:'Paseky nad Jizerou', city: prague},
           {name:'Pec pod Snezkou', city: prague},
           {name:'Bedrichov', city: prague},
           {name:'Benecko', city: prague},
           {name:'Benesov', city: prague},
           {name:'Beroun', city: prague},
           {name:'Bila', city: prague},
           {name:'Brno', city: prague},
           {name:'Celadna', city: prague},
           {name:'Cenkovice', city: prague},
           {name:'Cerny Dul', city: prague},
           {name:'Cervenohorske Sedlo', city: prague},
           {name:'Ceske Budejovice', city: prague},
           {name:'Cesky Krumlov', city: prague},
           {name:'Chomutov', city: prague},
           {name:'Decin', city: prague},
           {name:'Domazlice', city: prague},
           {name:'Frantiskovy Lazne', city: prague},
           {name:'Harrachov', city: prague},
           {name:'Hradec Kralove', city: prague},
           {name:'Jablonec nad Nisou', city: prague},
           {name:'Janske Lazne', city: prague},
           {name:'Jihlava', city: prague},
           {name:'Jindrichuv Hradec', city: prague},
           {name:'Karlova Studanka', city: prague},
           {name:'Karlovy Vary', city: prague},
           {name:'Kladno', city: prague},
           {name:'Kolin', city: prague},
           {name:'Korenov', city: prague},
           {name:'Kralupy nad Vltavou', city: prague},
           {name:'Kromeriz', city: prague},
           {name:'Kutna Hora', city: prague},
           {name:'Lanov', city: prague},
           {name:'Liberec', city: prague},
           {name:'Loucna', city: prague},
           {name:'Mala Moravka', city: prague},
           {name:'Mala Upa', city: prague},
           {name:'Marianske Lazne', city: prague},
           {name:'Medvedin', city: prague},
           {name:'Mlada Boleslav', city: prague},
           {name:'Most', city: prague},
           {name:'Olomouc', city: prague},
           {name:'Opava', city: prague},
           {name:'Ostrava', city: prague},
           {name:'Ostruzna', city: prague},
           {name:'Pardubice', city: prague},
           {name:'Paseky nad Jizerou', city: prague},
           {name:'Pec pod Snezkou', city: prague},
           {name:'Plzen', city: prague},
           {name:'Podebrady', city: prague},
           {name:'Prague City Centre', city: prague},
           {name:'Pribram', city: prague},
           {name:'Ramzova', city: prague},
           {name:'Rokytnice nad Jizerou', city: prague},
           {name:'Semily', city: prague},
           {name:'Severak', city: prague},
           {name:'Spindleruv Mlyn', city: prague},
           {name:'Stare Mesto', city: prague},
           {name:'Sternberk', city: prague},
           {name:'Strazne', city: prague},
           {name:'Stribrna', city: prague},
           {name:'Sumperk', city: prague},
           {name:'Svetla pod Jestedem', city: prague},
           {name:'Svoboda nad Upou', city: prague},
           {name:'Tabor', city: prague},
           {name:'Tanvald', city: prague},
           {name:'Telc', city: prague},
           {name:'Teplice', city: prague},
           {name:'Terezin', city: prague},
           {name:'Trebon', city: prague},
           {name:'Trojanovice', city: prague},
           {name:'Turnov', city: prague},
           {name:'Usti nad Labem', city: prague},
           {name:'Uvaly', city: prague},
           {name:'Vitkovice', city: prague},
           {name:'Vrbno pod Pradedem', city: prague},
           {name:'Vrchlabi', city: prague},
           {name:'Zdobnice', city: prague},
           {name:'Zlin', city: prague}
 ])
  puts 'Cities of Egypt'
  alexandria = City.find_by(name:'Alexandria')
  aswan = City.find_by(name:'Aswan')
  cairo = City.find_by(name:'Cairo')
  dabaa = City.find_by(name:'Dabaa')
  hurghada = City.find_by(name:'Hurghada')
  luxor = City.find_by(name:'Luxor')
  marsa = City.find_by(name:'Marsa Alam')
  sharm = City.find_by(name:'Sharm El Sheikh')
  taba = City.find_by(name:'Taba')
  PickUpLocation.create([
           {name:'Alexandria Airport', city: alexandria},
           {name:'Marsa Matrouh', city: alexandria},
           {name:'Alexandria City Centre', city: alexandria},
           {name:'Aswan Airport', city: aswan},
           {name:'Aswan Port', city: aswan},
           {name:'Aswan', city: aswan},
           {name:'Abu Simbel', city: aswan},
           {name:'Cairo Airport', city: cairo},
           {name:'Cairo City Centre', city: cairo},
           {name:'Heliopolis', city: cairo},
           {name:'Giza Hotels', city: cairo},
           {name:'Ain El Sukhna', city: cairo},
           {name:'El Alamein', city: cairo},
           {name:'El Minia', city: cairo},
           {name:'Ain El Sukhna', city: cairo},
           {name:'Cairo City Centre', city: cairo},
           {name:'El Alamein', city: cairo},
           {name:'El Minia', city: cairo},
           {name:'Giza Hotels', city: cairo},
           {name:'Heliopolis', city: cairo},
           {name:'Pyramids', city: cairo},
           {name:'Zafarana', city: cairo},
           {name:'Dabaa Alalamain Airport', city: dabaa},
           {name:'Dabaa', city: dabaa},
           {name:'Porto Marina El Alameen', city: dabaa},
           {name:'Borg Al Arab', city: dabaa},
           {name:'Matrouh', city: dabaa},
           {name:'Hurghada Airport', city: hurghada},
           {name:'Hurghada Port', city: hurghada},
           {name:'Hurghada Hotels', city: hurghada},
           {name:'El Gouna', city: hurghada},
           {name:'Makhadi Bay', city: hurghada},
           {name:'Soma Bay', city: hurghada},
           {name:'Hamata', city: hurghada},
           {name:'Sahl Hasheesh', city: hurghada},
           {name:'Al Kosseir', city: hurghada},
           {name:'Berenice', city: hurghada},
           {name:'Caribbean World Soma Bay', city: hurghada},
           {name:'Conrad Resort', city: hurghada},
           {name:'Coral Beach', city: hurghada},
           {name:'El Hamrawein', city: hurghada},
           {name:'El Naaba', city: hurghada},
           {name:'El Quseir', city: hurghada},
           {name:'Hamata', city: hurghada},
           {name:'Makhadi Bay', city: hurghada},
           {name:'Ras Sadr', city: hurghada},
           {name:'Safaga', city: hurghada},
           {name:'Safaga Port', city: hurghada},
           {name:'Luxor Airport', city: luxor},
           {name:'Luxor Port', city: luxor},
           {name:'Luxor Hotels', city: luxor},
           {name:'Karnak', city: luxor},
           {name:'Movenpick Joile Ville Luxor', city: luxor},
           {name:'Marsa Alam Airport', city: marsa},
           {name:'Marsa Alam', city: marsa},
           {name:'Abu Dabbab', city: marsa},
           {name:'Wadi Gimal', city: marsa},
           {name:'Shams Alam', city: marsa},
           {name:'Wadi Lahami', city: marsa},
           {name:'Abu Dabbab', city: marsa},
           {name:'Sharm El Sheikh Airport', city: sharm},
           {name:'Nuweiba Port', city: sharm},
           {name:'Sharm El Sheikh Port', city: sharm},
           {name:'Sharm El Sheikh Hotels', city: sharm},
           {name:'Sharks Bay', city: sharm},
           {name:'Naama Bay', city: sharm},
           {name:'Nabq Bay', city: sharm},
           {name:'Dahab', city: sharm},
           {name:'Om El Seid Hill', city: sharm},
           {name:'Hadaba', city: sharm},
           {name:'Neema Bay', city: sharm},
           {name:'Nuweiba', city: sharm},
           {name:'Ras Nasrani', city: sharm},
           {name:'Rus Um Shid', city: sharm},
           {name:'St Catherine', city: sharm},
           {name:'Taba Airport', city: taba},
           {name:'Sinai Bay Club Med', city: taba},
           {name:'Taba', city: taba}
          ])



end