after :cities do

  # Cities of Austria
  innsbruck = City.find_by(name: 'Innsbruck')
  klagenfurt = City.find_by(name: 'Klagenfurt')
  salzburg = City.find_by(name: 'Salzburg')
  vienna = City.find_by(name: 'Vienna')
  PickUpLocation.create([
        {name:'Innsbruck Airport',city:innsbruck},
        {name:'Innsbruck Train Station',city:innsbruck},
        {name:'Kitzbuhel',city:innsbruck},
        {name:'Mayrhofen',city:innsbruck},
        {name:'Ischgl',city:innsbruck},
        {name:'Fugen',city:innsbruck},
        {name:'Lech',city:innsbruck},
        {name:'Absam',city:innsbruck},
        {name:'Achenkirch',city:innsbruck},
        {name:'Affenhausen',city:innsbruck},
        {name:'Alberschwende',city:innsbruck},
        {name:'Alpbach',city:innsbruck},
        {name:'Andelsbuch',city:innsbruck},
        {name:'Arzl im Pitztal',city:innsbruck},
        {name:'Aschau im Zillertal',city:innsbruck},
        {name:'Au',city:innsbruck},
        {name:'Auffach',city:innsbruck},
        {name:'Aurach bei Kitzbuhel',city:innsbruck},
        {name:'Axamer Lizum',city:innsbruck},
        {name:'Axams',city:innsbruck},
        {name:'Bad Haring',city:innsbruck},
        {name:'Berwang',city:innsbruck},
        {name:'Biberwier',city:innsbruck},
        {name:'Bichlbach',city:innsbruck},
        {name:'Birgitz',city:innsbruck},
        {name:'Bizau',city:innsbruck},
        {name:'Bludenz',city:innsbruck},
        {name:'Brand',city:innsbruck},
        {name:'Brandenberg',city:innsbruck},
        {name:'Bregenz',city:innsbruck},
        {name:'Brennerpass',city:innsbruck},
        {name:'Brixen im Thale',city:innsbruck},
        {name:'Brixlegg',city:innsbruck},
        {name:'Bruck am Ziller',city:innsbruck},
        {name:'Burserberg',city:innsbruck},
        {name:'Dalaas',city:innsbruck},
        {name:'Damuels',city:innsbruck},
        {name:'Dirschenbach',city:innsbruck},
        {name:'Dornbirn',city:innsbruck},
        {name:'Ebbs',city:innsbruck},
        {name:'Eben am Achensee',city:innsbruck},
        {name:'Ehrwald',city:innsbruck},
        {name:'Eigenhofen',city:innsbruck},
        {name:'Elblingenalp',city:innsbruck},
        {name:'Ellmau',city:innsbruck},
        {name:'Elmen',city:innsbruck},
        {name:'Erl',city:innsbruck},
        {name:'Erpfendorf',city:innsbruck},
        {name:'Faschina',city:innsbruck},
        {name:'Feldkirch',city:innsbruck},
        {name:'Fernpass',city:innsbruck},
        {name:'Fieberbrunn',city:innsbruck},
        {name:'Fiecht',city:innsbruck},
        {name:'Finkenberg',city:innsbruck},
        {name:'Fiss',city:innsbruck},
        {name:'Flaurling',city:innsbruck},
        {name:'Fliess',city:innsbruck},
        {name:'Flirsch',city:innsbruck},
        {name:'Fontanella',city:innsbruck},
        {name:'Frohnhausen',city:innsbruck},
        {name:'Fugen',city:innsbruck},
        {name:'Fulpmes',city:innsbruck},
        {name:'Galtuer',city:innsbruck},
        {name:'Galtur',city:innsbruck},
        {name:'Gargellen',city:innsbruck},
        {name:'Gerlos',city:innsbruck},
        {name:'Gnadenwald',city:innsbruck},
        {name:'Going am Wilden Kaiser',city:innsbruck},
        {name:'Gotzens',city:innsbruck},
        {name:'Gotzis',city:innsbruck},
        {name:'Gries Sellrain',city:innsbruck},
        {name:'Gries am Brenner',city:innsbruck},
        {name:'Grinzens',city:innsbruck},
        {name:'Gschnitz',city:innsbruck},
        {name:'Haiming',city:innsbruck},
        {name:'Hall in Tirol',city:innsbruck},
        {name:'Hatting',city:innsbruck},
        {name:'Heiligenblut',city:innsbruck},
        {name:'Heiterwang',city:innsbruck},
        {name:'Hintertux',city:innsbruck},
        {name:'Hippach',city:innsbruck},
        {name:'Hochfilzen',city:innsbruck},
        {name:'Hochfugen',city:innsbruck},
        {name:'Hochgurgl',city:innsbruck},
        {name:'Hochpillberg',city:innsbruck},
        {name:'Hochzirl',city:innsbruck},
        {name:'Hofen',city:innsbruck},
        {name:'Hohenems',city:innsbruck},
        {name:'Hopfgarten im Brixental',city:innsbruck},
        {name:'Huben',city:innsbruck},
        {name:'Igls',city:innsbruck},
        {name:'Imst',city:innsbruck},
        {name:'Innsbruck City Centre',city:innsbruck},
        {name:'Inzing',city:innsbruck},
        {name:'Ischgl',city:innsbruck},
        {name:'Itter',city:innsbruck},
        {name:'Jenbach',city:innsbruck},
        {name:'Judenstein',city:innsbruck},
        {name:'Jungholz',city:innsbruck},
        {name:'Kaltenbach',city:innsbruck},
        {name:'Kampl',city:innsbruck},
        {name:'Kappl',city:innsbruck},
        {name:'Karres',city:innsbruck},
        {name:'Kaunertal',city:innsbruck},
        {name:'Kauns',city:innsbruck},
        {name:'Kelchsau',city:innsbruck},
        {name:'Kematen',city:innsbruck},
        {name:'Kirchberg in Tirol',city:innsbruck},
        {name:'Kirchbichl',city:innsbruck},
        {name:'Kitzbuhel',city:innsbruck},
        {name:'Kleinwalsertal',city:innsbruck},
        {name:'Klosterle',city:innsbruck},
        {name:'Koessen',city:innsbruck},
        {name:'Kolsass',city:innsbruck},
        {name:'Konigsleiten',city:innsbruck},
        {name:'Kossen',city:innsbruck},
        {name:'Kramsach',city:innsbruck},
        {name:'Krimml',city:innsbruck},
        {name:'Krossbach',city:innsbruck},
        {name:'Kufstein',city:innsbruck},
        {name:'Kuhtai',city:innsbruck},
        {name:'Kundl',city:innsbruck},
        {name:'Ladis',city:innsbruck},
        {name:'Landeck',city:innsbruck},
        {name:'Lanersbach',city:innsbruck},
        {name:'Langen am Arlberg',city:innsbruck},
        {name:'Langenfeld',city:innsbruck},
        {name:'Lans',city:innsbruck},
        {name:'Laterns',city:innsbruck},
        {name:'Lech',city:innsbruck},
        {name:'Lech am Arlberg',city:innsbruck},
        {name:'Leiblfing',city:innsbruck},
        {name:'Leithen',city:innsbruck},
        {name:'Lermoos',city:innsbruck},
        {name:'Leutasch',city:innsbruck},
        {name:'Lienz',city:innsbruck},
        {name:'Lofer',city:innsbruck},
        {name:'Lusens',city:innsbruck},
        {name:'Lustenau',city:innsbruck},
        {name:'Mathon',city:innsbruck},
        {name:'Matrei am Brenner',city:innsbruck},
        {name:'Matrei in Osttirol',city:innsbruck},
        {name:'Maurach',city:innsbruck},
        {name:'Mayrhofen',city:innsbruck},
        {name:'Mellau',city:innsbruck},
        {name:'Mieders',city:innsbruck},
        {name:'Milders',city:innsbruck},
        {name:'Mils bei Imst',city:innsbruck},
        {name:'Mittelberg',city:innsbruck},
        {name:'Mittersill',city:innsbruck},
        {name:'Motz',city:innsbruck},
        {name:'Munster Tirol',city:innsbruck},
        {name:'Mutters',city:innsbruck},
        {name:'Nassereth',city:innsbruck},
        {name:'Natters',city:innsbruck},
        {name:'Nauders',city:innsbruck},
        {name:'Navis',city:innsbruck},
        {name:'Neder',city:innsbruck},
        {name:'Neu Gotzens',city:innsbruck},
        {name:'Neukirchen am Grossvenediger',city:innsbruck},
        {name:'Neustift im Stubaital',city:innsbruck},
        {name:'Niederau',city:innsbruck},
        {name:'Oberau Wildschonau',city:innsbruck},
        {name:'Obergurgl',city:innsbruck},
        {name:'Oberhofen',city:innsbruck},
        {name:'Oberlech',city:innsbruck},
        {name:'Obermieming',city:innsbruck},
        {name:'Obernberg am Brenner',city:innsbruck},
        {name:'Oberperfuss',city:innsbruck},
        {name:'Obladis',city:innsbruck},
        {name:'Obsteig',city:innsbruck},
        {name:'Oetz',city:innsbruck},
        {name:'Omes',city:innsbruck},
        {name:'Partenen',city:innsbruck},
        {name:'Patsch',city:innsbruck},
        {name:'Pertisau',city:innsbruck},
        {name:'Pettnau',city:innsbruck},
        {name:'Pettnau am Arlberg',city:innsbruck},
        {name:'Pfaffenhofen',city:innsbruck},
        {name:'Pfons',city:innsbruck},
        {name:'Pfunds',city:innsbruck},
        {name:'Pians',city:innsbruck},
        {name:'Pill',city:innsbruck},
        {name:'Pitztal',city:innsbruck},
        {name:'Plagne Montalbert',city:innsbruck},
        {name:'Polling',city:innsbruck},
        {name:'Prutz',city:innsbruck},
        {name:'Radfeld',city:innsbruck},
        {name:'Raggal',city:innsbruck},
        {name:'Ramsau im Zillertal',city:innsbruck},
        {name:'Ranggen',city:innsbruck},
        {name:'Rankweil',city:innsbruck},
        {name:'Rans',city:innsbruck},
        {name:'Rattenberg',city:innsbruck},
        {name:'Reith bei Seefeld',city:innsbruck},
        {name:'Reith im Alpbachtal',city:innsbruck},
        {name:'Reutte',city:innsbruck},
        {name:'Ried im Zillertal',city:innsbruck},
        {name:'Rietz',city:innsbruck},
        {name:'Rinn',city:innsbruck},
        {name:'Rotholz',city:innsbruck},
        {name:'Rum',city:innsbruck},
        {name:'Sankt Leonhard im Pitztal',city:innsbruck},
        {name:'Sauttens',city:innsbruck},
        {name:'Scharnitz',city:innsbruck},
        {name:'Schattwald',city:innsbruck},
        {name:'Schlitters',city:innsbruck},
        {name:'Schmirn',city:innsbruck},
        {name:'Schoenberg',city:innsbruck},
        {name:'Schonwies',city:innsbruck},
        {name:'Schrocken',city:innsbruck},
        {name:'Schruns',city:innsbruck},
        {name:'Schwarzenberg',city:innsbruck},
        {name:'Schwaz',city:innsbruck},
        {name:'See im Paznauntal',city:innsbruck},
        {name:'Seefeld in Tirol',city:innsbruck},
        {name:'Sellrain',city:innsbruck},
        {name:'Serfaus',city:innsbruck},
        {name:'Silbertal',city:innsbruck},
        {name:'Sillian',city:innsbruck},
        {name:'Silz',city:innsbruck},
        {name:'Sistrans',city:innsbruck},
        {name:'Solden',city:innsbruck},
        {name:'Soll',city:innsbruck},
        {name:'St Agatha',city:innsbruck},
        {name:'St Anton am Arlberg',city:innsbruck},
        {name:'St Christoph am Arlberg',city:innsbruck},
        {name:'St Gallenkirch',city:innsbruck},
        {name:'St Jakob am Arlberg',city:innsbruck},
        {name:'St Johann in Tirol',city:innsbruck},
        {name:'St Peter in Tirol',city:innsbruck},
        {name:'St Sigmund im Sellrain',city:innsbruck},
        {name:'Stams',city:innsbruck},
        {name:'Stans',city:innsbruck},
        {name:'Stanzach',city:innsbruck},
        {name:'Steeg',city:innsbruck},
        {name:'Steinach am Brenner',city:innsbruck},
        {name:'Strass im Zillertal',city:innsbruck},
        {name:'Strengen am Arlberg',city:innsbruck},
        {name:'Stubaier Gletscher',city:innsbruck},
        {name:'Stuben am Arlberg',city:innsbruck},
        {name:'Stumm',city:innsbruck},
        {name:'Tannheim',city:innsbruck},
        {name:'Tarrenz',city:innsbruck},
        {name:'Telfes',city:innsbruck},
        {name:'Telfs',city:innsbruck},
        {name:'Terfens',city:innsbruck},
        {name:'Thaur',city:innsbruck},
        {name:'Thiersee',city:innsbruck},
        {name:'Trin',city:innsbruck},
        {name:'Tschagguns',city:innsbruck},
        {name:'Tulfes',city:innsbruck},
        {name:'Tumpen',city:innsbruck},
        {name:'Tux',city:innsbruck},
        {name:'Uderns',city:innsbruck},
        {name:'Umhausen',city:innsbruck},
        {name:'Untermieming',city:innsbruck},
        {name:'Vandans',city:innsbruck},
        {name:'Vomperberg',city:innsbruck},
        {name:'Waidring',city:innsbruck},
        {name:'Walchsee',city:innsbruck},
        {name:'Wald im Pinzgau',city:innsbruck},
        {name:'Warth',city:innsbruck},
        {name:'Wattens',city:innsbruck},
        {name:'Weer',city:innsbruck},
        {name:'Weissenmbach Lech',city:innsbruck},
        {name:'Wenns',city:innsbruck},
        {name:'Westendorf',city:innsbruck},
        {name:'Wiesing',city:innsbruck},
        {name:'Wildschonau Oberau',city:innsbruck},
        {name:'Worgl',city:innsbruck},
        {name:'Zams',city:innsbruck},
        {name:'Zell am Ziller',city:innsbruck},
        {name:'Zillertal',city:innsbruck},
        {name:'Zirl',city:innsbruck},
        {name:'Zurs',city:innsbruck},
        {name:'Zwieselstein',city:innsbruck},
        {name:'Klagenfurt Airport', city: klagenfurt},
        {name:'Altenmarkt im Pongau', city: klagenfurt},
        {name:'Katschberg', city: klagenfurt},
        {name:'Bad Kleinkirchheim', city: klagenfurt},
        {name:'Kotschach Mauthen', city: klagenfurt},
        {name:'Maria Worth', city: klagenfurt},
        {name:'Zauchensee', city: klagenfurt},
        {name:'Altenmarkt im Pongau', city: klagenfurt},
        {name:'Annenheim', city: klagenfurt},
        {name:'Arnoldstein', city: klagenfurt},
        {name:'Bad Bleiberg', city: klagenfurt},
        {name:'Bad Kleinkirchheim', city: klagenfurt},
        {name:'Bad St Leonhard im Lavanttal', city: klagenfurt},
        {name:'Bleiburg', city: klagenfurt},
        {name:'Bodensdorf', city: klagenfurt},
        {name:'Dobriach', city: klagenfurt},
        {name:'Drobollach', city: klagenfurt},
        {name:'Ebene Reichenau', city: klagenfurt},
        {name:'Egg am Faaker See', city: klagenfurt},
        {name:'Eisentratten', city: klagenfurt},
        {name:'Faak am See', city: klagenfurt},
        {name:'Falkert', city: klagenfurt},
        {name:'Feistritz ob Bleiburg', city: klagenfurt},
        {name:'Feld am See', city: klagenfurt},
        {name:'Feldkirchen in Karnten', city: klagenfurt},
        {name:'Ferndorf', city: klagenfurt},
        {name:'Finkenstein am Faaker See', city: klagenfurt},
        {name:'Flattach', city: klagenfurt},
        {name:'Frantschach', city: klagenfurt},
        {name:'Fresach', city: klagenfurt},
        {name:'Gerlitzen', city: klagenfurt},
        {name:'Godersdorf', city: klagenfurt},
        {name:'Goldeck', city: klagenfurt},
        {name:'Heiligengeist', city: klagenfurt},
        {name:'Hermagor', city: klagenfurt},
        {name:'Innerkrems', city: klagenfurt},
        {name:'Jenig', city: klagenfurt},
        {name:'Katschberg', city: klagenfurt},
        {name:'Kirchbach', city: klagenfurt},
        {name:'Klagenfurt City Centre', city: klagenfurt},
        {name:'Klippitztorl', city: klagenfurt},
        {name:'Kotschach Mauthen', city: klagenfurt},
        {name:'Krumpendorf', city: klagenfurt},
        {name:'Landskron', city: klagenfurt},
        {name:'Latschach', city: klagenfurt},
        {name:'Ledenitzen', city: klagenfurt},
        {name:'Lendorf', city: klagenfurt},
        {name:'Lieserbrucke', city: klagenfurt},
        {name:'Malta', city: klagenfurt},
        {name:'Maria Worth', city: klagenfurt},
        {name:'Mariahof', city: klagenfurt},
        {name:'Millstatt', city: klagenfurt},
        {name:'Nassfeld', city: klagenfurt},
        {name:'Notsch im Gailtal', city: klagenfurt},
        {name:'Obermillstatt', city: klagenfurt},
        {name:'Obervellach', city: klagenfurt},
        {name:'Ossiach', city: klagenfurt},
        {name:'Patergassen', city: klagenfurt},
        {name:'Portschach am Worthersee', city: klagenfurt},
        {name:'Pressegger See', city: klagenfurt},
        {name:'Radenthein', city: klagenfurt},
        {name:'Ramingstein', city: klagenfurt},
        {name:'Rattendorf', city: klagenfurt},
        {name:'Reifnitz', city: klagenfurt},
        {name:'Rennweg am Katschberg', city: klagenfurt},
        {name:'Sattendorf', city: klagenfurt},
        {name:'Schiefling am See', city: klagenfurt},
        {name:'Seeboden', city: klagenfurt},
        {name:'Spittal an der Drau', city: klagenfurt},
        {name:'St  Michael im Lungau', city: klagenfurt},
        {name:'St Kanzian am Klopeiner See', city: klagenfurt},
        {name:'St Margarethen im Lungau', city: klagenfurt},
        {name:'St Oswald', city: klagenfurt},
        {name:'St Veit', city: klagenfurt},
        {name:'Steindorf am Ossiacher See', city: klagenfurt},
        {name:'Tamsweg', city: klagenfurt},
        {name:'Trebesing', city: klagenfurt},
        {name:'Tropolach', city: klagenfurt},
        {name:'Turracher Hohe', city: klagenfurt},
        {name:'Unzmarkt Frauenburg', city: klagenfurt},
        {name:'Velden am Worther See', city: klagenfurt},
        {name:'Verditz', city: klagenfurt},
        {name:'Villach', city: klagenfurt},
        {name:'Waidegg', city: klagenfurt},
        {name:'Watschig', city: klagenfurt},
        {name:'Zauchensee', city: klagenfurt},
         {name:'Salzburg Airport', city: salzburg},
         {name:'Salzburg Train Station', city: salzburg},
         {name:'Saalbach', city: salzburg},
         {name:'Hinterglemm', city: salzburg},
         {name:'Wagrain', city: salzburg},
         {name:'Flachau', city: salzburg},
         {name:'Bad Gastein', city: salzburg},
         {name:'Zell am See', city: salzburg},
         {name:'Abtenau', city: salzburg},
         {name:'Achensee', city: salzburg},
         {name:'Afritz am See', city: salzburg},
         {name:'Aigen Schlaegl', city: salzburg},
         {name:'Alpendorf', city: salzburg},
         {name:'Altmunster', city: salzburg},
         {name:'Andorf ', city: salzburg},
         {name:'Annaberg im Lammatal', city: salzburg},
         {name:'Ansfelden', city: salzburg},
         {name:'Aschbach Markt', city: salzburg},
         {name:'Aspach', city: salzburg},
         {name:'Asten', city: salzburg},
         {name:'Attersee', city: salzburg},
         {name:'Bachmanning', city: salzburg},
         {name:'Bad Aussee', city: salzburg},
         {name:'Bad Gastein', city: salzburg},
         {name:'Bad Goisern', city: salzburg},
         {name:'Bad Hall', city: salzburg},
         {name:'Bad Hofgastein', city: salzburg},
         {name:'Bad Ischl', city: salzburg},
         {name:'Bad Kreuzen', city: salzburg},
         {name:'Bad Leonfelden', city: salzburg},
         {name:'Bad Mitterndorf', city: salzburg},
         {name:'Bad Schallerbach', city: salzburg},
         {name:'Bad Vigaun', city: salzburg},
         {name:'Baumkirchen', city: salzburg},
         {name:'Bischofshofen', city: salzburg},
         {name:'Blindenmarkt', city: salzburg},
         {name:'Bramberg', city: salzburg},
         {name:'Brand Nagelberg', city: salzburg},
         {name:'Braunau', city: salzburg},
         {name:'Breitenschuetzing', city: salzburg},
         {name:'Bruck an der Grossglocknerstrasse', city: salzburg},
         {name:'Buermoos', city: salzburg},
         {name:'Burghausen', city: salzburg},
         {name:'Dellach', city: salzburg},
         {name:'Deutschlandsberg', city: salzburg},
         {name:'Dienten', city: salzburg},
         {name:'Dolsach', city: salzburg},
         {name:'Donawitz', city: salzburg},
         {name:'Donnersbachwald', city: salzburg},
         {name:'Dorfbeuern', city: salzburg},
         {name:'Dorfgastein', city: salzburg},
         {name:'Ebelsberg', city: salzburg},
         {name:'Eben im Pongau', city: salzburg},
         {name:'Ebenau', city: salzburg},
         {name:'Ebensee', city: salzburg},
         {name:'Eberschwang', city: salzburg},
         {name:'Eferding', city: salzburg},
         {name:'Eggelsberg', city: salzburg},
         {name:'Eisenerz', city: salzburg},
         {name:'Engelhartszell', city: salzburg},
         {name:'Enns', city: salzburg},
         {name:'Eugendorf', city: salzburg},
         {name:'Faistenau', city: salzburg},
         {name:'Felbertauern', city: salzburg},
         {name:'Feldbach', city: salzburg},
         {name:'Ferleiten', city: salzburg},
         {name:'Filzmoos', city: salzburg},
         {name:'Flachau', city: salzburg},
         {name:'Fohnsdorf', city: salzburg},
         {name:'Forstau', city: salzburg},
         {name:'Frankenburg', city: salzburg},
         {name:'Frankenmarkt', city: salzburg},
         {name:'Friedburg', city: salzburg},
         {name:'Fuerstenfeld', city: salzburg},
         {name:'Fusch an der Grossglocknerstrasse', city: salzburg},
         {name:'Fuschl', city: salzburg},
         {name:'Gaishorn', city: salzburg},
         {name:'Gallneukirchen', city: salzburg},
         {name:'Gallspach', city: salzburg},
         {name:'Geretsberg', city: salzburg},
         {name:'Gerlos Pass', city: salzburg},
         {name:'Gmuend', city: salzburg},
         {name:'Gmunden', city: salzburg},
         {name:'Goestling', city: salzburg},
         {name:'Going', city: salzburg},
         {name:'Goldegg', city: salzburg},
         {name:'Golling', city: salzburg},
         {name:'Gosau', city: salzburg},
         {name:'Gossl', city: salzburg},
         {name:'Gostling', city: salzburg},
         {name:'Graukogel', city: salzburg},
         {name:'Greifenburg', city: salzburg},
         {name:'Grein', city: salzburg},
         {name:'Grieskirchen', city: salzburg},
         {name:'Grobming', city: salzburg},
         {name:'Grodig', city: salzburg},
         {name:'Grossarl', city: salzburg},
         {name:'Grossgmain', city: salzburg},
         {name:'Grossraming', city: salzburg},
         {name:'Grossreifling', city: salzburg},
         {name:'Grunau im Almtal', city: salzburg},
         {name:'Grundlsee', city: salzburg},
         {name:'Gundertshausen', city: salzburg},
         {name:'Gunskirchen', city: salzburg},
         {name:'Haag am Hausruck', city: salzburg},
         {name:'Hagen Lofer', city: salzburg},
         {name:'Hallein', city: salzburg},
         {name:'Hallstatt', city: salzburg},
         {name:'Haus im Ennstal', city: salzburg},
         {name:'Hinterglemm', city: salzburg},
         {name:'Hinterstoder', city: salzburg},
         {name:'Hof bei Salzburg ', city: salzburg},
         {name:'Hohentauren', city: salzburg},
         {name:'Holzoster', city: salzburg},
         {name:'Huettschlag', city: salzburg},
         {name:'Irdning', city: salzburg},
         {name:'Jochberg', city: salzburg},
         {name:'Kals am Grossglockner', city: salzburg},
         {name:'Kaprun', city: salzburg},
         {name:'Kirchdorf an der Krems', city: salzburg},
         {name:'Kirchdorf in Tirol', city: salzburg},
         {name:'Kitzbuehel', city: salzburg},
         {name:'Klagenfurt', city: salzburg},
         {name:'Kleinarl', city: salzburg},
         {name:'Knittelfeld', city: salzburg},
         {name:'Koenigswiesen', city: salzburg},
         {name:'Koppl', city: salzburg},
         {name:'Kostendorf', city: salzburg},
         {name:'Kuchl', city: salzburg},
         {name:'Laakirchen', city: salzburg},
         {name:'Lambach', city: salzburg},
         {name:'Lammertal', city: salzburg},
         {name:'Lamprechtshausen', city: salzburg},
         {name:'Lenzing', city: salzburg},
         {name:'Leoben', city: salzburg},
         {name:'Leogang', city: salzburg},
         {name:'Lessach', city: salzburg},
         {name:'Liezen', city: salzburg},
         {name:'Linz ', city: salzburg},
         {name:'Lohnsburg', city: salzburg},
         {name:'Maishofen', city: salzburg},
         {name:'Mallnitz', city: salzburg},
         {name:'Mandling', city: salzburg},
         {name:'Manning', city: salzburg},
         {name:'Marchtrenk', city: salzburg},
         {name:'Maria Alm', city: salzburg},
         {name:'Mariapfarr', city: salzburg},
         {name:'Mattighofen', city: salzburg},
         {name:'Mattsee', city: salzburg},
         {name:'Mauerkirchen', city: salzburg},
         {name:'Mauterndorf', city: salzburg},
         {name:'Mauthausen', city: salzburg},
         {name:'Mettmach', city: salzburg},
         {name:'Michaelbeuern', city: salzburg},
         {name:'Micheldorf', city: salzburg},
         {name:'Mondsee', city: salzburg},
         {name:'Moosdorf', city: salzburg},
         {name:'Muenzkirchen', city: salzburg},
         {name:'Muhlbach am Hochkonig', city: salzburg},
         {name:'Munderfing', city: salzburg},
         {name:'Murau', city: salzburg},
         {name:'Neumarkt am Wallersee', city: salzburg},
         {name:'Niederalm', city: salzburg},
         {name:'Niederndorf', city: salzburg},
         {name:'Niedernsill', city: salzburg},
         {name:'Nussdorf am Attersee', city: salzburg},
         {name:'Nussdorf am Haunsberg', city: salzburg},
         {name:'Obernberg am Inn', city: salzburg},
         {name:'Oberndorf bei Salzburg', city: salzburg},
         {name:'Oberndorf in Tirol', city: salzburg},
         {name:'Obertauern', city: salzburg},
         {name:'Obertilliach', city: salzburg},
         {name:'Obertraun', city: salzburg},
         {name:'Obertrum', city: salzburg},
         {name:'Offenhausen', city: salzburg},
         {name:'Ostermiething', city: salzburg},
         {name:'Ottensheim', city: salzburg},
         {name:'Perg', city: salzburg},
         {name:'Pertisau am Achensee', city: salzburg},
         {name:'Pettneu am Arlberg', city: salzburg},
         {name:'Peuerbach', city: salzburg},
         {name:'Pfarrkirchen', city: salzburg},
         {name:'Piesendorf', city: salzburg},
         {name:'Pinzgau', city: salzburg},
         {name:'Postalm', city: salzburg},
         {name:'Pramet', city: salzburg},
         {name:'Pregarten', city: salzburg},
         {name:'Prien am Chiemsee', city: salzburg},
         {name:'Pruggern', city: salzburg},
         {name:'Puch bei Hallein', city: salzburg},
         {name:'Radstadt', city: salzburg},
         {name:'Ramsau am Dachstein', city: salzburg},
         {name:'Rauris', city: salzburg},
         {name:'Reith', city: salzburg},
         {name:'Rennweg', city: salzburg},
         {name:'Ried im Innkreis', city: salzburg},
         {name:'Riedau', city: salzburg},
         {name:'Rohrbach in Oberosterreich', city: salzburg},
         {name:'Rohrmoos', city: salzburg},
         {name:'Rossbach', city: salzburg},
         {name:'Russbach', city: salzburg},
         {name:'Saalbach', city: salzburg},
         {name:'Saalfelden', city: salzburg},
         {name:'Salzburg City Centre', city: salzburg},
         {name:'Schaerding', city: salzburg},
         {name:'Scheffau am Wilden Kaiser', city: salzburg},
         {name:'Scheibbs', city: salzburg},
         {name:'Schladming', city: salzburg},
         {name:'Schlagl', city: salzburg},
         {name:'Schmieden', city: salzburg},
         {name:'Schneegattern', city: salzburg},
         {name:'Schorfling', city: salzburg},
         {name:'Schwanenstadt', city: salzburg},
         {name:'Schwertberg', city: salzburg},
         {name:'Seefeld', city: salzburg},
         {name:'Seeham', city: salzburg},
         {name:'Seekirchen', city: salzburg},
         {name:'Seewalchen', city: salzburg},
         {name:'Sierning', city: salzburg},
         {name:'Spital am Pyhrn', city: salzburg},
         {name:'Sportgastein', city: salzburg},
         {name:'St Aegydi', city: salzburg},
         {name:'St Gilgen ', city: salzburg},
         {name:'St Johann im Pongau', city: salzburg},
         {name:'St Lorenz', city: salzburg},
         {name:'St Martin bei Lofer', city: salzburg},
         {name:'St Martin im Innkreis', city: salzburg},
         {name:'St Michael im Lungau', city: salzburg},
         {name:'St Ulrich am Pillersee', city: salzburg},
         {name:'St Wolfgang', city: salzburg},
         {name:'Steinbach am Attersee', city: salzburg},
         {name:'Steyr', city: salzburg},
         {name:'Steyregg', city: salzburg},
         {name:'Strasswalchen', city: salzburg},
         {name:'Strobl', city: salzburg},
         {name:'Suben', city: salzburg},
         {name:'Sulzau', city: salzburg},
         {name:'Taiskirchen', city: salzburg},
         {name:'Tamsweg', city: salzburg},
         {name:'Tarsdorf', city: salzburg},
         {name:'Tauplitz', city: salzburg},
         {name:'Taxenbach', city: salzburg},
         {name:'Ternberg', city: salzburg},
         {name:'Thalgau', city: salzburg},
         {name:'Timmelkam', city: salzburg},
         {name:'Traun', city: salzburg},
         {name:'Traunkirchen', city: salzburg},
         {name:'Trimmelkam', city: salzburg},
         {name:'Turracherhohe', city: salzburg},
         {name:'Ulrichsberg', city: salzburg},
         {name:'Unken', city: salzburg},
         {name:'Unterach am Attersee', city: salzburg},
         {name:'Untertauern', city: salzburg},
         {name:'Uttendorf', city: salzburg},
         {name:'Viehhofen', city: salzburg},
         {name:'Vocklabruck', city: salzburg},
         {name:'Vocklamarkt', city: salzburg},
         {name:'Voitsberg', city: salzburg},
         {name:'Volkermarkt', city: salzburg},
         {name:'Vorchdorf', city: salzburg},
         {name:'Wagrain', city: salzburg},
         {name:'Waidhofen an der Thaya', city: salzburg},
         {name:'Waizenkirchen', city: salzburg},
         {name:'Waldzell', city: salzburg},
         {name:'Weissbach bei Lofer', city: salzburg},
         {name:'Wels', city: salzburg},
         {name:'Werfen', city: salzburg},
         {name:'Werfenweng', city: salzburg},
         {name:'Windischgarsten', city: salzburg},
         {name:'Wolfsberg', city: salzburg},
         {name:'Worschach', city: salzburg},
         {name:'Zell am Moos', city: salzburg},
         {name:'Zell am See', city: salzburg},
         {name:'Zell an der Pram', city: salzburg},
         {name:'Zinkenbach', city: salzburg},
          {name:'Vienna Airport', city: vienna},
          {name:'Vienna Train Station', city: vienna},
          {name:'Vienna City Centre', city: vienna},
          {name:'Wiener Neustadt', city: vienna},
          {name:'Hopfgarten', city: vienna},
          {name:'Kohfidisch', city: vienna},
          {name:'Neustift', city: vienna},
          {name:'Krems', city: vienna},
          {name:'Aderklaa', city: vienna},
          {name:'Aflenz Kurort', city: vienna},
          {name:'Amstetten', city: vienna},
          {name:'Annaberg', city: vienna},
          {name:'Bad Radkersburg', city: vienna},
          {name:'Baden', city: vienna},
          {name:'Berndorf', city: vienna},
          {name:'Bisamberg', city: vienna},
          {name:'Breitenfurt', city: vienna},
          {name:'Bruck an der Leitha', city: vienna},
          {name:'Bruck an der Mur', city: vienna},
          {name:'Brunn am Gebirge', city: vienna},
          {name:'Deutsch Wagram', city: vienna},
          {name:'Eisenstadt', city: vienna},
          {name:'Freistadt', city: vienna},
          {name:'Furstenfeld', city: vienna},
          {name:'Gablitz', city: vienna},
          {name:'Gaenserndorf', city: vienna},
          {name:'Gerasdorf', city: vienna},
          {name:'Gmund', city: vienna},
          {name:'Goriach', city: vienna},
          {name:'Graz', city: vienna},
          {name:'Gross Enzersdorf', city: vienna},
          {name:'Guessing', city: vienna},
          {name:'Guntramsdorf', city: vienna},
          {name:'Gussing', city: vienna},
          {name:'Hagenbrunn', city: vienna},
          {name:'Hainburg', city: vienna},
          {name:'Hainburg an der Donau', city: vienna},
          {name:'Himberg', city: vienna},
          {name:'Hinterbruhl', city: vienna},
          {name:'Hollabrunn', city: vienna},
          {name:'Hopfgarten', city: vienna},
          {name:'Jennersdorf', city: vienna},
          {name:'Kirchberg am Wechsel', city: vienna},
          {name:'Klosterneuburg', city: vienna},
          {name:'Kohfidisch', city: vienna},
          {name:'Korneuburg', city: vienna},
          {name:'Krems', city: vienna},
          {name:'Lackenhof', city: vienna},
          {name:'Langenzersdorf', city: vienna},
          {name:'Leopoldsdorf', city: vienna},
          {name:'Liesing', city: vienna},
          {name:'Lilienfeld', city: vienna},
          {name:'Mattersburg', city: vienna},
          {name:'Mauerbach', city: vienna},
          {name:'Melk', city: vienna},
          {name:'Mistelbach', city: vienna},
          {name:'Modling', city: vienna},
          {name:'Muerzzuschlag', city: vienna},
          {name:'Munchendorf', city: vienna},
          {name:'Neusiedl am See', city: vienna},
          {name:'Neustift', city: vienna},
          {name:'Oberpullendorf', city: vienna},
          {name:'Oberwart', city: vienna},
          {name:'Parndorf', city: vienna},
          {name:'Perchtoldsdorf', city: vienna},
          {name:'Pressbaum', city: vienna},
          {name:'Purkersdorf', city: vienna},
          {name:'Raasdorf', city: vienna},
          {name:'Rust Austria', city: vienna},
          {name:'Schwechat', city: vienna},
          {name:'Semmering', city: vienna},
          {name:'Spitz', city: vienna},
          {name:'St Polten', city: vienna},
          {name:'Stockerau', city: vienna},
          {name:'Tulln', city: vienna},
          {name:'Vienna City Centre', city: vienna},
          {name:'Waidhofen An Der Ybbs', city: vienna},
          {name:'Weidling', city: vienna},
          {name:'Weiz', city: vienna},
          {name:'Wiener Neudorf', city: vienna},
          {name:'Wiener Neustadt', city: vienna},
          {name:'Wolfsgraben', city: vienna},
          {name:'Zwettl', city: vienna}
          ])


  # Cities of Portugal
  beja = City.find_by(name: 'Beja')
  faro = City.find_by(name: 'Faro')
  funchal = City.find_by(name: 'Funchal')
  lisbon = City.find_by(name: 'Lisbon')
  porto = City.find_by(name: 'Porto')
  PickUpLocation.create([
          {name:'Beja Airport',city: beja},
          {name:'Beja City Centre',city: beja},
          {name:'Almeirim',city: beja},
          {name:'Amieira',city: beja},
          {name:'Elvas',city: beja},
          {name:'Esporao',city: beja},
          {name:'Estremoz',city: beja},
          {name:'Almeirim',city: beja},
          {name:'Amieira',city: beja},
          {name:'Beja City Centre',city: beja},
          {name:'Elvas',city: beja},
          {name:'Esporao',city: beja},
          {name:'Estremoz',city: beja},
          {name:'Manta Rota',city: beja},
          {name:'Odemira',city: beja},
          {name:'Olhos de Agua',city: beja},
          {name:'Portalegre',city: beja},
          {name:'Reguengos de Monsaraz',city: beja},
          {name:'Serra da Estrela',city: beja},
          {name:'Faro Airport', city: faro},
          {name:'Albufeira', city: faro},
          {name:'Vilamoura', city: faro},
          {name:'Praia da Luz', city: faro},
          {name:'Alvor', city: faro},
          {name:'Quarteira', city: faro},
          {name:'Carvoeiro', city: faro},
          {name:'Acoteias', city: faro},
          {name:'Albufeira', city: faro},
          {name:'Alcantarilha', city: faro},
          {name:'Alcoutim', city: faro},
          {name:'Alfontes', city: faro},
          {name:'Algoz', city: faro},
          {name:'Aljezur', city: faro},
          {name:'Almadena', city: faro},
          {name:'Almancil', city: faro},
          {name:'Altura', city: faro},
          {name:'Alvor', city: faro},
          {name:'Areias de Sao Joao', city: faro},
          {name:'Armacao de Pera', city: faro},
          {name:'Ayamonte', city: faro},
          {name:'Balaia Golf Resort', city: faro},
          {name:'Boliqueime', city: faro},
          {name:'Bordeira', city: faro},
          {name:'Budens', city: faro},
          {name:'Burgau', city: faro},
          {name:'Cabanas de Tavira', city: faro},
          {name:'Carrapateira', city: faro},
          {name:'Carvoeiro', city: faro},
          {name:'Castro Marim', city: faro},
          {name:'El Rompido', city: faro},
          {name:'Estoi', city: faro},
          {name:'Falesia', city: faro},
          {name:'Faro City Centre', city: faro},
          {name:'Ferragudo', city: faro},
          {name:'Fuseta', city: faro},
          {name:'Gale', city: faro},
          {name:'Guia', city: faro},
          {name:'Isla Antilla', city: faro},
          {name:'Isla Canela', city: faro},
          {name:'Isla Critina', city: faro},
          {name:'Lagoa', city: faro},
          {name:'Lepe', city: faro},
          {name:'Loule', city: faro},
          {name:'Matalascanas', city: faro},
          {name:'Meia Praia', city: faro},
          {name:'Moncarapacho', city: faro},
          {name:'Monchique', city: faro},
          {name:'Monte Gordo', city: faro},
          {name:'Montechoro', city: faro},
          {name:'Montenegro', city: faro},
          {name:'Olhao', city: faro},
          {name:'Paderne', city: faro},
          {name:'Pechao', city: faro},
          {name:'Pedras Del Rei', city: faro},
          {name:'Penina', city: faro},
          {name:'Porches', city: faro},
          {name:'Praia da Falesia', city: faro},
          {name:'Praia da Luz', city: faro},
          {name:'Praia da Oura', city: faro},
          {name:'Praia da Rocha', city: faro},
          {name:'Praia do Vau', city: faro},
          {name:'Punta Umbria', city: faro},
          {name:'Quarteira', city: faro},
          {name:'Quinta do Lago', city: faro},
          {name:'Rocha Brava Resort', city: faro},
          {name:'Sagres', city: faro},
          {name:'Salema', city: faro},
          {name:'Santa Barbara de Nexe', city: faro},
          {name:'Santa Eulalia', city: faro},
          {name:'Santa Luzia', city: faro},
          {name:'Sao Bras de Alportel', city: faro},
          {name:'Sao Rafael', city: faro},
          {name:'Sesmarias', city: faro},
          {name:'Silves', city: faro},
          {name:'Tavira', city: faro},
          {name:'Vale Carros', city: faro},
          {name:'Vale Garrao', city: faro},
          {name:'Vale Parra', city: faro},
          {name:'Vale do Lobo', city: faro},
          {name:'Vila Real De Santo Antonio', city: faro},
          {name:'Vilamoura', city: faro},
          {name:'Madeira Funchal Airport', city: funchal},
          {name:'Funchal City Centre', city: funchal},
          {name:'Santa Cruz Funchal', city: funchal},
          {name:'Machico', city: funchal},
          {name:'Canico', city: funchal},
          {name:'Ribeira Brava', city: funchal},
          {name:'Calheta', city: funchal},
          {name:'Boaventura', city: funchal},
          {name:'Calheta', city: funchal},
          {name:'Camara de Lobos', city: funchal},
          {name:'Canico', city: funchal},
          {name:'Choupana Hills Resort', city: funchal},
          {name:'Encumeada', city: funchal},
          {name:'Funchal City Centre', city: funchal},
          {name:'Jardim da Serra', city: funchal},
          {name:'Machico', city: funchal},
          {name:'Ponta Delgada', city: funchal},
          {name:'Ponta do Pargo', city: funchal},
          {name:'Ponta do Sol', city: funchal},
          {name:'Porto Moniz', city: funchal},
          {name:'Porto da Cruz', city: funchal},
          {name:'Ribeira Brava', city: funchal},
          {name:'Santa Cruz Funchal', city: funchal},
          {name:'Santana', city: funchal},
          {name:'Santo da Serra', city: funchal},
          {name:'Sao Jorge', city: funchal},
          {name:'Sao Vicente', city: funchal},
          {name:'Lisbon Airport', city: lisbon},
          {name:'Belem Cruise Port', city: lisbon},
          {name:'Lisbon Cruise Port', city: lisbon},
          {name:'Lisbon Train Station', city: lisbon},
          {name:'Lisbon City Centre', city: lisbon},
          {name:'Cascais', city: lisbon},
          {name:'Lagos', city: lisbon},
          {name:'Estoril', city: lisbon},
          {name:'Sintra', city: lisbon},
          {name:'Fatima', city: lisbon},
          {name:'Alcobaca', city: lisbon},
          {name:'Alcochete', city: lisbon},
          {name:'Algarve', city: lisbon},
          {name:'Azinhaga', city: lisbon},
          {name:'Batalha', city: lisbon},
          {name:'Bombarral', city: lisbon},
          {name:'Caldas da Rainha', city: lisbon},
          {name:'Caparica', city: lisbon},
          {name:'Cascais', city: lisbon},
          {name:'Castelo Branco', city: lisbon},
          {name:'Charneca da Caparica', city: lisbon},
          {name:'Coimbra', city: lisbon},
          {name:'Colares', city: lisbon},
          {name:'Costa da Caparica', city: lisbon},
          {name:'Ericeira', city: lisbon},
          {name:'Estoril', city: lisbon},
          {name:'Evora', city: lisbon},
          {name:'Fatima', city: lisbon},
          {name:'Figueira da Foz', city: lisbon},
          {name:'Foros de Salvaterra', city: lisbon},
          {name:'Foz do Arelho', city: lisbon},
          {name:'Fundao', city: lisbon},
          {name:'Gradil', city: lisbon},
          {name:'Guincho', city: lisbon},
          {name:'Lagos', city: lisbon},
          {name:'Leiria', city: lisbon},
          {name:'Lisbon City Centre', city: lisbon},
          {name:'Luso', city: lisbon},
          {name:'Mafra', city: lisbon},
          {name:'Marinha Grande', city: lisbon},
          {name:'Mindelo', city: lisbon},
          {name:'Miraflores', city: lisbon},
          {name:'Montijo', city: lisbon},
          {name:'Nazare', city: lisbon},
          {name:'Obidos', city: lisbon},
          {name:'Oeiras', city: lisbon},
          {name:'Paco de Arcos', city: lisbon},
          {name:'Palmela', city: lisbon},
          {name:'Penha Longa Golf Resort', city: lisbon},
          {name:'Peniche', city: lisbon},
          {name:'Portimao', city: lisbon},
          {name:'Praia Grande', city: lisbon},
          {name:'Praia del Rey', city: lisbon},
          {name:'Private tour of Lisbon', city: lisbon},
          {name:'Queijas', city: lisbon},
          {name:'Queluz', city: lisbon},
          {name:'Salir do Porto', city: lisbon},
          {name:'Santa Cruz', city: lisbon},
          {name:'Santa Iria da Azoia', city: lisbon},
          {name:'Santa Maria de Belem', city: lisbon},
          {name:'Santarem', city: lisbon},
          {name:'Santiago de Cacem', city: lisbon},
          {name:'Santo Estevao', city: lisbon},
          {name:'Sao Martinho do Porto', city: lisbon},
          {name:'Seixal', city: lisbon},
          {name:'Sesimbra', city: lisbon},
          {name:'Setubal', city: lisbon},
          {name:'Sevilha', city: lisbon},
          {name:'Sines', city: lisbon},
          {name:'Sintra', city: lisbon},
          {name:'Sintra Private Tour', city: lisbon},
          {name:'Tomar', city: lisbon},
          {name:'Torres Vedras', city: lisbon},
          {name:'Troia by Ferry', city: lisbon},
          {name:'Troia by road', city: lisbon},
          {name:'Turcifal', city: lisbon},
          {name:'Vieira de Leiria', city: lisbon},
          {name:'Vila do Bispo', city: lisbon},
          {name:'Villa Nova de Milfontes', city: lisbon},
          {name:'Porto Airport', city: porto},
          {name:'Porto Cruise Port', city: porto},
          {name:'Porto City Centre', city: porto},
          {name:'Vila Nova de Gaia', city: porto},
          {name:'Aveiro', city: porto},
          {name:'Esposende', city: porto},
          {name:'Braga', city: porto},
          {name:'Viseu', city: porto},
          {name:'Amarante', city: porto},
          {name:'Arcos de Valdevez', city: porto},
          {name:'Aveiro', city: porto},
          {name:'Baiona', city: porto},
          {name:'Barcelos', city: porto},
          {name:'Braga', city: porto},
          {name:'Braganca', city: porto},
          {name:'Bussaco', city: porto},
          {name:'Chaves', city: porto},
          {name:'Espinho', city: porto},
          {name:'Esposende', city: porto},
          {name:'Estarreja', city: porto},
          {name:'Europarque', city: porto},
          {name:'Guarda', city: porto},
          {name:'Guimaraes', city: porto},
          {name:'Lamego', city: porto},
          {name:'Mirandela', city: porto},
          {name:'Moncao', city: porto},
          {name:'Oliveira de Azemeis', city: porto},
          {name:'Ovar', city: porto},
          {name:'Pacos de Ferreira', city: porto},
          {name:'Paredes de Coura', city: porto},
          {name:'Penafiel', city: porto},
          {name:'Peso da Regua', city: porto},
          {name:'Pinhao', city: porto},
          {name:'Ponte da Barca', city: porto},
          {name:'Ponte de Lima', city: porto},
          {name:'Porto City Centre', city: porto},
          {name:'Povoa de Varzim', city: porto},
          {name:'Santa Maria da Feira', city: porto},
          {name:'Santo Tirso', city: porto},
          {name:'Sao Joao da Madeira', city: porto},
          {name:'Tui', city: porto},
          {name:'Valenca do Minho', city: porto},
          {name:'Viana do Castelo', city: porto},
          {name:'Vidago', city: porto},
          {name:'Vila Nova de Gaia', city: porto},
          {name:'Vila Real', city: porto},
          {name:'Vila do Conde', city: porto},
          {name:'Viseu', city: porto}
        ])

end