after :cities, :agencies do

  alamo_subsidiaries =  Subsidiary.create([
                                              {name:'Innsbruck Airport Station', address:'Innsbruck Street 1', city:City.find(1), agency: Agency.find(1)},
                                              {name:'Vienna Station', address:' Street 1', city:City.find(4), agency: Agency.find(1)},
                                              {name:'Brussels Station', address:' Street 1', city:City.find(7), agency: Agency.find(1)},
                                              {name:'Stugartt Station', address:' Street 1', city:City.find(65), agency: Agency.find(1)},
                                              {name:'Klagenfurt Station', address:' Street 1', city:City.find(2), agency: Agency.find(1)},
                                              {name:'Metz Station', address:' Street 4', city:City.find(43), agency: Agency.find(1)},
                                              {name:'Salzburg Station', address:' Street 1', city:City.find(3), agency: Agency.find(1)},
                                              {name:'Plovdiv Station', address:' Street 1', city:City.find(9), agency: Agency.find(1)},
                                              {name:'Dubrovnik Station', address:' Street 1', city:City.find(12), agency: Agency.find(1)},
                                              {name:'Helsinki Station', address:' Street 16', city:City.find(34), agency: Agency.find(1)},
                                              {name:'Burgas Station', address:' Street 1', city:City.find(8), agency: Agency.find(1)},
                                              {name:'Treviso Station', address:' Street 81', city:City.find(98), agency: Agency.find(1)},
                                              {name:'Funchal Station', address:' Street 1', city:City.find(123), agency: Agency.find(1)},
                                              {name:'Nancy Station', address:' Street 1', city:City.find(45), agency: Agency.find(1)},
                                              {name:'Eindhoven Station', address:' Street 1', city:City.find(111), agency: Agency.find(1)},
                                              {name:'Genoa Station', address:' Street 1', city:City.find(87), agency: Agency.find(1)},
                                              {name:'Nice Station', address:' Street 1', city:City.find(46), agency: Agency.find(1)},
                                              {name:'Grenoble Station', address:' Street 7', city:City.find(40), agency: Agency.find(1)},
                                              {name:'Budapest Station', address:' Street 1', city:City.find(76), agency: Agency.find(1)},
                                              {name:'Trapani Station', address:' Street 1', city:City.find(97), agency: Agency.find(1)},
                                              {name:'Ancona Station', address:' Street 1', city:City.find(78), agency: Agency.find(1)},
                                              {name:'Rijeka Station', address:' Street 1', city:City.find(15), agency: Agency.find(1)},
                                              {name:'Zagreb Station', address:' Street 5', city:City.find(18), agency: Agency.find(1)},
                                              {name:'Toulouse Station', address:' Street 1', city:City.find(53), agency: Agency.find(1)},
                                              {name:'Zurich Station', address:' Street 14', city:City.find(156), agency: Agency.find(1)},
                                              {name:'Bled Station', address:' Street 1', city:City.find(134), agency: Agency.find(1)},
                                              {name:'Timisoara Station', address:' Street 31', city:City.find(129), agency: Agency.find(1)},
                                              {name:'London', address:' Street 1', city:City.find(168), agency: Agency.find(1)}
                                          ])
  avis_subsidiaries =  Subsidiary.create([

                                             {name:'Plovdiv Station', address:' Street 1', city:City.find(9), agency: Agency.find(2)},
                                             {name:'Sofia Station', address:' Street 1', city:City.find(10), agency: Agency.find(2)},
                                             {name:'Varna Station', address:' Street 1', city:City.find(11), agency: Agency.find(2)},
                                             {name:'Osijek Station', address:' Street 1', city:City.find(13), agency: Agency.find(2)},
                                             {name:'Rijeka Station', address:' Street 1', city:City.find(15), agency: Agency.find(2)},
                                             {name:'Zagreb Station', address:' Street 1', city:City.find(18), agency: Agency.find(2)},
                                             {name:'Larnaca Station', address:' Street 1', city:City.find(19), agency: Agency.find(2)},
                                             {name:'Paphos Station', address:' Street 1', city:City.find(21), agency: Agency.find(2)},
                                             {name:'Dabaa Station', address:' Street 1', city:City.find(26), agency: Agency.find(2)},
                                             {name:'Hurghada Station', address:' Street 1', city:City.find(27), agency: Agency.find(2)},
                                             {name:'Marsa AlamStation', address:' Street 1', city:City.find(29), agency: Agency.find(2)},
                                             {name:'Sharm El Sheikh Station', address:' Street 1', city:City.find(30), agency: Agency.find(2)},
                                             {name:'Montpellier Station', address:' Street 1', city:City.find(44), agency: Agency.find(2)},
                                             {name:'Nice Station', address:' Street 1', city:City.find(46), agency: Agency.find(2)},
                                             {name:'Paris Station', address:' Street 1', city:City.find(47), agency: Agency.find(2)},
                                             {name:'Pau Station', address:' Street 1', city:City.find(48), agency: Agency.find(2)},
                                             {name:'Strasbourg Station', address:' Street 1', city:City.find(50), agency: Agency.find(2)},
                                             {name:'Toulon Station', address:' Street 1', city:City.find(52), agency: Agency.find(2)},
                                             {name:'Berlin Station', address:' Street 1', city:City.find(54), agency: Agency.find(2)},
                                             {name:'Bremen Station', address:' Street 1', city:City.find(55), agency: Agency.find(2)},
                                             {name:'Dusseldorf Station', address:' Street 1', city:City.find(57), agency: Agency.find(2)},
                                             {name:'Friedrichshafen Station', address:' Street 1', city:City.find(59), agency: Agency.find(2)},
                                             {name:'Hamburg Station', address:' Street 1', city:City.find(60), agency: Agency.find(2)},
                                             {name:'Stuttgart Station', address:' Street 1', city:City.find(65), agency: Agency.find(2)},
                                             {name:'Naxos Station', address:' Street 1', city:City.find(70), agency: Agency.find(2)},
                                             {name:'Thessaloniki Station', address:' Street 1', city:City.find(74), agency: Agency.find(2)},
                                             {name:'Zakynthos Station', address:' Street 1', city:City.find(75), agency: Agency.find(2)},
                                             {name:'Alghero Station', address:' Street 1', city:City.find(77), agency: Agency.find(2)},
                                             {name:'Ancona Station', address:' Street 1', city:City.find(78), agency: Agency.find(2)},
                                             {name:'Florence Station', address:' Street 1', city:City.find(85), agency: Agency.find(2)},
                                             {name:'Genoa Station', address:' Street 1', city:City.find(87), agency: Agency.find(2)},
                                             {name:'Lamezia Terme Station', address:' Street 1', city:City.find(88), agency: Agency.find(2)},
                                             {name:'Milan Station', address:' Street 1', city:City.find(89), agency: Agency.find(2)},
                                             {name:'Olbia Station', address:' Street 1', city:City.find(91), agency: Agency.find(2)},
                                             {name:'Palermo Station', address:' Street 1', city:City.find(92), agency: Agency.find(2)},
                                             {name:'Pisa Station', address:' Street 1', city:City.find(94), agency: Agency.find(2)},
                                             {name:'Rimini Station', address:' Street 1', city:City.find(95), agency: Agency.find(2)},
                                             {name:'Trapani Station', address:' Street 1', city:City.find(97), agency: Agency.find(2)},
                                             {name:'Trieste Station', address:' Street 1', city:City.find(99), agency: Agency.find(2)},
                                             {name:'Turin Station', address:' Street 1', city:City.find(100), agency: Agency.find(2)},
                                             {name:'Venice Station', address:' Street 1', city:City.find(101), agency: Agency.find(2)},
                                             {name:'Eindhoven Station', address:' Street 1', city:City.find(111), agency: Agency.find(2)},
                                             {name:'Katowice Station', address:' Street 1', city:City.find(116), agency: Agency.find(2)},
                                             {name:'Krakow Station', address:' Street 1', city:City.find(117), agency: Agency.find(2)},
                                             {name:'Warsaw Station', address:' Street 1', city:City.find(119), agency: Agency.find(2)},
                                             {name:'Funchal Station', address:' Street 1', city:City.find(123), agency: Agency.find(2)},
                                             {name:'Lisbon Station', address:' Street 1', city:City.find(124), agency: Agency.find(2)},
                                             {name:'Porto Station', address:' Street 1', city:City.find(125), agency: Agency.find(2)},
                                             {name:'Bucharest Station', address:' Street 1', city:City.find(126), agency: Agency.find(2)},
                                             {name:'Cluj Napoca Station', address:' Street 1', city:City.find(127), agency: Agency.find(2)},
                                             {name:'Bratislava Station', address:' Street 1', city:City.find(133), agency: Agency.find(2)},
                                             {name:'Ljubljana Station', address:' Street 1', city:City.find(135), agency: Agency.find(2)},
                                             {name:'Portoroz Station', address:' Street 1', city:City.find(136), agency: Agency.find(2)},
                                             {name:'Almeria Station', address:' Street 1', city:City.find(138), agency: Agency.find(2)},
                                             {name:'Barcelona Station', address:' Street 1', city:City.find(139), agency: Agency.find(2)},
                                             {name:'Madrid Station', address:' Street 1', city:City.find(143), agency: Agency.find(2)},
                                             {name:'Tenerife Station', address:' Street 1', city:City.find(149), agency: Agency.find(2)},
                                             {name:'Valencia Station', address:' Street 1', city:City.find(150), agency: Agency.find(2)},
                                             {name:'Lugano Station', address:' Street 1', city:City.find(154), agency: Agency.find(2)},
                                             {name:'Zurich Station', address:' Street 1', city:City.find(156), agency: Agency.find(2)},
                                             {name:'Ankara Station', address:' Street 1', city:City.find(157), agency: Agency.find(2)},
                                             {name:'Antalya Station', address:' Street 1', city:City.find(158), agency: Agency.find(2)},
                                             {name:'Samsun Station', address:' Street 1', city:City.find(163), agency: Agency.find(2)},
                                             {name:'Bristol Station', address:' Street 1', city:City.find(165), agency: Agency.find(2)},
                                             {name:'Glasgow Station', address:' Street 1', city:City.find(167), agency: Agency.find(2)},
                                             {name:'London Station', address:' Street 1', city:City.find(168), agency: Agency.find(2)},
                                             {name:'Manchester Station', address:' Street 1', city:City.find(169), agency: Agency.find(2)}
                                         ])
  budget_subsidiaries = Subsidiary.create([
                                              {name:'	Sofia	Station', address:' Street 1', city:City.find(			10	), agency: Agency.find(3)},
                                              {name:'	Varna	Station', address:' Street 1', city:City.find(			11	), agency: Agency.find(3)},
                                              {name:'	Dubrovnik	Station', address:' Street 1', city:City.find(			12	), agency: Agency.find(3)},
                                              {name:'	Osijek	Station', address:' Street 1', city:City.find(			13	), agency: Agency.find(3)},
                                              {name:'	Pula	Station', address:' Street 1', city:City.find(			14	), agency: Agency.find(3)},
                                              {name:'	Rijeka	Station', address:' Street 1', city:City.find(			15	), agency: Agency.find(3)},
                                              {name:'	Prague	Station', address:' Street 1', city:City.find(			22	), agency: Agency.find(3)},
                                              {name:'	Alexandria	Station', address:' Street 1', city:City.find(			23	), agency: Agency.find(3)},
                                              {name:'	Hurghada	Station', address:' Street 1', city:City.find(			27	), agency: Agency.find(3)},
                                              {name:'	Luxor	Station', address:' Street 1', city:City.find(			28	), agency: Agency.find(3)},
                                              {name:'	Tartu	Station', address:' Street 1', city:City.find(			33	), agency: Agency.find(3)},
                                              {name:'	Helsinki	Station', address:' Street 1', city:City.find(			34	), agency: Agency.find(3)},
                                              {name:'	Annecy	Station', address:' Street 1', city:City.find(			35	), agency: Agency.find(3)},
                                              {name:'	Marseille	Station', address:' Street 1', city:City.find(			42	), agency: Agency.find(3)},
                                              {name:'	Metz	Station', address:' Street 1', city:City.find(			43	), agency: Agency.find(3)},
                                              {name:'	Montpellier	Station', address:' Street 1', city:City.find(			44	), agency: Agency.find(3)},
                                              {name:'	Nancy	Station', address:' Street 1', city:City.find(			45	), agency: Agency.find(3)},
                                              {name:'	Nice	Station', address:' Street 1', city:City.find(			46	), agency: Agency.find(3)},
                                              {name:'	Paris	Station', address:' Street 1', city:City.find(			47	), agency: Agency.find(3)},
                                              {name:'	Pau	Station', address:' Street 1', city:City.find(			48	), agency: Agency.find(3)},
                                              {name:'	Toulon	Station', address:' Street 1', city:City.find(			52	), agency: Agency.find(3)},
                                              {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(3)},
                                              {name:'	Frankfurt	Station', address:' Street 1', city:City.find(			58	), agency: Agency.find(3)},
                                              {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(3)},
                                              {name:'	Kos	Station', address:' Street 1', city:City.find(			68	), agency: Agency.find(3)},
                                              {name:'	Santorini	Station', address:' Street 1', city:City.find(			73	), agency: Agency.find(3)},
                                              {name:'	Ancona	Station', address:' Street 1', city:City.find(			78	), agency: Agency.find(3)},
                                              {name:'	Bergamo	Station', address:' Street 1', city:City.find(			79	), agency: Agency.find(3)},
                                              {name:'	Bologna	Station', address:' Street 1', city:City.find(			80	), agency: Agency.find(3)},
                                              {name:'	Bolzano	Station', address:' Street 1', city:City.find(			81	), agency: Agency.find(3)},
                                              {name:'	Brescia	Station', address:' Street 1', city:City.find(			82	), agency: Agency.find(3)},
                                              {name:'	Palermo	Station', address:' Street 1', city:City.find(			92	), agency: Agency.find(3)},
                                              {name:'	Treviso	Station', address:' Street 1', city:City.find(			98	), agency: Agency.find(3)},
                                              {name:'	Trieste	Station', address:' Street 1', city:City.find(			99	), agency: Agency.find(3)},
                                              {name:'	Turin	Station', address:' Street 1', city:City.find(			100	), agency: Agency.find(3)},
                                              {name:'	Rotterdam	Station', address:' Street 1', city:City.find(			112	), agency: Agency.find(3)},
                                              {name:'	Oslo	Station', address:' Street 1', city:City.find(			113	), agency: Agency.find(3)},
                                              {name:'	Bydgoszcz	Station', address:' Street 1', city:City.find(			114	), agency: Agency.find(3)},
                                              {name:'	Gdansk	Station', address:' Street 1', city:City.find(			115	), agency: Agency.find(3)},
                                              {name:'	Katowice	Station', address:' Street 1', city:City.find(			116	), agency: Agency.find(3)},
                                              {name:'	Krakow	Station', address:' Street 1', city:City.find(			117	), agency: Agency.find(3)},
                                              {name:'	Poznan	Station', address:' Street 1', city:City.find(			118	), agency: Agency.find(3)},
                                              {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(3)},
                                              {name:'	Porto	Station', address:' Street 1', city:City.find(			125	), agency: Agency.find(3)},
                                              {name:'	Bucharest	Station', address:' Street 1', city:City.find(			126	), agency: Agency.find(3)},
                                              {name:'	Cluj Napoca	Station', address:' Street 1', city:City.find(			127	), agency: Agency.find(3)},
                                              {name:'	Sibiu	Station', address:' Street 1', city:City.find(			128	), agency: Agency.find(3)},
                                              {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(3)},
                                              {name:'	Saint Petersburg	Station', address:' Street 1', city:City.find(			131	), agency: Agency.find(3)},
                                              {name:'	Belgrade	Station', address:' Street 1', city:City.find(			132	), agency: Agency.find(3)},
                                              {name:'	Bled	Station', address:' Street 1', city:City.find(			134	), agency: Agency.find(3)},
                                              {name:'	Ljubljana	Station', address:' Street 1', city:City.find(			135	), agency: Agency.find(3)},
                                              {name:'	Alicante	Station', address:' Street 1', city:City.find(			137	), agency: Agency.find(3)},
                                              {name:'	Almeria	Station', address:' Street 1', city:City.find(			138	), agency: Agency.find(3)},
                                              {name:'	Barcelona	Station', address:' Street 1', city:City.find(			139	), agency: Agency.find(3)},
                                              {name:'	Bilbao	Station', address:' Street 1', city:City.find(			140	), agency: Agency.find(3)},
                                              {name:'	Girona	Station', address:' Street 1', city:City.find(			141	), agency: Agency.find(3)},
                                              {name:'	Gran Canaria	Station', address:' Street 1', city:City.find(			142	), agency: Agency.find(3)},
                                              {name:'	Madrid	Station', address:' Street 1', city:City.find(			143	), agency: Agency.find(3)},
                                              {name:'	Malaga	Station', address:' Street 1', city:City.find(			144	), agency: Agency.find(3)},
                                              {name:'	Menorca	Station', address:' Street 1', city:City.find(			145	), agency: Agency.find(3)},
                                              {name:'	Murcia	Station', address:' Street 1', city:City.find(			146	), agency: Agency.find(3)},
                                              {name:'	San Sebastian	Station', address:' Street 1', city:City.find(			147	), agency: Agency.find(3)},
                                              {name:'	Santander	Station', address:' Street 1', city:City.find(			148	), agency: Agency.find(3)},
                                              {name:'	Tenerife	Station', address:' Street 1', city:City.find(			149	), agency: Agency.find(3)},
                                              {name:'	Zurich	Station', address:' Street 1', city:City.find(			156	), agency: Agency.find(3)},
                                              {name:'	Ankara	Station', address:' Street 1', city:City.find(			157	), agency: Agency.find(3)},
                                              {name:'	Antalya	Station', address:' Street 1', city:City.find(			158	), agency: Agency.find(3)},
                                              {name:'	Dalaman	Station', address:' Street 1', city:City.find(			160	), agency: Agency.find(3)},
                                              {name:'	Istanbul	Station', address:' Street 1', city:City.find(			161	), agency: Agency.find(3)},
                                              {name:'	Izmir	Station', address:' Street 1', city:City.find(			162	), agency: Agency.find(3)},
                                              {name:'	Samsun	Station', address:' Street 1', city:City.find(			163	), agency: Agency.find(3)},
                                              {name:'	Birmingham	Station', address:' Street 1', city:City.find(			164	), agency: Agency.find(3)},
                                              {name:'	Manchester	Station', address:' Street 1', city:City.find(			169	), agency: Agency.find(3)}
                                          ])

  dollar_subsidiaries = Subsidiary.create([
                                              {name:'	Klagenfurt	Station', address:' Street 1', city:City.find(			2	), agency: Agency.find(4)},
                                              {name:'	Vienna	Station', address:' Street 1', city:City.find(			4	), agency: Agency.find(4)},
                                              {name:'	Burgas	Station', address:' Street 1', city:City.find(			8	), agency: Agency.find(4)},
                                              {name:'	Plovdiv	Station', address:' Street 1', city:City.find(			9	), agency: Agency.find(4)},
                                              {name:'	Varna	Station', address:' Street 1', city:City.find(			11	), agency: Agency.find(4)},
                                              {name:'	Dubrovnik	Station', address:' Street 1', city:City.find(			12	), agency: Agency.find(4)},
                                              {name:'	Split	Station', address:' Street 1', city:City.find(			16	), agency: Agency.find(4)},
                                              {name:'	Zadar	Station', address:' Street 1', city:City.find(			17	), agency: Agency.find(4)},
                                              {name:'	Zagreb	Station', address:' Street 1', city:City.find(			18	), agency: Agency.find(4)},
                                              {name:'	Larnaca	Station', address:' Street 1', city:City.find(			19	), agency: Agency.find(4)},
                                              {name:'	Paphos	Station', address:' Street 1', city:City.find(			21	), agency: Agency.find(4)},
                                              {name:'	Prague	Station', address:' Street 1', city:City.find(			22	), agency: Agency.find(4)},
                                              {name:'	Aswan	Station', address:' Street 1', city:City.find(			24	), agency: Agency.find(4)},
                                              {name:'	Cairo	Station', address:' Street 1', city:City.find(			25	), agency: Agency.find(4)},
                                              {name:'	Dabaa	Station', address:' Street 1', city:City.find(			26	), agency: Agency.find(4)},
                                              {name:'	Luxor	Station', address:' Street 1', city:City.find(			28	), agency: Agency.find(4)},
                                              {name:'	Marsa Alam	Station', address:' Street 1', city:City.find(			29	), agency: Agency.find(4)},
                                              {name:'	Sharm El Sheikh	Station', address:' Street 1', city:City.find(			30	), agency: Agency.find(4)},
                                              {name:'	Tallinn	Station', address:' Street 1', city:City.find(			32	), agency: Agency.find(4)},
                                              {name:'	Tartu	Station', address:' Street 1', city:City.find(			33	), agency: Agency.find(4)},
                                              {name:'	Marseille	Station', address:' Street 1', city:City.find(			42	), agency: Agency.find(4)},
                                              {name:'	Metz	Station', address:' Street 1', city:City.find(			43	), agency: Agency.find(4)},
                                              {name:'	Montpellier	Station', address:' Street 1', city:City.find(			44	), agency: Agency.find(4)},
                                              {name:'	Perpignan	Station', address:' Street 1', city:City.find(			49	), agency: Agency.find(4)},
                                              {name:'	Strasbourg	Station', address:' Street 1', city:City.find(			50	), agency: Agency.find(4)},
                                              {name:'	Toulon	Station', address:' Street 1', city:City.find(			52	), agency: Agency.find(4)},
                                              {name:'	Toulouse	Station', address:' Street 1', city:City.find(			53	), agency: Agency.find(4)},
                                              {name:'	Bremen	Station', address:' Street 1', city:City.find(			55	), agency: Agency.find(4)},
                                              {name:'	Cologne	Station', address:' Street 1', city:City.find(			56	), agency: Agency.find(4)},
                                              {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(4)},
                                              {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(4)},
                                              {name:'	Hannover	Station', address:' Street 1', city:City.find(			61	), agency: Agency.find(4)},
                                              {name:'	Leipzig	Station', address:' Street 1', city:City.find(			62	), agency: Agency.find(4)},
                                              {name:'	Nuremberg	Station', address:' Street 1', city:City.find(			64	), agency: Agency.find(4)},
                                              {name:'	Stuttgart	Station', address:' Street 1', city:City.find(			65	), agency: Agency.find(4)},
                                              {name:'	Crete	Station', address:' Street 1', city:City.find(			67	), agency: Agency.find(4)},
                                              {name:'	Kos	Station', address:' Street 1', city:City.find(			68	), agency: Agency.find(4)},
                                              {name:'	Mykonos	Station', address:' Street 1', city:City.find(			69	), agency: Agency.find(4)},
                                              {name:'	Naxos	Station', address:' Street 1', city:City.find(			70	), agency: Agency.find(4)},
                                              {name:'	Paros	Station', address:' Street 1', city:City.find(			71	), agency: Agency.find(4)},
                                              {name:'	Santorini	Station', address:' Street 1', city:City.find(			73	), agency: Agency.find(4)},
                                              {name:'	Ancona	Station', address:' Street 1', city:City.find(			78	), agency: Agency.find(4)},
                                              {name:'	Bologna	Station', address:' Street 1', city:City.find(			80	), agency: Agency.find(4)},
                                              {name:'	Bolzano	Station', address:' Street 1', city:City.find(			81	), agency: Agency.find(4)},
                                              {name:'	Brescia	Station', address:' Street 1', city:City.find(			82	), agency: Agency.find(4)},
                                              {name:'	Cagliari	Station', address:' Street 1', city:City.find(			83	), agency: Agency.find(4)},
                                              {name:'	Florence	Station', address:' Street 1', city:City.find(			85	), agency: Agency.find(4)},
                                              {name:'	Forli	Station', address:' Street 1', city:City.find(			86	), agency: Agency.find(4)},
                                              {name:'	Genoa	Station', address:' Street 1', city:City.find(			87	), agency: Agency.find(4)},
                                              {name:'	Lamezia Terme	Station', address:' Street 1', city:City.find(			88	), agency: Agency.find(4)},
                                              {name:'	Milan	Station', address:' Street 1', city:City.find(			89	), agency: Agency.find(4)},
                                              {name:'	Rome	Station', address:' Street 1', city:City.find(			96	), agency: Agency.find(4)},
                                              {name:'	Trapani	Station', address:' Street 1', city:City.find(			97	), agency: Agency.find(4)},
                                              {name:'	Treviso	Station', address:' Street 1', city:City.find(			98	), agency: Agency.find(4)},
                                              {name:'	Turin	Station', address:' Street 1', city:City.find(			100	), agency: Agency.find(4)},
                                              {name:'	Venice	Station', address:' Street 1', city:City.find(			101	), agency: Agency.find(4)},
                                              {name:'	Liepaja	Station', address:' Street 1', city:City.find(			103	), agency: Agency.find(4)},
                                              {name:'	Riga	Station', address:' Street 1', city:City.find(			104	), agency: Agency.find(4)},
                                              {name:'	Palanga	Station', address:' Street 1', city:City.find(			106	), agency: Agency.find(4)},
                                              {name:'	Vilnius	Station', address:' Street 1', city:City.find(			107	), agency: Agency.find(4)},
                                              {name:'	Luxembourg	Station', address:' Street 1', city:City.find(			108	), agency: Agency.find(4)},
                                              {name:'	Valletta	Station', address:' Street 1', city:City.find(			109	), agency: Agency.find(4)},
                                              {name:'	Amsterdam	Station', address:' Street 1', city:City.find(			110	), agency: Agency.find(4)},
                                              {name:'	Krakow	Station', address:' Street 1', city:City.find(			117	), agency: Agency.find(4)},
                                              {name:'	Poznan	Station', address:' Street 1', city:City.find(			118	), agency: Agency.find(4)},
                                              {name:'	Warsaw	Station', address:' Street 1', city:City.find(			119	), agency: Agency.find(4)},
                                              {name:'	Wroclaw	Station', address:' Street 1', city:City.find(			120	), agency: Agency.find(4)},
                                              {name:'	Faro	Station', address:' Street 1', city:City.find(			122	), agency: Agency.find(4)},
                                              {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(4)},
                                              {name:'	Cluj Napoca	Station', address:' Street 1', city:City.find(			127	), agency: Agency.find(4)},
                                              {name:'	Sibiu	Station', address:' Street 1', city:City.find(			128	), agency: Agency.find(4)},
                                              {name:'	Timisoara	Station', address:' Street 1', city:City.find(			129	), agency: Agency.find(4)},
                                              {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(4)},
                                              {name:'	Bratislava	Station', address:' Street 1', city:City.find(			133	), agency: Agency.find(4)},
                                              {name:'	Bled	Station', address:' Street 1', city:City.find(			134	), agency: Agency.find(4)},
                                              {name:'	Ljubljana	Station', address:' Street 1', city:City.find(			135	), agency: Agency.find(4)},
                                              {name:'	Portoroz	Station', address:' Street 1', city:City.find(			136	), agency: Agency.find(4)},
                                              {name:'	Alicante	Station', address:' Street 1', city:City.find(			137	), agency: Agency.find(4)},
                                              {name:'	Gran Canaria	Station', address:' Street 1', city:City.find(			142	), agency: Agency.find(4)},
                                              {name:'	Madrid	Station', address:' Street 1', city:City.find(			143	), agency: Agency.find(4)},
                                              {name:'	Malaga	Station', address:' Street 1', city:City.find(			144	), agency: Agency.find(4)},
                                              {name:'	Murcia	Station', address:' Street 1', city:City.find(			146	), agency: Agency.find(4)},
                                              {name:'	Sion	Station', address:' Street 1', city:City.find(			155	), agency: Agency.find(4)},
                                              {name:'	Bodrum	Station', address:' Street 1', city:City.find(			159	), agency: Agency.find(4)},
                                              {name:'	Istanbul	Station', address:' Street 1', city:City.find(			161	), agency: Agency.find(4)},
                                              {name:'	Samsun	Station', address:' Street 1', city:City.find(			163	), agency: Agency.find(4)},
                                              {name:'	Birmingham	Station', address:' Street 1', city:City.find(			164	), agency: Agency.find(4)},
                                              {name:'	Edinburgh	Station', address:' Street 1', city:City.find(			166	), agency: Agency.find(4)},
                                              {name:'	Glasgow	Station', address:' Street 1', city:City.find(			167	), agency: Agency.find(4)},
                                              {name:'	London	Station', address:' Street 1', city:City.find(			168	), agency: Agency.find(4)}

                                          ])

  europcar_subsidiaries = Subsidiary.create([
                                                {name:'	Innsbruck	Station', address:' Street 1', city:City.find(			1	), agency: Agency.find(5)},
                                                {name:'	Salzburg	Station', address:' Street 1', city:City.find(			3	), agency: Agency.find(5)},
                                                {name:'	Brussels	Station', address:' Street 1', city:City.find(			7	), agency: Agency.find(5)},
                                                {name:'	Burgas	Station', address:' Street 1', city:City.find(			8	), agency: Agency.find(5)},
                                                {name:'	Plovdiv	Station', address:' Street 1', city:City.find(			9	), agency: Agency.find(5)},
                                                {name:'	Varna	Station', address:' Street 1', city:City.find(			11	), agency: Agency.find(5)},
                                                {name:'	Dubrovnik	Station', address:' Street 1', city:City.find(			12	), agency: Agency.find(5)},
                                                {name:'	Osijek	Station', address:' Street 1', city:City.find(			13	), agency: Agency.find(5)},
                                                {name:'	Pula	Station', address:' Street 1', city:City.find(			14	), agency: Agency.find(5)},
                                                {name:'	Rijeka	Station', address:' Street 1', city:City.find(			15	), agency: Agency.find(5)},
                                                {name:'	Split	Station', address:' Street 1', city:City.find(			16	), agency: Agency.find(5)},
                                                {name:'	Zadar	Station', address:' Street 1', city:City.find(			17	), agency: Agency.find(5)},
                                                {name:'	Zagreb	Station', address:' Street 1', city:City.find(			18	), agency: Agency.find(5)},
                                                {name:'	Larnaca	Station', address:' Street 1', city:City.find(			19	), agency: Agency.find(5)},
                                                {name:'	Limassol	Station', address:' Street 1', city:City.find(			20	), agency: Agency.find(5)},
                                                {name:'	Luxor	Station', address:' Street 1', city:City.find(			28	), agency: Agency.find(5)},
                                                {name:'	Marsa Alam	Station', address:' Street 1', city:City.find(			29	), agency: Agency.find(5)},
                                                {name:'	Sharm El Sheikh	Station', address:' Street 1', city:City.find(			30	), agency: Agency.find(5)},
                                                {name:'	Taba	Station', address:' Street 1', city:City.find(			31	), agency: Agency.find(5)},
                                                {name:'	Tallinn	Station', address:' Street 1', city:City.find(			32	), agency: Agency.find(5)},
                                                {name:'	Tartu	Station', address:' Street 1', city:City.find(			33	), agency: Agency.find(5)},
                                                {name:'	Helsinki	Station', address:' Street 1', city:City.find(			34	), agency: Agency.find(5)},
                                                {name:'	Annecy	Station', address:' Street 1', city:City.find(			35	), agency: Agency.find(5)},
                                                {name:'	Biarritz	Station', address:' Street 1', city:City.find(			36	), agency: Agency.find(5)},
                                                {name:'	Bordeaux	Station', address:' Street 1', city:City.find(			37	), agency: Agency.find(5)},
                                                {name:'	Cannes	Station', address:' Street 1', city:City.find(			38	), agency: Agency.find(5)},
                                                {name:'	Chambery	Station', address:' Street 1', city:City.find(			39	), agency: Agency.find(5)},
                                                {name:'	Grenoble	Station', address:' Street 1', city:City.find(			40	), agency: Agency.find(5)},
                                                {name:'	Lyon	Station', address:' Street 1', city:City.find(			41	), agency: Agency.find(5)},
                                                {name:'	Marseille	Station', address:' Street 1', city:City.find(			42	), agency: Agency.find(5)},
                                                {name:'	Nancy	Station', address:' Street 1', city:City.find(			45	), agency: Agency.find(5)},
                                                {name:'	Paris	Station', address:' Street 1', city:City.find(			47	), agency: Agency.find(5)},
                                                {name:'	Pau	Station', address:' Street 1', city:City.find(			48	), agency: Agency.find(5)},
                                                {name:'	Perpignan	Station', address:' Street 1', city:City.find(			49	), agency: Agency.find(5)},
                                                {name:'	Strasbourg	Station', address:' Street 1', city:City.find(			50	), agency: Agency.find(5)},
                                                {name:'	Toulon	Station', address:' Street 1', city:City.find(			52	), agency: Agency.find(5)},
                                                {name:'	Toulouse	Station', address:' Street 1', city:City.find(			53	), agency: Agency.find(5)},
                                                {name:'	Berlin	Station', address:' Street 1', city:City.find(			54	), agency: Agency.find(5)},
                                                {name:'	Bremen	Station', address:' Street 1', city:City.find(			55	), agency: Agency.find(5)},
                                                {name:'	Cologne	Station', address:' Street 1', city:City.find(			56	), agency: Agency.find(5)},
                                                {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(5)},
                                                {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(5)},
                                                {name:'	Hannover	Station', address:' Street 1', city:City.find(			61	), agency: Agency.find(5)},
                                                {name:'	Nuremberg	Station', address:' Street 1', city:City.find(			64	), agency: Agency.find(5)},
                                                {name:'	Mykonos	Station', address:' Street 1', city:City.find(			69	), agency: Agency.find(5)},
                                                {name:'	Naxos	Station', address:' Street 1', city:City.find(			70	), agency: Agency.find(5)},
                                                {name:'	Paros	Station', address:' Street 1', city:City.find(			71	), agency: Agency.find(5)},
                                                {name:'	Rhodes	Station', address:' Street 1', city:City.find(			72	), agency: Agency.find(5)},
                                                {name:'	Santorini	Station', address:' Street 1', city:City.find(			73	), agency: Agency.find(5)},
                                                {name:'	Thessaloniki	Station', address:' Street 1', city:City.find(			74	), agency: Agency.find(5)},
                                                {name:'	Bergamo	Station', address:' Street 1', city:City.find(			79	), agency: Agency.find(5)},
                                                {name:'	Bologna	Station', address:' Street 1', city:City.find(			80	), agency: Agency.find(5)},
                                                {name:'	Bolzano	Station', address:' Street 1', city:City.find(			81	), agency: Agency.find(5)},
                                                {name:'	Cagliari	Station', address:' Street 1', city:City.find(			83	), agency: Agency.find(5)},
                                                {name:'	Catania	Station', address:' Street 1', city:City.find(			84	), agency: Agency.find(5)},
                                                {name:'	Genoa	Station', address:' Street 1', city:City.find(			87	), agency: Agency.find(5)},
                                                {name:'	Lamezia Terme	Station', address:' Street 1', city:City.find(			88	), agency: Agency.find(5)},
                                                {name:'	Naples	Station', address:' Street 1', city:City.find(			90	), agency: Agency.find(5)},
                                                {name:'	Pescara	Station', address:' Street 1', city:City.find(			93	), agency: Agency.find(5)},
                                                {name:'	Rome	Station', address:' Street 1', city:City.find(			96	), agency: Agency.find(5)},
                                                {name:'	Trapani	Station', address:' Street 1', city:City.find(			97	), agency: Agency.find(5)},
                                                {name:'	Treviso	Station', address:' Street 1', city:City.find(			98	), agency: Agency.find(5)},
                                                {name:'	Trieste	Station', address:' Street 1', city:City.find(			99	), agency: Agency.find(5)},
                                                {name:'	Turin	Station', address:' Street 1', city:City.find(			100	), agency: Agency.find(5)},
                                                {name:'	Liepaja	Station', address:' Street 1', city:City.find(			103	), agency: Agency.find(5)},
                                                {name:'	Riga	Station', address:' Street 1', city:City.find(			104	), agency: Agency.find(5)},
                                                {name:'	Palanga	Station', address:' Street 1', city:City.find(			106	), agency: Agency.find(5)},
                                                {name:'	Vilnius	Station', address:' Street 1', city:City.find(			107	), agency: Agency.find(5)},
                                                {name:'	Eindhoven	Station', address:' Street 1', city:City.find(			111	), agency: Agency.find(5)},
                                                {name:'	Rotterdam	Station', address:' Street 1', city:City.find(			112	), agency: Agency.find(5)},
                                                {name:'	Oslo	Station', address:' Street 1', city:City.find(			113	), agency: Agency.find(5)},
                                                {name:'	Gdansk	Station', address:' Street 1', city:City.find(			115	), agency: Agency.find(5)},
                                                {name:'	Katowice	Station', address:' Street 1', city:City.find(			116	), agency: Agency.find(5)},
                                                {name:'	Poznan	Station', address:' Street 1', city:City.find(			118	), agency: Agency.find(5)},
                                                {name:'	Warsaw	Station', address:' Street 1', city:City.find(			119	), agency: Agency.find(5)},
                                                {name:'	Beja	Station', address:' Street 1', city:City.find(			121	), agency: Agency.find(5)},
                                                {name:'	Faro	Station', address:' Street 1', city:City.find(			122	), agency: Agency.find(5)},
                                                {name:'	Funchal	Station', address:' Street 1', city:City.find(			123	), agency: Agency.find(5)},
                                                {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(5)},
                                                {name:'	Porto	Station', address:' Street 1', city:City.find(			125	), agency: Agency.find(5)},
                                                {name:'	Bucharest	Station', address:' Street 1', city:City.find(			126	), agency: Agency.find(5)},
                                                {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(5)},
                                                {name:'	Saint Petersburg	Station', address:' Street 1', city:City.find(			131	), agency: Agency.find(5)},
                                                {name:'	Bratislava	Station', address:' Street 1', city:City.find(			133	), agency: Agency.find(5)},
                                                {name:'	Bled	Station', address:' Street 1', city:City.find(			134	), agency: Agency.find(5)},
                                                {name:'	Ljubljana	Station', address:' Street 1', city:City.find(			135	), agency: Agency.find(5)},
                                                {name:'	Alicante	Station', address:' Street 1', city:City.find(			137	), agency: Agency.find(5)},
                                                {name:'	Almeria	Station', address:' Street 1', city:City.find(			138	), agency: Agency.find(5)},
                                                {name:'	Bilbao	Station', address:' Street 1', city:City.find(			140	), agency: Agency.find(5)},
                                                {name:'	Girona	Station', address:' Street 1', city:City.find(			141	), agency: Agency.find(5)},
                                                {name:'	Madrid	Station', address:' Street 1', city:City.find(			143	), agency: Agency.find(5)},
                                                {name:'	Malaga	Station', address:' Street 1', city:City.find(			144	), agency: Agency.find(5)},
                                                {name:'	Murcia	Station', address:' Street 1', city:City.find(			146	), agency: Agency.find(5)},
                                                {name:'	Santander	Station', address:' Street 1', city:City.find(			148	), agency: Agency.find(5)},
                                                {name:'	Tenerife	Station', address:' Street 1', city:City.find(			149	), agency: Agency.find(5)},
                                                {name:'	Valencia	Station', address:' Street 1', city:City.find(			150	), agency: Agency.find(5)},
                                                {name:'	Bern	Station', address:' Street 1', city:City.find(			152	), agency: Agency.find(5)},
                                                {name:'	Geneva	Station', address:' Street 1', city:City.find(			153	), agency: Agency.find(5)},
                                                {name:'	Lugano	Station', address:' Street 1', city:City.find(			154	), agency: Agency.find(5)},
                                                {name:'	Zurich	Station', address:' Street 1', city:City.find(			156	), agency: Agency.find(5)},
                                                {name:'	Antalya	Station', address:' Street 1', city:City.find(			158	), agency: Agency.find(5)},
                                                {name:'	Dalaman	Station', address:' Street 1', city:City.find(			160	), agency: Agency.find(5)},
                                                {name:'	Birmingham	Station', address:' Street 1', city:City.find(			164	), agency: Agency.find(5)},
                                                {name:'	Edinburgh	Station', address:' Street 1', city:City.find(			166	), agency: Agency.find(5)},
                                                {name:'	Glasgow	Station', address:' Street 1', city:City.find(			167	), agency: Agency.find(5)},
                                                {name:'	London	Station', address:' Street 1', city:City.find(			168	), agency: Agency.find(5)},
                                                {name:'	Manchester	Station', address:' Street 1', city:City.find(			169	), agency: Agency.find(5)},
                                            ])


  hertz_subsidiaries = Subsidiary.create([
                                             {name:'	Innsbruck	Station', address:' Street 1', city:City.find(			1	), agency: Agency.find(6)},
                                             {name:'	Salzburg	Station', address:' Street 1', city:City.find(			3	), agency: Agency.find(6)},
                                             {name:'	Brussels	Station', address:' Street 1', city:City.find(			7	), agency: Agency.find(6)},
                                             {name:'	Varna	Station', address:' Street 1', city:City.find(			11	), agency: Agency.find(6)},
                                             {name:'	Dubrovnik	Station', address:' Street 1', city:City.find(			12	), agency: Agency.find(6)},
                                             {name:'	Osijek	Station', address:' Street 1', city:City.find(			13	), agency: Agency.find(6)},
                                             {name:'	Pula	Station', address:' Street 1', city:City.find(			14	), agency: Agency.find(6)},
                                             {name:'	Rijeka	Station', address:' Street 1', city:City.find(			15	), agency: Agency.find(6)},
                                             {name:'	Split	Station', address:' Street 1', city:City.find(			16	), agency: Agency.find(6)},
                                             {name:'	Zadar	Station', address:' Street 1', city:City.find(			17	), agency: Agency.find(6)},
                                             {name:'	Zagreb	Station', address:' Street 1', city:City.find(			18	), agency: Agency.find(6)},
                                             {name:'	Larnaca	Station', address:' Street 1', city:City.find(			19	), agency: Agency.find(6)},
                                             {name:'	Limassol	Station', address:' Street 1', city:City.find(			20	), agency: Agency.find(6)},
                                             {name:'	Luxor	Station', address:' Street 1', city:City.find(			28	), agency: Agency.find(6)},
                                             {name:'	Marsa Alam	Station', address:' Street 1', city:City.find(			29	), agency: Agency.find(6)},
                                             {name:'	Sharm El Sheikh	Station', address:' Street 1', city:City.find(			30	), agency: Agency.find(6)},
                                             {name:'	Taba	Station', address:' Street 1', city:City.find(			31	), agency: Agency.find(6)},
                                             {name:'	Tallinn	Station', address:' Street 1', city:City.find(			32	), agency: Agency.find(6)},
                                             {name:'	Tartu	Station', address:' Street 1', city:City.find(			33	), agency: Agency.find(6)},
                                             {name:'	Biarritz	Station', address:' Street 1', city:City.find(			36	), agency: Agency.find(6)},
                                             {name:'	Bordeaux	Station', address:' Street 1', city:City.find(			37	), agency: Agency.find(6)},
                                             {name:'	Cannes	Station', address:' Street 1', city:City.find(			38	), agency: Agency.find(6)},
                                             {name:'	Chambery	Station', address:' Street 1', city:City.find(			39	), agency: Agency.find(6)},
                                             {name:'	Grenoble	Station', address:' Street 1', city:City.find(			40	), agency: Agency.find(6)},
                                             {name:'	Lyon	Station', address:' Street 1', city:City.find(			41	), agency: Agency.find(6)},
                                             {name:'	Marseille	Station', address:' Street 1', city:City.find(			42	), agency: Agency.find(6)},
                                             {name:'	Nancy	Station', address:' Street 1', city:City.find(			45	), agency: Agency.find(6)},
                                             {name:'	Paris	Station', address:' Street 1', city:City.find(			47	), agency: Agency.find(6)},
                                             {name:'	Pau	Station', address:' Street 1', city:City.find(			48	), agency: Agency.find(6)},
                                             {name:'	Perpignan	Station', address:' Street 1', city:City.find(			49	), agency: Agency.find(6)},
                                             {name:'	Strasbourg	Station', address:' Street 1', city:City.find(			50	), agency: Agency.find(6)},
                                             {name:'	Toulon	Station', address:' Street 1', city:City.find(			52	), agency: Agency.find(6)},
                                             {name:'	Berlin	Station', address:' Street 1', city:City.find(			54	), agency: Agency.find(6)},
                                             {name:'	Bremen	Station', address:' Street 1', city:City.find(			55	), agency: Agency.find(6)},
                                             {name:'	Cologne	Station', address:' Street 1', city:City.find(			56	), agency: Agency.find(6)},
                                             {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(6)},
                                             {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(6)},
                                             {name:'	Hannover	Station', address:' Street 1', city:City.find(			61	), agency: Agency.find(6)},
                                             {name:'	Nuremberg	Station', address:' Street 1', city:City.find(			64	), agency: Agency.find(6)},
                                             {name:'	Mykonos	Station', address:' Street 1', city:City.find(			69	), agency: Agency.find(6)},
                                             {name:'	Naxos	Station', address:' Street 1', city:City.find(			70	), agency: Agency.find(6)},
                                             {name:'	Paros	Station', address:' Street 1', city:City.find(			71	), agency: Agency.find(6)},
                                             {name:'	Bergamo	Station', address:' Street 1', city:City.find(			79	), agency: Agency.find(6)},
                                             {name:'	Bologna	Station', address:' Street 1', city:City.find(			80	), agency: Agency.find(6)},
                                             {name:'	Bolzano	Station', address:' Street 1', city:City.find(			81	), agency: Agency.find(6)},
                                             {name:'	Cagliari	Station', address:' Street 1', city:City.find(			83	), agency: Agency.find(6)},
                                             {name:'	Catania	Station', address:' Street 1', city:City.find(			84	), agency: Agency.find(6)},
                                             {name:'	Genoa	Station', address:' Street 1', city:City.find(			87	), agency: Agency.find(6)},
                                             {name:'	Lamezia Terme	Station', address:' Street 1', city:City.find(			88	), agency: Agency.find(6)},
                                             {name:'	Naples	Station', address:' Street 1', city:City.find(			90	), agency: Agency.find(6)},
                                             {name:'	Pescara	Station', address:' Street 1', city:City.find(			93	), agency: Agency.find(6)},
                                             {name:'	Riga	Station', address:' Street 1', city:City.find(			104	), agency: Agency.find(6)},
                                             {name:'	Palanga	Station', address:' Street 1', city:City.find(			106	), agency: Agency.find(6)},
                                             {name:'	Vilnius	Station', address:' Street 1', city:City.find(			107	), agency: Agency.find(6)},
                                             {name:'	Eindhoven	Station', address:' Street 1', city:City.find(			111	), agency: Agency.find(6)},
                                             {name:'	Rotterdam	Station', address:' Street 1', city:City.find(			112	), agency: Agency.find(6)},
                                             {name:'	Oslo	Station', address:' Street 1', city:City.find(			113	), agency: Agency.find(6)},
                                             {name:'	Gdansk	Station', address:' Street 1', city:City.find(			115	), agency: Agency.find(6)},
                                             {name:'	Katowice	Station', address:' Street 1', city:City.find(			116	), agency: Agency.find(6)},
                                             {name:'	Poznan	Station', address:' Street 1', city:City.find(			118	), agency: Agency.find(6)},
                                             {name:'	Warsaw	Station', address:' Street 1', city:City.find(			119	), agency: Agency.find(6)},
                                             {name:'	Beja	Station', address:' Street 1', city:City.find(			121	), agency: Agency.find(6)},
                                             {name:'	Faro	Station', address:' Street 1', city:City.find(			122	), agency: Agency.find(6)},
                                             {name:'	Funchal	Station', address:' Street 1', city:City.find(			123	), agency: Agency.find(6)},
                                             {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(6)},
                                             {name:'	Porto	Station', address:' Street 1', city:City.find(			125	), agency: Agency.find(6)},
                                             {name:'	Bucharest	Station', address:' Street 1', city:City.find(			126	), agency: Agency.find(6)},
                                             {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(6)},
                                             {name:'	Saint Petersburg	Station', address:' Street 1', city:City.find(			131	), agency: Agency.find(6)},
                                             {name:'	Bratislava	Station', address:' Street 1', city:City.find(			133	), agency: Agency.find(6)},
                                             {name:'	Almeria	Station', address:' Street 1', city:City.find(			138	), agency: Agency.find(6)},
                                             {name:'	Bilbao	Station', address:' Street 1', city:City.find(			140	), agency: Agency.find(6)},
                                             {name:'	Girona	Station', address:' Street 1', city:City.find(			141	), agency: Agency.find(6)},
                                             {name:'	Madrid	Station', address:' Street 1', city:City.find(			143	), agency: Agency.find(6)},
                                             {name:'	Malaga	Station', address:' Street 1', city:City.find(			144	), agency: Agency.find(6)},
                                             {name:'	Murcia	Station', address:' Street 1', city:City.find(			146	), agency: Agency.find(6)},
                                             {name:'	Santander	Station', address:' Street 1', city:City.find(			148	), agency: Agency.find(6)},
                                             {name:'	Tenerife	Station', address:' Street 1', city:City.find(			149	), agency: Agency.find(6)},
                                             {name:'	Zurich	Station', address:' Street 1', city:City.find(			156	), agency: Agency.find(6)},
                                             {name:'	Antalya	Station', address:' Street 1', city:City.find(			158	), agency: Agency.find(6)},
                                             {name:'	Dalaman	Station', address:' Street 1', city:City.find(			160	), agency: Agency.find(6)},
                                             {name:'	Birmingham	Station', address:' Street 1', city:City.find(			164	), agency: Agency.find(6)},
                                             {name:'	Edinburgh	Station', address:' Street 1', city:City.find(			166	), agency: Agency.find(6)},
                                             {name:'	Glasgow	Station', address:' Street 1', city:City.find(			167	), agency: Agency.find(6)}

                                         ])

  national_subsidiaries = Subsidiary.create([
                                                {name:'	Innsbruck	Station', address:' Street 1', city:City.find(			1	), agency: Agency.find(7)},
                                                {name:'	Klagenfurt	Station', address:' Street 1', city:City.find(			2	), agency: Agency.find(7)},
                                                {name:'	Salzburg	Station', address:' Street 1', city:City.find(			3	), agency: Agency.find(7)},
                                                {name:'	Vienna	Station', address:' Street 1', city:City.find(			4	), agency: Agency.find(7)},
                                                {name:'	Plovdiv	Station', address:' Street 1', city:City.find(			9	), agency: Agency.find(7)},
                                                {name:'	Sofia	Station', address:' Street 1', city:City.find(			10	), agency: Agency.find(7)},
                                                {name:'	Varna	Station', address:' Street 1', city:City.find(			11	), agency: Agency.find(7)},
                                                {name:'	Dubrovnik	Station', address:' Street 1', city:City.find(			12	), agency: Agency.find(7)},
                                                {name:'	Split	Station', address:' Street 1', city:City.find(			16	), agency: Agency.find(7)},
                                                {name:'	Zadar	Station', address:' Street 1', city:City.find(			17	), agency: Agency.find(7)},
                                                {name:'	Zagreb	Station', address:' Street 1', city:City.find(			18	), agency: Agency.find(7)},
                                                {name:'	Prague	Station', address:' Street 1', city:City.find(			22	), agency: Agency.find(7)},
                                                {name:'	Alexandria	Station', address:' Street 1', city:City.find(			23	), agency: Agency.find(7)},
                                                {name:'	Aswan	Station', address:' Street 1', city:City.find(			24	), agency: Agency.find(7)},
                                                {name:'	Cairo	Station', address:' Street 1', city:City.find(			25	), agency: Agency.find(7)},
                                                {name:'	Dabaa	Station', address:' Street 1', city:City.find(			26	), agency: Agency.find(7)},
                                                {name:'	Sharm El Sheikh	Station', address:' Street 1', city:City.find(			30	), agency: Agency.find(7)},
                                                {name:'	Taba	Station', address:' Street 1', city:City.find(			31	), agency: Agency.find(7)},
                                                {name:'	Tallinn	Station', address:' Street 1', city:City.find(			32	), agency: Agency.find(7)},
                                                {name:'	Tartu	Station', address:' Street 1', city:City.find(			33	), agency: Agency.find(7)},
                                                {name:'	Annecy	Station', address:' Street 1', city:City.find(			35	), agency: Agency.find(7)},
                                                {name:'	Biarritz	Station', address:' Street 1', city:City.find(			36	), agency: Agency.find(7)},
                                                {name:'	Chambery	Station', address:' Street 1', city:City.find(			39	), agency: Agency.find(7)},
                                                {name:'	Grenoble	Station', address:' Street 1', city:City.find(			40	), agency: Agency.find(7)},
                                                {name:'	Lyon	Station', address:' Street 1', city:City.find(			41	), agency: Agency.find(7)},
                                                {name:'	Metz	Station', address:' Street 1', city:City.find(			43	), agency: Agency.find(7)},
                                                {name:'	Montpellier	Station', address:' Street 1', city:City.find(			44	), agency: Agency.find(7)},
                                                {name:'	Nancy	Station', address:' Street 1', city:City.find(			45	), agency: Agency.find(7)},
                                                {name:'	Paris	Station', address:' Street 1', city:City.find(			47	), agency: Agency.find(7)},
                                                {name:'	Perpignan	Station', address:' Street 1', city:City.find(			49	), agency: Agency.find(7)},
                                                {name:'	Strasbourg	Station', address:' Street 1', city:City.find(			50	), agency: Agency.find(7)},
                                                {name:'	Toulon	Station', address:' Street 1', city:City.find(			52	), agency: Agency.find(7)},
                                                {name:'	Toulouse	Station', address:' Street 1', city:City.find(			53	), agency: Agency.find(7)},
                                                {name:'	Berlin	Station', address:' Street 1', city:City.find(			54	), agency: Agency.find(7)},
                                                {name:'	Cologne	Station', address:' Street 1', city:City.find(			56	), agency: Agency.find(7)},
                                                {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(7)},
                                                {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(7)},
                                                {name:'	Hamburg	Station', address:' Street 1', city:City.find(			60	), agency: Agency.find(7)},
                                                {name:'	Hannover	Station', address:' Street 1', city:City.find(			61	), agency: Agency.find(7)},
                                                {name:'	Leipzig	Station', address:' Street 1', city:City.find(			62	), agency: Agency.find(7)},
                                                {name:'	Munich	Station', address:' Street 1', city:City.find(			63	), agency: Agency.find(7)},
                                                {name:'	Nuremberg	Station', address:' Street 1', city:City.find(			64	), agency: Agency.find(7)},
                                                {name:'	Stuttgart	Station', address:' Street 1', city:City.find(			65	), agency: Agency.find(7)},
                                                {name:'	Naxos	Station', address:' Street 1', city:City.find(			70	), agency: Agency.find(7)},
                                                {name:'	Rhodes	Station', address:' Street 1', city:City.find(			72	), agency: Agency.find(7)},
                                                {name:'	Santorini	Station', address:' Street 1', city:City.find(			73	), agency: Agency.find(7)},
                                                {name:'	Zakynthos	Station', address:' Street 1', city:City.find(			75	), agency: Agency.find(7)},
                                                {name:'	Budapest	Station', address:' Street 1', city:City.find(			76	), agency: Agency.find(7)},
                                                {name:'	Alghero	Station', address:' Street 1', city:City.find(			77	), agency: Agency.find(7)},
                                                {name:'	Ancona	Station', address:' Street 1', city:City.find(			78	), agency: Agency.find(7)},
                                                {name:'	Bergamo	Station', address:' Street 1', city:City.find(			79	), agency: Agency.find(7)},
                                                {name:'	Bologna	Station', address:' Street 1', city:City.find(			80	), agency: Agency.find(7)},
                                                {name:'	Bolzano	Station', address:' Street 1', city:City.find(			81	), agency: Agency.find(7)},
                                                {name:'	Brescia	Station', address:' Street 1', city:City.find(			82	), agency: Agency.find(7)},
                                                {name:'	Lamezia Terme	Station', address:' Street 1', city:City.find(			88	), agency: Agency.find(7)},
                                                {name:'	Milan	Station', address:' Street 1', city:City.find(			89	), agency: Agency.find(7)},
                                                {name:'	Olbia	Station', address:' Street 1', city:City.find(			91	), agency: Agency.find(7)},
                                                {name:'	Palermo	Station', address:' Street 1', city:City.find(			92	), agency: Agency.find(7)},
                                                {name:'	Rimini	Station', address:' Street 1', city:City.find(			95	), agency: Agency.find(7)},
                                                {name:'	Rome	Station', address:' Street 1', city:City.find(			96	), agency: Agency.find(7)},
                                                {name:'	Trapani	Station', address:' Street 1', city:City.find(			97	), agency: Agency.find(7)},
                                                {name:'	Trieste	Station', address:' Street 1', city:City.find(			99	), agency: Agency.find(7)},
                                                {name:'	Turin	Station', address:' Street 1', city:City.find(			100	), agency: Agency.find(7)},
                                                {name:'	Venice	Station', address:' Street 1', city:City.find(			101	), agency: Agency.find(7)},
                                                {name:'	Verona	Station', address:' Street 1', city:City.find(			102	), agency: Agency.find(7)},
                                                {name:'	Liepaja	Station', address:' Street 1', city:City.find(			103	), agency: Agency.find(7)},
                                                {name:'	Riga	Station', address:' Street 1', city:City.find(			104	), agency: Agency.find(7)},
                                                {name:'	Kaunas	Station', address:' Street 1', city:City.find(			105	), agency: Agency.find(7)},
                                                {name:'	Palanga	Station', address:' Street 1', city:City.find(			106	), agency: Agency.find(7)},
                                                {name:'	Vilnius	Station', address:' Street 1', city:City.find(			107	), agency: Agency.find(7)},
                                                {name:'	Valletta	Station', address:' Street 1', city:City.find(			109	), agency: Agency.find(7)},
                                                {name:'	Amsterdam	Station', address:' Street 1', city:City.find(			110	), agency: Agency.find(7)},
                                                {name:'	Eindhoven	Station', address:' Street 1', city:City.find(			111	), agency: Agency.find(7)},
                                                {name:'	Rotterdam	Station', address:' Street 1', city:City.find(			112	), agency: Agency.find(7)},
                                                {name:'	Bydgoszcz	Station', address:' Street 1', city:City.find(			114	), agency: Agency.find(7)},
                                                {name:'	Gdansk	Station', address:' Street 1', city:City.find(			115	), agency: Agency.find(7)},
                                                {name:'	Katowice	Station', address:' Street 1', city:City.find(			116	), agency: Agency.find(7)},
                                                {name:'	Krakow	Station', address:' Street 1', city:City.find(			117	), agency: Agency.find(7)},
                                                {name:'	Poznan	Station', address:' Street 1', city:City.find(			118	), agency: Agency.find(7)},
                                                {name:'	Wroclaw	Station', address:' Street 1', city:City.find(			120	), agency: Agency.find(7)},
                                                {name:'	Beja	Station', address:' Street 1', city:City.find(			121	), agency: Agency.find(7)},
                                                {name:'	Faro	Station', address:' Street 1', city:City.find(			122	), agency: Agency.find(7)},
                                                {name:'	Funchal	Station', address:' Street 1', city:City.find(			123	), agency: Agency.find(7)},
                                                {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(7)},
                                                {name:'	Porto	Station', address:' Street 1', city:City.find(			125	), agency: Agency.find(7)},
                                                {name:'	Cluj Napoca	Station', address:' Street 1', city:City.find(			127	), agency: Agency.find(7)},
                                                {name:'	Timisoara	Station', address:' Street 1', city:City.find(			129	), agency: Agency.find(7)},
                                                {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(7)},
                                                {name:'	Saint Petersburg	Station', address:' Street 1', city:City.find(			131	), agency: Agency.find(7)},
                                                {name:'	Belgrade	Station', address:' Street 1', city:City.find(			132	), agency: Agency.find(7)},
                                                {name:'	Bratislava	Station', address:' Street 1', city:City.find(			133	), agency: Agency.find(7)},
                                                {name:'	Bled	Station', address:' Street 1', city:City.find(			134	), agency: Agency.find(7)},
                                                {name:'	Alicante	Station', address:' Street 1', city:City.find(			137	), agency: Agency.find(7)},
                                                {name:'	Almeria	Station', address:' Street 1', city:City.find(			138	), agency: Agency.find(7)},
                                                {name:'	Barcelona	Station', address:' Street 1', city:City.find(			139	), agency: Agency.find(7)},
                                                {name:'	Bilbao	Station', address:' Street 1', city:City.find(			140	), agency: Agency.find(7)},
                                                {name:'	Gran Canaria	Station', address:' Street 1', city:City.find(			142	), agency: Agency.find(7)},
                                                {name:'	San Sebastian	Station', address:' Street 1', city:City.find(			147	), agency: Agency.find(7)},
                                                {name:'	Santander	Station', address:' Street 1', city:City.find(			148	), agency: Agency.find(7)},
                                                {name:'	Tenerife	Station', address:' Street 1', city:City.find(			149	), agency: Agency.find(7)},
                                                {name:'	Valencia	Station', address:' Street 1', city:City.find(			150	), agency: Agency.find(7)},
                                                {name:'	Sion	Station', address:' Street 1', city:City.find(			155	), agency: Agency.find(7)},
                                                {name:'	Zurich	Station', address:' Street 1', city:City.find(			156	), agency: Agency.find(7)},
                                                {name:'	Ankara	Station', address:' Street 1', city:City.find(			157	), agency: Agency.find(7)},
                                                {name:'	Antalya	Station', address:' Street 1', city:City.find(			158	), agency: Agency.find(7)},
                                                {name:'	Bristol	Station', address:' Street 1', city:City.find(			165	), agency: Agency.find(7)},
                                                {name:'	Glasgow	Station', address:' Street 1', city:City.find(			167	), agency: Agency.find(7)},
                                                {name:'	London	Station', address:' Street 1', city:City.find(			168	), agency: Agency.find(7)},
                                                {name:'	Manchester	Station', address:' Street 1', city:City.find(			169	), agency: Agency.find(7)}


                                            ])

  thrifty_subsidiaries = Subsidiary.create([
                                               {name:'	Prague	Station', address:' Street 1', city:City.find(			22	), agency: Agency.find(8)},
                                               {name:'	Alexandria	Station', address:' Street 1', city:City.find(			23	), agency: Agency.find(8)},
                                               {name:'	Aswan	Station', address:' Street 1', city:City.find(			24	), agency: Agency.find(8)},
                                               {name:'	Cairo	Station', address:' Street 1', city:City.find(			25	), agency: Agency.find(8)},
                                               {name:'	Metz	Station', address:' Street 1', city:City.find(			43	), agency: Agency.find(8)},
                                               {name:'	Montpellier	Station', address:' Street 1', city:City.find(			44	), agency: Agency.find(8)},
                                               {name:'	Nancy	Station', address:' Street 1', city:City.find(			45	), agency: Agency.find(8)},
                                               {name:'	Nice	Station', address:' Street 1', city:City.find(			46	), agency: Agency.find(8)},
                                               {name:'	Paris	Station', address:' Street 1', city:City.find(			47	), agency: Agency.find(8)},
                                               {name:'	Toulouse	Station', address:' Street 1', city:City.find(			53	), agency: Agency.find(8)},
                                               {name:'	Berlin	Station', address:' Street 1', city:City.find(			54	), agency: Agency.find(8)},
                                               {name:'	Bremen	Station', address:' Street 1', city:City.find(			55	), agency: Agency.find(8)},
                                               {name:'	Cologne	Station', address:' Street 1', city:City.find(			56	), agency: Agency.find(8)},
                                               {name:'	Dusseldorf	Station', address:' Street 1', city:City.find(			57	), agency: Agency.find(8)},
                                               {name:'	Frankfurt	Station', address:' Street 1', city:City.find(			58	), agency: Agency.find(8)},
                                               {name:'	Friedrichshafen	Station', address:' Street 1', city:City.find(			59	), agency: Agency.find(8)},
                                               {name:'	Nuremberg	Station', address:' Street 1', city:City.find(			64	), agency: Agency.find(8)},
                                               {name:'	Florence	Station', address:' Street 1', city:City.find(			85	), agency: Agency.find(8)},
                                               {name:'	Genoa	Station', address:' Street 1', city:City.find(			87	), agency: Agency.find(8)},
                                               {name:'	Milan	Station', address:' Street 1', city:City.find(			89	), agency: Agency.find(8)},
                                               {name:'	Naples	Station', address:' Street 1', city:City.find(			90	), agency: Agency.find(8)},
                                               {name:'	Olbia	Station', address:' Street 1', city:City.find(			91	), agency: Agency.find(8)},
                                               {name:'	Trapani	Station', address:' Street 1', city:City.find(			97	), agency: Agency.find(8)},
                                               {name:'	Treviso	Station', address:' Street 1', city:City.find(			98	), agency: Agency.find(8)},
                                               {name:'	Trieste	Station', address:' Street 1', city:City.find(			99	), agency: Agency.find(8)},
                                               {name:'	Turin	Station', address:' Street 1', city:City.find(			100	), agency: Agency.find(8)},
                                               {name:'	Palanga	Station', address:' Street 1', city:City.find(			106	), agency: Agency.find(8)},
                                               {name:'	Vilnius	Station', address:' Street 1', city:City.find(			107	), agency: Agency.find(8)},
                                               {name:'	Luxembourg	Station', address:' Street 1', city:City.find(			108	), agency: Agency.find(8)},
                                               {name:'	Warsaw	Station', address:' Street 1', city:City.find(			119	), agency: Agency.find(8)},
                                               {name:'	Wroclaw	Station', address:' Street 1', city:City.find(			120	), agency: Agency.find(8)},
                                               {name:'	Beja	Station', address:' Street 1', city:City.find(			121	), agency: Agency.find(8)},
                                               {name:'	Faro	Station', address:' Street 1', city:City.find(			122	), agency: Agency.find(8)},
                                               {name:'	Funchal	Station', address:' Street 1', city:City.find(			123	), agency: Agency.find(8)},
                                               {name:'	Lisbon	Station', address:' Street 1', city:City.find(			124	), agency: Agency.find(8)},
                                               {name:'	Porto	Station', address:' Street 1', city:City.find(			125	), agency: Agency.find(8)},
                                               {name:'	Timisoara	Station', address:' Street 1', city:City.find(			129	), agency: Agency.find(8)},
                                               {name:'	Moscow	Station', address:' Street 1', city:City.find(			130	), agency: Agency.find(8)},
                                               {name:'	Saint Petersburg	Station', address:' Street 1', city:City.find(			131	), agency: Agency.find(8)},
                                               {name:'	Alicante	Station', address:' Street 1', city:City.find(			137	), agency: Agency.find(8)},
                                               {name:'	Almeria	Station', address:' Street 1', city:City.find(			138	), agency: Agency.find(8)},
                                               {name:'	Barcelona	Station', address:' Street 1', city:City.find(			139	), agency: Agency.find(8)},
                                               {name:'	Bilbao	Station', address:' Street 1', city:City.find(			140	), agency: Agency.find(8)},
                                               {name:'	Tenerife	Station', address:' Street 1', city:City.find(			149	), agency: Agency.find(8)},
                                               {name:'	Valencia	Station', address:' Street 1', city:City.find(			150	), agency: Agency.find(8)},
                                               {name:'	Basel	Station', address:' Street 1', city:City.find(			151	), agency: Agency.find(8)},
                                               {name:'	Bern	Station', address:' Street 1', city:City.find(			152	), agency: Agency.find(8)},
                                               {name:'	Edinburgh	Station', address:' Street 1', city:City.find(			166	), agency: Agency.find(8)},
                                               {name:'	Glasgow	Station', address:' Street 1', city:City.find(			167	), agency: Agency.find(8)},
                                               {name:'	London	Station', address:' Street 1', city:City.find(			168	), agency: Agency.find(8)},
                                               {name:'	Manchester	Station', address:' Street 1', city:City.find(			169	), agency: Agency.find(8)}

                                           ])
end